### ISSUE TITLE
RStudio crashes when encountering TF abortion

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/tensorflow#104]
When I run the following code, RStudio crashes:

```
  devtools::install_github(rstudio/tflearn)
  library(tflearn)
  mtcars$vs <- as.factor(mtcars$vs)
  feature_columns <- construct_feature_columns(mtcars, c("drat", "cyl"))
  constructed_input_fn <- construct_input_fn(mtcars, response = "vs",
                                             features = c("drat", "cyl"),
                                             id_column = "id_column")

  clf <-
    svm_classifier(
      feature_columns = feature_columns,
      example_id_column = "id_column",
      weight_column_name = "drat"
    ) %>% fit(input_fn = constructed_input_fn)

```

When I run it using `Rscript`, I got the following error:

```
2017-03-15 12:19:15.781128: F tensorflow/core/framework/tensor_shape.cc:36] Check failed: NDIMS == dims() (2 vs. 1)Asking for tensor of 2 dimensions from a tensor of 1 dimensions
Abort trap: 6
```

Any ideas? @jjallaire

**Comment by jjallaire** [comment]
Those appear to be the same crash just manifest in different ways inside and outside of the IDE.

As for why a tensor of 2 dimensions is being asked for from a tensor of 1 dimension I'm not sure (that is inherent to whatever this code is doing). I would try to break down the example into the smallest possible bit of code that exhibits this error so we can see where a conversion might be either improperly handled or improperly setup.

**Comment by terrytangyuan** [comment]
Okay as long as this crash is expected in RStudio. Thanks!

**Comment by terrytangyuan** [comment]
BTW, speaking on crashes, when I run reticulate tests twice, RStudio
crashes. Could you try if you can reproduce it on your end?

**Comment by jjallaire** [comment]
I can reproduce this, but I don't think it's actually a problem. The issue
is that devtools::test will attempt to "tear down" the reticulate package
and then re-load it for the next call to devtools::test. This doesn't
really work with the embedded Python interpreter (you initialize it once
per process and it needs to keep running, you can't unload and then reload
it).

On Wed, Mar 15, 2017 at 2:54 PM, Yuan (Terry) Tang <notifications@github.com

**Comment by terrytangyuan** [comment]
Got it. Thanks for the clarification!
