### ISSUE TITLE
error in iris example code

### ISSUE THREAD

**Issue by mwhitaker** [rstudio/tensorflow#107]
Hi there,

Many thanks for a great package! I was working through the [iris example](https://github.com/rstudio/tensorflow/tree/master/inst/examples/tflearn) and I get an error when I run `classifier$fit(x = training_set$data, y = training_set$target, steps = 2000L)`:

> Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'NoneType' object has no attribute 'f_code'

The Tensorflow API itself may have changed so maybe you'd set up this particular example differently now? I suspect it's not really related to your R package, but I thought I'd bring it to your attention.

Am running R version 3.3.3 (2017-03-06), Platform: x86_64-apple-darwin13.4.0 (64-bit), tensorflow version 1.0.1.

**Comment by jjallaire** [comment]
@terrytangyuan Any idea about this one? (it's in the simple tflearn example we have).

tflearn itself is being promoted out of contrib along with a bunch of changes so I'm not surprised that something broke here. Yuan, if this example is too out of sync with the current APIs we can just remove it for now.

@mwhitaker We are actually working on a higher level interface to tflearn right now which we hope to have news on in the coming months. Stay tuned!

**Comment by terrytangyuan** [comment]
That looks like an error in reticulate - a bug that has been fixed long time ago - happens when trying to print the stacktrace. Can you try upgrading your reticulate and then reinstall tensorflow R?

**Comment by jjallaire** [comment]
Running with the latest reticulate reveals the actual error, here it is:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Labels dtype should be integer Instead got <dtype: 'float64'>.

Detailed traceback: 
  File "/Users/jjallaire/tensorflow/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 281, in new_func
    return func(*args, **kwargs)
  File "/Users/jjallaire/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 414, in fit
    SKCompat(self).fit(x, y, batch_size, steps, max_steps, monitors)
  File "/Users/jjallaire/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1319, in fit
    monitors=all_monitors)
  File "/Users/jjallaire/tensorflow/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 281, in new_func
    return func(*args, **kwargs)
  File "/Users/jjallaire/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 430, in fit
    loss = self._train_model(input_fn=input 
```

**Comment by terrytangyuan** [comment]
Not sure why the label dtype is not what's specified `tf$int`. I would say this `tflearn$datasets$base$load_csv_with_header` has a bug. I'd suggest postpone using tflearn until the final API is settled.

**Comment by jjallaire** [comment]
Okay, I'll remove this example for now.

**Comment by mwhitaker** [comment]
Thank you for looking into this so quickly and I shall be staying tuned!
