### ISSUE TITLE
r(studio) crashes on tf$reshape

### ISSUE THREAD

**Issue by kromme** [rstudio/tensorflow#108]
When running the advanced MINST tutorial, Rstudio keeps crashing on 
`x_image <- tf$reshape(x, shape(-1L, 28L, 28L, 1L))`

rstudio just shuts down completely.

```
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Dutch_Netherlands.1252  LC_CTYPE=Dutch_Netherlands.1252   
[3] LC_MONETARY=Dutch_Netherlands.1252 LC_NUMERIC=C                      
[5] LC_TIME=Dutch_Netherlands.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tensorflow_0.7        reticulate_0.7.0.9000 RevoUtilsMath_8.0.3  

loaded via a namespace (and not attached):
[1] RevoUtils_10.0.1 tools_3.3.1      Rcpp_0.12.10 
```

**Comment by jjallaire** [comment]
Hmm...I'm not able to repro this. I tried on the Mac w/ TensorFlow (dev version) and on Windows with both TensorFlow 0.12.1 and 1.0.1. What is your version of both TensorFlow and RStudio?

**Comment by terrytangyuan** [comment]
Could you also try it using Rscript in the console?

**Comment by kromme** [comment]
found it! assigned capital `X` instead of `x`. so it couldn't find input.

**Comment by jjallaire** [comment]
Great, glad you figured it out!

Could you send us a quick snippet of code which does crash in this scenario? (that will help us establish whether there is anything we can do in the package to prevent the crash or whether it's something in tensorflow itself).

**Comment by kromme** [comment]
adjusted some more code and cant reproduce it anymore. just getting an error now! i'll try to reproduce the error
