### ISSUE TITLE
Estimator API via R

### ISSUE THREAD

**Issue by dfalbel** [rstudio/tensorflow#109]
I'm trying to use the Estimator API from TensorFlow using the R package with the following code:

```
library(tensorflow)
model_fn_lib <- tf$contrib$learn$python$learn$estimators$model_fn
model_fn <- function(features, targets, mode, params){
  
  output <- tf$contrib$layers$linear(features, 1L)
  
  predictions <- tf$reshape(output, shape(-1L))
  predictions_dict <- dict(predictions = predictions)
  
  loss <- tf$losses$mean_squared_error(targets, predictions)
  
  eval_metric_ops <- dict(
    rmse = tf$metrics$root_mean_squared_error(tf$cast(targets, tf$float64), predictions) 
  )
  
  train_op <- tf$contrib$layers$optimize_loss(
    loss = loss,
    global_step = tf$contrib$framework$get_global_step(),
    learning_rate = params[["learning_rate"]],
    optimizer = "SGD"
  )
  
  model_fn_lib$ModelFnOps(
    mode = mode,
    predictions = predictions_dict,
    loss = loss,
    train_op = train_op,
    eval_metric_ops = eval_metric_ops
  )
}

tf_lm <- tf$contrib$learn$Estimator(model_fn = model_fn, params = dict(learning_rate = 0.5))
```
This generates an error, after trying to instantiate the estimator. Something related to the `params` argument.

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Estimator's model_fn (<function python_function at 0x7fb3fbf7b398>) has less than 4 arguments, but not None params ({'learning_rate': 0.5}) are passed.

Detailed traceback: 
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1097, in __init__
    (model_fn, params))
```

I don't know what happens exactly but I think it's related to how the R package receives `dict`s as arguments... The equivalent python code works fine (I can attach it if you need)

Documentation for creating estimators can be found [here](https://www.tensorflow.org/extend/estimators#constructing_the_model_fn)

I am using latest `tensorflow` from Github and 

```
> tf$VERSION
[1] "1.0.1"
```

**Comment by jjallaire** [comment]
@dfalbel I just added you to another repo where we are working on a TF learn interface (it's private for now because the interface his highly subject to change).

**Comment by terrytangyuan** [comment]
@dfalbel I just put some docs recently. This section might be of interest to you: https://github.com/rstudio/tflearn/blob/master/inst/docs/architecture_notes.md#custom-estimator

**Comment by dfalbel** [comment]
Oh thanks!! I'm trying to use the custom_model interface but I'm still struggling..  I think it's related to the changes on TensorFllow API. 

I'm using this to train the model as found in the docs:

```
constructed_input_fn <- input_fn(
  x = iris,
  response = "Species",
  features = c(
    "Sepal.Length",
    "Sepal.Width",
    "Petal.Length",
    "Petal.Width"),
  features_as_named_list = FALSE
)

custom_model_fn <- function(features, labels, mode, params, config) {
  labels <- tf$one_hot(labels, 3L)
  
  # Create three fully connected layers respectively of size 10, 20, and 10 with
  # each layer having a dropout probability of 0.1.
  logits <- features %>%
    tf$contrib$layers$stack(
      tf$contrib$layers$fully_connected, c(10L, 20L, 10L),
      normalizer_fn = tf$contrib$layers$dropout,
      normalizer_params = list(keep_prob = 0.9)) %>%
    tf$contrib$layers$fully_connected(3L, activation_fn = NULL) # Compute logits (1 per class) and compute loss.
  
  loss <- tf$losses$softmax_cross_entropy(labels, logits)
  predictions <- list(
    class = tf$argmax(logits, 1L),
    prob = tf$nn$softmax(logits))
  
  # Create a tensor for training op.
  train_op <- tf$contrib$layers$optimize_loss(
    loss,
    tf$contrib$framework$get_global_step(),
    optimizer = 'Adagrad',
    learning_rate = 0.1)
  
  return(estimator_spec(predictions, loss, train_op, mode))
}

# Initialize and fit the model using the the custom model function we defined
# and the constructed_input_fn that represents the input data source.  
classifier <- estimator(model_fn = custom_model_fn)
classifier <- fit(classifier, input_fn = constructed_input_fn, steps = 2L)
```

But `predict` didn`t work:

```
> predict(classifier, input_fn = constructed_input_fn)
 Show Traceback
 
 Rerun with Debug
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: predict() got an unexpected keyword argument 'checkpoint_path' 
```

I tried with TF version 1.0.1 and the latest TF 1.1.0-rc1

Also, I found some small things I may be able to fix like this warning:

```
classifier <- estimator(model_fn = custom_model_fn)
WARNING:tensorflow:Estimator's model_fn (<function model_function at 0x7f6e81d88320>) includes params argument, but params are not passed to Estimator.
```

When the model_fn doesn't have all parameters. Can I open a pull request later?
Thanks again!

**Comment by terrytangyuan** [comment]
Yep for sure! The argument checkpoint_dir was recently added by me. Installing the nightly builds of TensorFlow should work.

**Comment by dfalbel** [comment]
@terrytangyuan I'm still trying to predict the fitted model using `tflearn`.  I in `test-tf-custom-model.R` you have a `TODO` to fix this on python end. 

I've been trying to fix this but I didn't find anything yet. Could you point me where I should try to fix this?

When I try to predict I get the following error:

```
predictions <- predict(classifier, input_fn = constructed_input_fn)
WARNING:tensorflow:Input graph does not contain a QueueRunner. That means predict yields forever. This is probably a mistake.
 Show Traceback
 
 Rerun with Debug
 Error in py_iterate(x, f) : 
  ValueError: Tried to convert 'indices' to a tensor and failed. Error: None values not supported. 
```

Then I tried to use the clasifier method directly:

```
pred <- classifier$estimator$predict(constructed_input_fn$input_fn)
> pred
<generator object predict at 0x115c9df50>
Python iterator/generator (use iterate function to traverse)
```

And this returns a python `iterator`.

**Comment by terrytangyuan** [comment]
Yeah when you use iterate() on that Python iterator you'll get exactly the same issue. I haven't looked into this too much yet. This is some new bug they introduced recently during migration from contrib to core (note that it's using the Estimator API from core). The same code used to work in contrib. I'll look into this soon but keep me posted if you have any idea.

**Comment by dfalbel** [comment]
@terrytangyuan I found the problem is when we call 

```
> tf$one_hot(NULL, 3L)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Tried to convert 'indices' to a tensor and failed. Error: None values not supported.
```

This happens in predict when TF calls the first line of the custom model_fn:

`labels <- tf$one_hot(labels, 3L)`

If we rearrange the order of the custom function and early return when the mode is "infer" we resolve this error. Eg defining the function below:

```
custom_model_fn <- function(features, labels, mode, params, config) {
    # Create three fully connected layers respectively of size 10, 20, and 10 with
    # each layer having a dropout probability of 0.1.
    logits <- features %>%
      tf$contrib$layers$stack(
        tf$contrib$layers$fully_connected, c(10L, 20L, 10L),
        normalizer_fn = tf$contrib$layers$dropout,
        normalizer_params = list(keep_prob = 0.9)) %>%
      tf$contrib$layers$fully_connected(3L, activation_fn = NULL) # Compute logits (1 per class) and compute loss.

    predictions <- list(
      class = tf$argmax(logits, 1L),
      prob = tf$nn$softmax(logits))
    
    if(mode == "infer"){
      return(estimator_spec(predictions = predictions, mode = mode, loss = NULL, train_op = NULL))
    }
    
    labels <- tf$one_hot(labels, 3L)
    loss <- tf$losses$softmax_cross_entropy(labels, logits)
    
    # Create a tensor for training op.
    train_op <- tf$contrib$layers$optimize_loss(
      loss,
      tf$contrib$framework$get_global_step(),
      optimizer = 'Adagrad',
      learning_rate = 0.1)

    return(estimator_spec(predictions, loss, train_op, mode))
  }
```

Now the problem is that predictions really yieds forever like the the warning was saying:

`WARNING:tensorflow:Input graph does not contain a QueueRunner. That means predict yields forever. This is probably a mistake.
`

Do you think it makes sense to make `tflearn::input_fn` a higher level wrapper for `numpy_input_fn` here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/estimator/inputs/numpy_io.py

I think this may fix the problem.

Thanks

**Comment by terrytangyuan** [comment]
Nice found! Yep passing `NULL` predictions to one_hot causes the issue. I am trying to find a way to avoid this for users. Do you think it's intuitive enough for `if(mode == "infer")` and move the logic around in the custom function though?

Regarding `"WARNING:tensorflow:Input graph does not contain a QueueRunner. That means predict yields forever. This is probably a mistake"`, I am looking into why `QueueRunner` is not attached to the graph. We can try make `numpy_input_fn` work too in the meantime. You are welcome to add it!

**Comment by dfalbel** [comment]
This is not intuitive :( We could do like in keras. You define your model in terms of what is your input and what is your output, then with other API you define the optimization steps. Maybe custom models could be defined by 2 functions: model_fn and train_fn/optimization_fn?

Thanks! I'll try to make numpy_input_fn work!

**Comment by jjallaire** [comment]
@dfalbel I just added you to another repo where we are working on some related things. There is no readme but if you just open docs/index.html you'll see the work in progress there.

**Comment by dfalbel** [comment]
@jjallaire  Thanks! I answered your e-mail

@terrytangyuan we could also force the user to define defaults for the arguments in the custom_model_fn. Something like:

```
custom_model_fn <- function(
    features = tf$placeholder(tf$float32, shape(NULL, 4)), 
    labels = tf$placeholder(tf$string, shape(NULL, 1)), 
    mode, params, config) {
    ...
}
```

This is usefull for debugging and It solves the problem of "early-returning".

**Comment by terrytangyuan** [comment]
I've splitted this into separate issues in tflearn repo. @jjallaire Should we close this one?

**Comment by ElianoMarques** [comment]
@jjallaire could you add me to the repo too?

**Comment by jjallaire** [comment]
Done!

**Comment by kevinykuo** [comment]
@jjallaire could you add me too please?

**Comment by BillWeld** [comment]
@jjallaire I'm also interested in the TF Learn work--please add me to if it's convenient.

**Comment by adder** [comment]
Hi, If you want, you can all add me to the tf learn repo. :)

I had some succes using the keras backend from tensorflow contrib, but Im stuck trying to train more complex networks.

thanks in advance

**Comment by jjallaire** [comment]
@adder The tflearn repo won't help you much with kears as it stands today. However, we have some work on a Keras interface coming soon. Stay tuned!

**Comment by adder** [comment]
Hey,
I asked for the tflearn repo because I wanted to do more complex things with the estimator API (not keras) that I cant do with the current keras API. :)

Also eager to see your Keras interface!
You guys are doing great work with R tensorflow !
I'm using it in my research.
