### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by patrickmineault** [rstudio/tensorflow#11]
There's no LICENSE file in this repo, or any licensing indication. Please specify the license so that people know whether it's usable, e.g. in a corporate setting.

**Comment by jjallaire** [comment]
R packages don't necessarily include a LICENSE file. The license is always within the DESCRIPTION file: https://github.com/rstudio/tensorflow/blob/master/DESCRIPTION#L28

**Comment by jjallaire** [comment]
I'll add a LICENSE file so the GitHub license display kicks in.

**Comment by eddelbuettel** [comment]
@patrickmineault Every R package has that specified as a field in its `DESCRIPTION` file.

If anything then this is a bug at GtiHub for not displaying it.

**Comment by patrickmineault** [comment]
Great!

**Comment by hadley** [comment]
BTW @jimhester has been working with github to add autodetection for R's standard licensing mechanism: https://github.com/benbalter/licensee/pull/129
