### ISSUE TITLE
Trying to use tf$image$ResizeMethod$NEAREST_NEIGHBOR

### ISSUE THREAD

**Issue by markdumke** [rstudio/tensorflow#110]
I'm trying to use the following code and it doesn't work.

```
library(tensorflow)
input_state = tf$placeholder(tf$uint8, shape(210L, 160L, 3L))
output = tf$image$rgb_to_grayscale(input_state)
output = tf$image$crop_to_bounding_box(output, 34L, 0L, 160L, 160L)
output = tf$image$resize_images(output, shape(84L, 84L),
  method = tf$image$ResizeMethod$NEAREST_NEIGHBOR) 
```

`tf$image$ResizeMethod$NEAREST_NEIGHBOR` fails, though it does work in Python 3. Can somebody help?

**Comment by jjallaire** [comment]
Thanks for the report! Should be fixed now, you can test by installing the development version of the package from GitHub:

```r
devtools::install_github("rstudio/tensorflow")
```

**Comment by markdumke** [comment]
This does not work for me. Now every initialization of a placeholder fails with 

**Error in py_initialize(config$python, config$libpython, config$pythonhome,  : 
  expecting a string**

**Comment by jjallaire** [comment]
That error message indicates that there was a problem with installation (the newer version of the package is talking to an older version of the package DLL). Try exiting all R sessions, coming back in, then re-executing `devtools::install_github("rstudio/tensorflow")`

**Comment by markdumke** [comment]
Excellent. That did it!
