### ISSUE TITLE
Assigning tensorflow functions to variables and testing equivalency

### ISSUE THREAD

**Issue by traversc** [rstudio/tensorflow#115]
Here is an example in Python:

```
In [1]: import tensorflow as tf
In [2]: activation = tf.tanh
In [3]: activation == tf.tanh
Out[3]: True
```

However, in R the same operation returns false or produces an error:

```
> library(tensorflow)
> activation=tf$tanh

> activation == tf$tanh
Error in activation == tf$tanh :
  comparison (1) is possible only for atomic and list types

> identical(activation, tf$tanh)
[1] FALSE
```

Is there a way to test this in R?

**Comment by jjallaire** [comment]
Good one! We hadn't yet implement the basic comparison operators for Python objects. Now implemented here: https://github.com/rstudio/reticulate/pull/57
