### ISSUE TITLE
Issue for installation: ‘reticulate’ package,  on 20170517

### ISSUE THREAD

**Issue by FightInFaith** [rstudio/tensorflow#117]
Hi
It's the first time I installed tensorflow & python 3.5
Follow the guide@https://rstudio.github.io/tensorflow/installation.html
devtools::install_github("rstudio/tensorflow")  # work

library("tensorflow")

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘reticulate’ 0.7 is being loaded, but >= 0.7.0.9017 is required
Error: package or namespace load failed for ‘tensorflow’
###
I checked the package 'reticulate', released March,14,2017. The 0.7 ed. may be the latest.
Reinstall and update are also tried. 
Is there anything I missed? 

Thank you.

**Comment by jjallaire** [comment]
If you have a current version of devtools then the command `devtools::install_github("rstudio/tensorflow") ` should actually install the new version of reticulate automatically.

Try updating reticulate manually:

```r
devtools::install_github("rstudio/reticulate")
```

Then restart R and try installing tensorflow again.

**Comment by FightInFaith** [comment]
Hi~ jjallaire
After your comment, it shows 
> sess$run(hello)
b'Hello, TensorFlow!'
now. Thank you^__^
> sessionInfo() 
...reticulate_0.7.0.9017 jsonlite_1.4  

##########
# By the way, I am sort of sure that it's the first time that I do anything about Python and TensorFlow in R.(Win10). No previous "reticulate" package installed.

# All the lines are 

> install.packages("tensorflow")  # It can be run with something into Local. Not sure if reticulate 0.7 ed comes from here
> library(tensorflow)  # failed

### Then I followed the guide
> install.packages("devtools")
> library(devtools)
> devtools::install_github("rstudio/tensorflow")  # worked
> library(tensorflow)
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
namespace ‘reticulate’ 0.7 is being loaded, but >= 0.7.0.9017 is required
Error: package or namespace load failed for ‘tensorflow’

> install.packages("reticulate")  # worked but got 0.7 ed still.  update.packages("reticulate") also
> library(tensorflow)  # failed

# Then I installed the Python 3.61 and tensorflow form https://www.tensorflow.org/, but didn't work
### After your comment 
> devtools::install_github("rstudio/reticulate")  # work
> library(tensorflow)  # work
> install_tensorflow() # work
...
> sess$run(hello)
b'Hello, TensorFlow!'

##########
By the way, in my RStudio, code from https://rstudio.github.io/tensorflow/index.html
....
> for (step in 1:201) {
+   sess$run(train)
+   if (step %% 20 == 0)
+     cat(step, "-", sess$run(W), sess$run(b), "\n")
+ }
20 - 
Error in cat(list(...), file, sep, fill, labels, append) : 
  argument 3 (type 'environment') cannot be handled by 'cat'

# paste0() works here
##########
Thank you and RStudio team

Best wish

**Comment by jjallaire** [comment]
Great, glad things are working now!
