### ISSUE TITLE
Change Python Environment when using Anaconda

### ISSUE THREAD

**Issue by eisioriginal** [rstudio/tensorflow#119]
The library installs an Anaconda environment which must be actively set when using the package:

#set anaconda to tensor flow environment
reticulate::use_condaenv("r-tensorflow")

This can be done via reticulate but isn't executed via the library. In windows this prevents the library from working if r-tensorflow is not the standard environment for Python.

Thank you very much for the great package!

Andreas

**Comment by jjallaire** [comment]
That conda env should be found when you go to use tensorflow *unless* you've got other things going on that cause another python environment to be found first. You can see here that the conda envs are given first priority after any explicitly requested environments (via environment variable or use_ directive): https://github.com/rstudio/reticulate/blob/master/R/config.R#L95-L107

What is the output of `tf_config()` (that will show other versions being scanned).

**Comment by jjallaire** [comment]
Also what's the output of:

reticulate::py_config

**Comment by eisioriginal** [comment]
Yes, I agree, but if you are on Ubuntu it uses many libraries (sssd etc.) which require Python. In almost ever installation the system python has larger priority there. So one must actively set the Python environment beforehand. On windows it is a bit easier but if another Python was used prior to Anaconda one must set the environment actively as well. I guess adding something like:

library(reticulate)
use_condaenv(condaenv = "deeplearning_R", conda = "/opt/anaconda3/bin/conda")

to the documentation would be very helpful for the users.

**Comment by jjallaire** [comment]
Okay, added an additional note to the docs here: https://github.com/rstudio/reticulate/commit/3209d85f5143b37f4fbd533ebaf94f0aadb4bb8a

**Comment by andreidi** [comment]
Hi there !
I have the following issue: although I use "use_condaenv" it seems my R still uses the root environment. This is easily self-explained by the following commands/outputs:
> conda_list()
          name                                                               python
1 r-tensorflow C:\\Users\\Andrei\\Documents\\.conda\\envs\\r-tensorflow\\python.exe
> use_condaenv("r-tensorflow")
> tf_config()
Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\Program Files\Anaconda3\python.exe
 C:\Program Files\Anaconda3\python.exe

You can install TensorFlow using the install_tensorflow() function.

**Comment by jjallaire** [comment]
This might happen for a number of reasons:

1) The installation of TensorFlow into the r-tensorflow conda env failed for some reason after the environment was created.

2) There is a mismatch in architecture between your R session and the Anaconda architecture (e.g. 64-bit R with 32-bit Anaconda or 32-bit R with 64-bit Anaconda)

3) Anaconda is having trouble loading within your R session (we've seen this happen with conflicting versions of MKL when running Anaconda under Microsoft R Open)

**Comment by andreidi** [comment]
Found a workaround and the actual culprit: MS Visual Studio 2017.

So basically initially I installed MS VS 2017 that included Anaconda3 4.3 and I got the previous explained behavior.

I uninstalled the MS VS installed Conda and I re-installed with normal 4.4 installation. After this everything worked just peachy. Obviously it is a bug within the MS VS 2017 environment/installation.

So I recommend anyone who uses MS VS 2017 to install Anaconda3 separately and there will be no trouble !

**Comment by jjallaire** [comment]
Okay, thanks for letting us know!

FWIW I just installed Visual Studio 2017 w/ Andaconda 3 4.3 and things did work as expected, so there might be some additional local configuration issues that led your environment to not work (hard to say of course as there are so many variables in play!)
