### ISSUE TITLE
install_tensorflow() not working on linux

### ISSUE THREAD

**Issue by adder** [rstudio/tensorflow#120]
I get the following output when trying to run `install_tensorflow()`.

    Unable to install TensorFlow on this platform. Binary installation is available for Windows, Linux, and Ubuntu.

I'm on Arch linux and installing tensorflow through pip works just fine.
````
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS: /usr/lib/libblas.so.3.7.0
LAPACK: /usr/lib/liblapack.so.3.7.0

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tensorflow_0.8

loaded via a namespace (and not attached):
 [1] httr_1.2.1        compiler_3.4.0    R6_2.2.0          tools_3.4.0      
 [5] withr_1.0.2       curl_2.6          Rcpp_0.12.11      reticulate_0.8   
 [9] highlight_0.4.7.1 memoise_1.1.0     knitr_1.15.1      git2r_0.18.0     
[13] jsonlite_1.4      digest_0.6.12     devtools_1.12.0  
````

**Comment by jjallaire** [comment]
Interesting, I was keying off the fact that the TensorFlow project emphasizes Ubuntu to the exclusion of other distros: https://www.tensorflow.org/install/

But just noticed this:

> This guide explains how to install TensorFlow on Ubuntu. These instructions might also work on other Linux variants, but we have only tested (and we only support) these instructions on Ubuntu 14.04 or higher.

So perhaps we should just allow installation to proceed on other variants.

**Comment by eddelbuettel** [comment]
Maybe relax it one by one?  Or turn the "no soup for you" error into a stern warning and proceed?

**Comment by jjallaire** [comment]
Working on a change now to allow this to proceed w/ distinct installation
instructions for non-Ubuntu Linux (for Ubuntu we provide the apt-get
commands to execute, for other Linux we'll just say "install pip and
virtualenv" if they aren't already there).

On Wed, May 24, 2017 at 8:49 AM, Dirk Eddelbuettel <notifications@github.com

**Comment by jjallaire** [comment]
Okay, this should now be fixed. Could you try again on arch after installing the dev version to make sure things work as expected?

**Comment by adder** [comment]
Woow, fast response.

Seems to be working. 
No error during installation and I can call tensorflow functions.

Thanks!!
