### ISSUE TITLE
A very wee tiny little thing

### ISSUE THREAD

**Issue by witusj** [rstudio/tensorflow#122]
Shouldn't the last variable in the MNIST for Experts code be called `test_accuracy`:

`train_accuracy <- accuracy$eval(feed_dict = dict(
     x = mnist$test$images, y_ = mnist$test$labels, keep_prob = 1.0))
`
?

**Comment by jjallaire** [comment]
Indeed it should! Thanks, just fixed.

**Comment by witusj** [comment]
And many thanks to you for opening up Tensorflow to R. Beautiful stuff!

**Comment by jjallaire** [comment]
Thanks, more to come very soon!
