### ISSUE TITLE
summary ops no longer available?

### ISSUE THREAD

**Issue by zcesur** [rstudio/tensorflow#124]
### Describe the problem
As I was going through the MNIST tutorials, I have come across the following issue.
```{bash}
Error in py_get_attr_impl(x, name, silent) :
  AttributeError: 'module' object has no attribute 'summary'
Calls: with ... $.python.builtin.object -> py_get_attr -> py_get_attr_impl -> .Call
Execution halted
```
It seems to me that either the error is on my end, or some modules like `summary` and `global_variables_initializer` are removed despite they are still being used in the examples that are given on [TensorFlow Mechanics 101](https://tensorflow.rstudio.com/tutorial_tensorflow_mechanics.html). Below is the exact command to reproduce my output.

```{bash}
wget https://raw.githubusercontent.com/rstudio/tensorflow/master/inst/examples/mnist/fully_connected_feed.R && wget https://raw.githubusercontent.com/rstudio/tensorflow/master/inst/examples/mnist/mnist.R && Rscript fully_connected_feed.R
```

### System information
```{bash}
$ Rscript -e "library(tensorflow); sessionInfo()"

R version 3.3.2 (2016-10-31)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C             
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8   
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8  
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                
 [9] LC_ADDRESS=C               LC_TELEPHONE=C           
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C      

attached base packages:
[1] stats     graphics  grDevices utils     datasets  base    

other attached packages:
[1] tensorflow_0.8.2

loaded via a namespace (and not attached):
[1] Rcpp_0.12.11   reticulate_0.8 methods_3.3.2  jsonlite_1.4  
```

**Comment by jjallaire** [comment]
I think it depends on the version of TensorFlow you are running. I am able to successfully run the example on both TensorFlow v1.1 as well as the release candidate of TensorFlow v1.2. Perhaps you are running TensorFlow v1.0 or older? You can find out via:

```r
tf_config()
```

**Comment by zcesurr** [comment]
Upgrading TensorFlow from v0.9 to v1.1 fixed the issue. Thanks!

**Comment by zcesur** [comment]
Upgrading TensorFlow from v0.9 to v1.1 fixed the issue. Thanks!
