### ISSUE TITLE
datasets <- tf$contrib$learn$datasets cannot work

### ISSUE THREAD

**Issue by JTigerChen** [rstudio/tensorflow#126]
datasets <- tf$contrib$learn$datasets cannot work in Mac,it seems that there are some function names \paremeter names are changed——for example,"global_variables_initializer()" is replaced by "initialize_all_variables()" ——and I can not find out this time which is the replacement of"tf$contrib",
the error :
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: 'module' object has no attribute 'contrib'

can you tell the right TT

**Comment by jjallaire** [comment]
This might vary by TensorFlow version. I am running TF v1.1 and there is no problem accessing `tf$contrib$learn$datasets`

**Comment by JTigerChen** [comment]
thank you, it was!! @jjallaire
