### ISSUE TITLE
Show python documentation in R

### ISSUE THREAD

**Issue by fritzo** [rstudio/tensorflow#127]
In python I can get lots of useful documentation via `help()`
```
>>> import tensorflow as tf
>>> help(tf.placeholder)
Help on function placeholder in module tensorflow.python.ops.array_ops:

placeholder(dtype, shape=None, name=None)
    Inserts a placeholder for a tensor that will be always fed.
    
    **Important**: This tensor will produce an error if evaluated. Its value must
    ...
```
But in R the documentation is not available
```
> library(tensorflow)
> ?tf$placeholder
no method defined for function ‘$’ and signature ‘x = "python.builtin.module"’Error in .helpForCall(topicExpr, parent.frame()) : 
  no documentation for function ‘$’ and signature ‘x = "python.builtin.module"’
```
Do you have any idea how hard it would be to connect the python documentation to R?

**Comment by StevenLShafer** [comment]
I have python 2.7 and 3.5 installed. Current tensorflow instructions recommend 3.5. However, I cannot get beyond the following error in Rstudio: 

tf$Session()
Error in system2(python, stdout = TRUE, args = c("-c", shQuote("import sys; import platform; sys.stdout.write(platform.architecture()[0])"))) : 
  '"C:\Python27\/python.exe"' not found

My attempts to set TENSORFLOW_PYTHON as recommended in the document don't help. Is Python27 hardcoded somewhere?

I see elsewhere that this issue might have been raised and resolved, but the recommendations in the installation document to override python27 don't seem to work.

**Comment by fritzo** [comment]
@StevenLShafer I believe your problem is independent from this issue (which concerns only `?` functionality once tensorflow is installed). It sounds like your problem deserves a new issue.

**Comment by fritzo** [comment]
This can be done using the [`reticulate`](https://github.com/rstudio/reticulate) package:
```r
> library(reticulate)
> py <- import_builtins()
> py$help(tf$placeholder)
Help on function placeholder in module tensorflow.python.ops.array_ops:

placeholder(dtype, shape=None, name=None)
    Inserts a placeholder for a tensor that will be always fed.
    
    **Important**: This tensor will produce an error if evaluated. Its value must
    ...
```

**Comment by jjallaire** [comment]
When inside a recent version of RStudio you can also see some docs when you type the `$` operator, e.g.
<img width="878" alt="screen shot 2017-06-06 at 10 44 11 am" src="https://user-images.githubusercontent.com/104391/26843461-2c285a82-4aa5-11e7-9a91-8debc3eabb0c.png">
