### ISSUE TITLE
How to install tensorflow for R offline

### ISSUE THREAD

**Issue by dslate** [rstudio/tensorflow#128]
I have some x86_64 computers running Ubuntu Linux 16.04.2 LTS and R version 3.4.0 on which I wanted to install TensorFlow and its R interface.  One of the computers is on the Internet, and on it I had no difficulties installing the R tensorflow package and then successfully running install_tensorflow() from R.  However, the other computers are not connected to the Internet.  Is there a "recommended" way to perform the offline equivalent of install_tensorflow()?

Thanks.

**Comment by jjallaire** [comment]
I think for this case you should do a manual installation using pip (where you point to a local whl package). Note that in this you'll also have to determine the recursive dependencies of the tensorflow package and get the whl file for each of those as well. 

Here's documentation on what happens under the hood for `install_tensorflow`: https://tensorflow.rstudio.com/installation.html#custom_installation
