### ISSUE TITLE
indexing tensors

### ISSUE THREAD

**Issue by goldingn** [rstudio/tensorflow#13]
Thanks you so much for this package!

This is a feature request: would it be possible to provide a slimmer syntax for subsetting tensors to match python/tf tensor subsetting, preferably using R's `[`?

i.e., I can do this in Python:
```python
import tensorflow as tf
x = tf.zeros(3)
y = x[1]
sess = tf.Session()
sess.run(y)
```
```
0.0
```
but in R, no dice:
```r
library (tensorflow)
x = tf$zeros(3)
y = x[1]
```
```
Error in x[1] : object of type 'externalptr' is not subsettable
```

I can use other tf functions like `slice` and `gather`, but it's fairly clunky:
```r
y = tf$gather(x, 1L)
sess = tf$Session()
sess$run(y)
```
```
[1] 0
```

**Comment by jjallaire** [comment]
Yes, it should be very straightforward to do this. One thing that's a bit tricky about tensors is that they are 0-based (reflecting the fact that C++ and Python/numpy are 0-based). I'm thinking that the subsetting operators should reflect this as well (otherwise there will be confusion between subsetting functions that are 0-based and operators that are 1-based).

I should be able to get to this early next week. In case you want to play around with this in the meantime the `tf_generics.R` file has a bunch of other customer operators for Tensors: https://github.com/rstudio/tensorflow/blob/master/R/tf_generics.R#L57-L60

**Comment by goldingn** [comment]
Great, thanks! Hopefully I'll l find some time to try implementing this myself. 

I agree, it would be less confusing to keep it 0-indexed. It would be good to flag this to the user, though I'm not sure which doc would be best

**Comment by jjallaire** [comment]
I put a stub in for the generic here: https://github.com/rstudio/tensorflow/commit/3c1c48b1fb877ebd7e6a93d0b3469c0e0203869d

If you could give me a PR for the implementation that would be great.

**Comment by goldingn** [comment]
Some more details of the prototype implementation in the PR:

#### Indexing
Indices are taken to be zero-indexed, inclusive at the lower end and
non-inclusive at the upper end, as in numpy & tensorflow.

#### Syntax
I've attempted to implement a subset of the numpy/tensorflow syntax, with Python's standalone `:` replaced with a blank entry for the default index. I.e. these are equivalent (assuming e.g. a 4x3 Tensor `x`):

python: `x[1, 2]`
R: `x[1, 2]`
(scalar)

python: `x[1:3, 2]`
R: `x[1:3, 2]`
(column vector)

python: `x[1, :]`
R: `x[1, ]`
(row vector)

python: `x[1]`
R: `x[1]`
(row vector, equivalent to the above)

But there is no analogue of this python syntax:
`x[1:, 2]`
`x[:3, 2]`
`x[1:3:2, 2]`

It's not clear that this is the best approach. Either fully replicating python syntax, or using standard R indexing might be preferable.

#### Size 0 indices
The behaviour appears to match the Python API's in most cases, except that this R implementation can't handle  indices that lead to size 0 in one dimension.
I.e. for a 3x2 Tensor `x`, doing `x[0:2, 1:1]` (which has size 0 in the second dimension, because the index is non-inclusive) returns different Tensors in the python vs R APIs:
python: `Tensor(..., shape(2, 0), ...)`
R: `Tensor(..., shape(2,), ...)`
The python behaviour could be matched by parsing the call and grepping for colons, but with the current implementation `1:1` is indistinguishable from `1`

#### Default indices
This implementation also cannot handle a missing (default) index between the third and final dimension, where there is an index for a later dimension. I.e. for a
2x2x2x2 Tensor `x`:
  `x[0:1, 1:2, :, 0:1]` works in python,
but the corresponding:
  `x[0:1, 1:2, , 0:1]` fails in R because: **'argument is missing, with no default'** which makes sense, given indices beyond the first two are passed via the dots argument.

R's base array indexing can handle these sorts of missing indices but I haven't yet dug into the call path for those and how best to handle it here

The following does work (by accident rather than design) and is equivalent to the python above:
`x[0:1, 1:2, NA, 0:1]`

#### Testing
Non-existent so far...

**Comment by goldingn** [comment]
Thanks both!
