### ISSUE TITLE
Package Installation Error

### ISSUE THREAD

**Issue by rajafan** [rstudio/tensorflow#133]
Hi everyone, 

I would like to install the tensorflow package in R. While trying the command devtools::install_github("rstudio/tensorflow"), an error occurred shown as follows: "Error: Could not find build tools necessary to build reticulate". 

I did not find much help on the Internet. Any help will be much appreciated. 

Thanks.
Fan

**Comment by jjallaire** [comment]
If you are on Windows you should install Rtools: https://cran.r-project.org/bin/windows/Rtools/

If you are on the Mac you should install XCode or XCode Command Line Tools.

See https://support.rstudio.com/hc/en-us/articles/200486498-Package-Development-Prerequisites

**Comment by rajafan** [comment]
Thanks for the reply. 

I have installed Xcode and Xcode command line tools. 

Now there are prompt showing that 'Install build tools: Building R package from source requires installation of additional build tools ...'. 

I think this may not be related to the tensorflow package, but any suggestions on solving that would be appreciated.

Thanks.

**Comment by jjallaire** [comment]
There is something in your setup preventing you from using the compiler
you've installed to build R packages. I unfortunately don't have any means
of telling what that something might be! (perhaps you have other compilers
on your path, perhaps the header files installed with R are corrupted or
missing, etc.)
