### ISSUE TITLE
Error while running "install_tensorflow()"

### ISSUE THREAD

**Issue by YashwanthGithub** [rstudio/tensorflow#134]
Hi 

While installing Tensorflow in R,
```
> devtools::install_github("rstudio/tensorflow")
> library(tensorflow)
> system("python --version")
Python 3.5.3 :: Anaconda 4.4.0 (64-bit)
> install_tensorflow()
Error: Error 1 occurred installing packages into conda environment r-tensorflow
In addition: Warning message:
running command '"C:/Python2/Scripts/activate" r-tensorflow && pip install --upgrade --ignore-installed "https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.2.0-cp35-cp35m-win_amd64.whl"' had status 1
```

PYTHON_HOME is set as `C:\Python2\envs\py35; C:\Users\'username'\Documents\R\win-library\3.4`

Is there something I missed before running `install_tensorflow()`?. I have successfully installed tensorflow in Python3.5.

Thanks
Yashwanth

**Comment by jjallaire** [comment]
What if you just execute this:

```
system2("C:/Python2/Scripts/activate r-tensorflow")
```

Does C:/Python2/Scripts/activate actually exist?

I'm wondering if perhaps we are dealing with an older version of Anaconda which has some unexpected directory structure?

What do you get if you run the following from a system command window:

```
C:/Python2/Scripts/activate r-tensorflow && pip install --upgrade --ignore-installed "https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.2.0-cp35-cp35m-win_amd64.whl
```

**Comment by jjallaire** [comment]
That `PYTHON_HOME` also looks a bit fishy (as the R package library is part of PYTHON_HOME).

**Comment by jjallaire** [comment]
I can't seem to reproduce your error locally even when using the exact some base python env, setting PYTHON_HOME to the same as what you have, etc.

**Comment by YashwanthGithub** [comment]
I executed it but with warnings,
```
system2("C:/Python2/Scripts/activate r-tensorflow")
Warning message:
running command '"C:/Python2/Scripts/activate r-tensorflow"' had status 127 
```

` C:/Python2/Scripts/activate` exists as you can see below,

![activate path](https://user-images.githubusercontent.com/12031936/27271553-11a69b86-54e3-11e7-9b6c-967171b590d9.PNG)

` C:/Python2/` is where Python 2.7 is installed. As Tensorflow is compatible with Python >3.5.x, I upgraded the Python version to 3.5.2 & doing so it automatically got installed into  `C:\Python2\envs\py35` 

I tried executing

`C:/Python2/Scripts/activate r-tensorflow && pip install --upgrade --ignore-installed "https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.2.0-cp35-cp35m-win_amd64.whl` & is successful.

![activate path_2](https://user-images.githubusercontent.com/12031936/27271762-2b69bd22-54e4-11e7-800c-a9455e11458c.PNG)


`PYTHON_HOME` is fine as I can use python with NO issues. Reason I have added  `C:\Users\'username'\Documents\R\win-library\3.4` is merely a google answer. I assume it is not causing any issues because I have also tried executing `install_tensorflow()` by eliminating  
`C:\Users\'username'\Documents\R\win-library\3.4` from `PYTHON_HOME`.

I tried again after executing `system2("C:/Python2/Scripts/activate r-tensorflow")` but ends with same error
 ```
Using r-tensorflow conda environment for TensorFlow installation
Determining latest release of TensorFlow...done
Installing TensorFlow...
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'cmd' is not recognized as an internal or external command,
operable program or batch file.
'cmd' is not recognized as an internal or external command,
operable program or batch file.
Error: Error 1 occurred installing packages into conda environment r-tensorflow
In addition: Warning message:
running command '"C:/Python2/Scripts/activate" r-tensorflow && pip install --upgrade --ignore-installed "https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.2.0-cp35-cp35m-win_amd64.whl"' had status 1 
```

**Comment by jjallaire** [comment]
The fact that this works from the console:

```
C:/Python2/Scripts/activate r-tensorflow && pip install --upgrade --ignore-installed "https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.2.0-cp35-cp35m-win_amd64.whl
```

But then doesn't work from within R via `system` is very puzzling. You error message says:

```
'cmd' is not recognized as an internal or external command,
operable program or batch file.
```

So perhaps there is some issue with your system `PATH`? (i.e. maybe Windows\System32 isn't on you PATH, see https://support.cloudbees.com/hc/en-us/articles/230613127-Pipeline-bat-command-returns-Windows-error

If that's not it then I"m not sure what else to suggest. Note that the installation from outside of R is perfectly legit (you can just execute that command and the tensorflow package will use that version).

**Comment by YashwanthGithub** [comment]
Its working fine after I added `Windows\System32` to PATH variable.

Thank you very much!!!

**Comment by jjallaire** [comment]
Terrific, so happy to hear!
