### ISSUE TITLE
Issue when initializing global variables - behavior of sess$run

### ISSUE THREAD

**Issue by pjere** [rstudio/tensorflow#135]
Hello,

I am  trying to port to R the tutorial in (https://medium.com/@erikhallstrm/tensorflow-rnn-api-2bb31821b185) : after some tweaking it gets to work (I had some issues with the behavior of `tf$unstack` which requires an explicit num argument when the Python version doesn't) as far as creating the tensorflow graph is concerned.

When I try to run it in my session I get the following error :

```
sess <- tf$Session
sess$run(tf$global_variables_initializer())
```

returns :

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: run() missing 1 required positional argument: 'fetches'
```

**Comment by pjere** [comment]
The weirdness goes further :
```

sess <- tf$Session
init_op <- tf$global_variables_initializer()
sess$run(init_op)
```

will give the same error, but conversely when I run it as : 
```
init_op <- tf$global_variables_initializer()
with(tf$Session() %as% sess, {
  sess$run(init_op)
 })
```

it does work !?

**Comment by jjallaire** [comment]
See answer here: https://stackoverflow.com/questions/42858114/typeerror-run-missing-1-required-positional-argument-fetches-on-session-ru

It needs to be `sess <- tf$Session()`
