### ISSUE TITLE
Calling `sess$run` inside a function when tensorflow graph lives in global workspace returns error

### ISSUE THREAD

**Issue by markdumke** [rstudio/tensorflow#136]
I used this code and it did work recently (with an older version of R and tensorflow - now I have R 3.4 and tensorflow 0.8.7)

```
library(tensorflow)
x = tf$placeholder("float", shape(NULL, 2))
W1 = tf$Variable(tf$random_uniform(shape(2, 1), 0, 0.01))
y = tf$matmul(x, W1)
sess = tf$Session()
sess$run(tf$global_variables_initializer())

predict = function(x_) {
  sess$run(y, feed_dict = dict(x = x_))
}
predict(x_ = matrix(c(1, 2), ncol = 2))
```

Now this fails with Error: 
**TypeError: Cannot interpret feed_dict key as Tensor: The name 'x' looks like an (invalid) Operation name, not a Tensor. Tensor names must be of the form "<op_name>:<output_index>".**

When I put the placeholders x and y into the predict function it does work

```
predict = function(x, y, x_) {
  sess$run(y, feed_dict = dict(x = x_))
}
predict(x, y, x_ = matrix(c(1, 2), ncol = 2))
```

Is this a bug or desired behaviour?

**Comment by jjallaire** [comment]
Thanks for the report! This is a result of change in how we search for key names here:
https://github.com/rstudio/reticulate/commit/867b7759f02af9c85a65d5ac9a79b8bd56f6fa8c

Basically, we used to search everywhere for symbols that key names but that ended up matching on base functions, etc. I think we are now being too restrictive though, let me think about how to strike the right balance between making code work as expected and having overly greedy symbol matching.

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/reticulate/commit/198e6f68e0542ad69fcc6dc2641dc5be685deec6
