### ISSUE TITLE
I got some problem with tensorflow on R studio

### ISSUE THREAD

**Issue by MainTankJerry** [rstudio/tensorflow#137]
I got to `install_tensorflow()` step
>...
Installation of TensorFlow complete.

`library(tensorflow)`
`datasets <- tf$contrib$learn$datasets`
Then I got this message:
>Error: Python module tensorflow was not found.
Detected Python configuration:
python:         /usr/bin/python
libpython: /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
pythonhome:     /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7
version:        2.7.10 (default, Jul 30 2016, 19:40:32)  [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
numpy:          /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy
numpy_version:  1.8.1
tensorflow:     [NOT FOUND]
python versions found: 
 /usr/bin/python
 /usr/local/bin/python
 /usr/local/bin/python3
 /Users/JerryQiu/anaconda/bin/python

I cannot understand this error. What should I do?

**Comment by jjallaire** [comment]
It looks like the installation of TensorFlow didn't actually succeed. Could you re-run `install_tensorflow()` tand provide it's full output.
