### ISSUE TITLE
Error with tf$Session()

### ISSUE THREAD

**Issue by coodgee** [rstudio/tensorflow#138]
I have a windows 7 64 bit installation of Rstudio Version 1.0.143 with R 3.4.0. 

I have installed tensorflow with the command:

```
devtools::install_github("rstudio/tensorflow")
library(tensorflow)
```
The full output of the installation is below. 

But when I run 
`sess = tf$Session() `
I get the following error: 

> Error in file.exists(envs) : invalid 'file' argument

I have reinstalled both R and Rstudio. I am running python 3.5 for windows. 

My Path windows system variable is: 

> C:\ProgramData\Oracle\Java\javapath;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp;C:\Program Files (x86)\Teradata\Client\13.10\ODBC Driver for Teradata\Lib\;C:\Program Files (x86)\Teradata\Client\13.10\Shared ICU Libraries for Teradata\lib\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft Application Virtualization Client;C:\Program Files (x86)\Enterprise Vault\EVClient\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Users\c950270\AppData\Local\Programs\Python\Python35\cuda\bin;C:\Users\c950270\AppData\Local\Programs\Python\Python35;C:\Users\c950270\AppData\Local\Programs\Python\Python35\Scripts;C:\Program Files\RStudio\bin\

> > devtools::install_github("rstudio/tensorflow")
> Downloading GitHub repo rstudio/tensorflow@master
> from URL https://api.github.com/repos/rstudio/tensorflow/zipball/master
> Installing tensorflow
> Installing 1 package: processx
> also installing the dependencies ‘assertthat’, ‘crayon’, ‘debugme’
> 
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/assertthat_0.2.0.zip'
> Content type 'application/zip' length 43688 bytes (42 KB)
> downloaded 42 KB
> 
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/crayon_1.3.2.zip'
> Content type 'application/zip' length 705767 bytes (689 KB)
> downloaded 689 KB
> 
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/debugme_1.0.2.zip'
> Content type 'application/zip' length 1003609 bytes (980 KB)
> downloaded 980 KB
> 
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/processx_2.0.0.zip'
> Content type 'application/zip' length 91375 bytes (89 KB)
> downloaded 89 KB
> 
> package ‘assertthat’ successfully unpacked and MD5 sums checked
> package ‘crayon’ successfully unpacked and MD5 sums checked
> package ‘debugme’ successfully unpacked and MD5 sums checked
> package ‘processx’ successfully unpacked and MD5 sums checked
> 
> The downloaded binary packages are in
> 	C:\Users\c950270\AppData\Local\Temp\Rtmp4OpPMR\downloaded_packages
> Installing 1 package: yaml
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/yaml_2.1.14.zip'
> Content type 'application/zip' length 179611 bytes (175 KB)
> downloaded 175 KB
> 
> package ‘yaml’ successfully unpacked and MD5 sums checked
> 
> The downloaded binary packages are in
> 	C:\Users\c950270\AppData\Local\Temp\Rtmp4OpPMR\downloaded_packages
> Downloading GitHub repo rstudio/reticulate@master
> from URL https://api.github.com/repos/rstudio/reticulate/zipball/master
> Installing reticulate
> Installing 1 package: Rcpp
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/Rcpp_0.12.11.zip'
> Content type 'application/zip' length 3380126 bytes (3.2 MB)
> downloaded 3.2 MB
> 
> package ‘Rcpp’ successfully unpacked and MD5 sums checked
> 
> The downloaded binary packages are in
> 	C:\Users\c950270\AppData\Local\Temp\Rtmp4OpPMR\downloaded_packages
> "D:/Users/c950270/Documents/R/R-3.4.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
>   "C:/Users/c950270/AppData/Local/Temp/Rtmp4OpPMR/devtools33dc35b77220/rstudio-reticulate-d2158c5"  \
>   --library="D:/Users/c950270/Documents/R/R-3.4.0/library" --install-tests 
> 
> * installing *source* package 'reticulate' ...
> ** libs
> 
> *** arch - i386
> C:/RBuildTools/3.4/mingw_32/bin/g++  -I"D:/Users/c950270/Documents/R/R-3.4.0/include" -DNDEBUG  -I"D:/Users/c950270/Documents/R/R-3.4.0/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
> C:/RBuildTools/3.4/mingw_32/bin/g++  -I"D:/Users/c950270/Documents/R/R-3.4.0/include" -DNDEBUG  -I"D:/Users/c950270/Documents/R/R-3.4.0/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c interrupt.cpp -o interrupt.o
> C:/RBuildTools/3.4/mingw_32/bin/g++  -I"D:/Users/c950270/Documents/R/R-3.4.0/include" -DNDEBUG  -I"D:/Users/c950270/Documents/R/R-3.4.0/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c libpython.cpp -o libpython.o
> C:/RBuildTools/3.4/mingw_32/bin/g++  -I"D:/Users/c950270/Documents/R/R-3.4.0/include" -DNDEBUG  -I"D:/Users/c950270/Documents/R/R-3.4.0/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c python.cpp -o python.o
> C:/RBuildTools/3.4/mingw_32/bin/g++ -shared -s -static-libgcc -o reticulate.dll tmp.def RcppExports.o interrupt.o libpython.o python.o -Ld:/Compiler/gcc-4.9.3/local330/lib/i386 -Ld:/Compiler/gcc-4.9.3/local330/lib -LD:/Users/c950270/Documents/R/R-3.4.0/bin/i386 -lR
> installing to D:/Users/c950270/Documents/R/R-3.4.0/library/reticulate/libs/i386
> 
> *** arch - x64
> C:/RBuildTools/3.4/mingw_64/bin/g++  -I"D:/Users/c950270/Documents/R/R-3.4.0/include" -DNDEBUG  -I"D:/Users/c950270/Documents/R/R-3.4.0/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
> C:/RBuildTools/3.4/mingw_64/bin/g++  -I"D:/Users/c950270/Documents/R/R-3.4.0/include" -DNDEBUG  -I"D:/Users/c950270/Documents/R/R-3.4.0/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c interrupt.cpp -o interrupt.o
> C:/RBuildTools/3.4/mingw_64/bin/g++  -I"D:/Users/c950270/Documents/R/R-3.4.0/include" -DNDEBUG  -I"D:/Users/c950270/Documents/R/R-3.4.0/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c libpython.cpp -o libpython.o
> C:/RBuildTools/3.4/mingw_64/bin/g++  -I"D:/Users/c950270/Documents/R/R-3.4.0/include" -DNDEBUG  -I"D:/Users/c950270/Documents/R/R-3.4.0/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c python.cpp -o python.o
> C:/RBuildTools/3.4/mingw_64/bin/g++ -shared -s -static-libgcc -o reticulate.dll tmp.def RcppExports.o interrupt.o libpython.o python.o -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LD:/Users/c950270/Documents/R/R-3.4.0/bin/x64 -lR
> installing to D:/Users/c950270/Documents/R/R-3.4.0/library/reticulate/libs/x64
> ** R
> ** inst
> ** tests
> ** preparing package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded
> *** arch - i386
> *** arch - x64
> * DONE (reticulate)
> "D:/Users/c950270/Documents/R/R-3.4.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
>   "C:/Users/c950270/AppData/Local/Temp/Rtmp4OpPMR/devtools33dc741c408d/rstudio-tensorflow-4278b0d"  \
>   --library="D:/Users/c950270/Documents/R/R-3.4.0/library" --install-tests 
> 
> * installing *source* package 'tensorflow' ...
> ** R
> ** inst
> ** tests
> ** preparing package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** testing if installed package can be loaded
> *** arch - i386
> *** arch - x64
> * DONE (tensorflow)
> > library(tensorflow)
> > sess = tf$Session()
> Error in file.exists(envs) : invalid 'file' argument

**Comment by jjallaire** [comment]
I just pushed a fix which should eliminate the possibility of that error. Could you try again to see whether you can successfully initialize a session? Note that it's important that you exit all R sessions before initiating the install (so that shared libraries used by the packages are not in use when you install).

**Comment by coodgee** [comment]
thankyou the error is now gone. I have managed to get GPU tensorflow working after a bit of fiddling around.
