### ISSUE TITLE
unexpected behavior when extracting from tensors with undefined shape

### ISSUE THREAD

**Issue by dfalbel** [rstudio/tensorflow#139]
Suppose I have a placeholder like `x` define below and I want to extract the first column:

```
x <- tf$placeholder(tf$int16, shape = list(NULL, 1L))
x[,0L]
```
This returns the following error:

```
Error in pmin(end, x_size) : 
  (list) object cannot be coerced to type 'double'
```

The equivalent python code works fine:

```
x = tf.placeholder(tf.int16, [None, 1])
x[:,0]
<tf.Tensor 'strided_slice:0' shape=(?,) dtype=int16>
```
Also the following works as expected:

```
> x <- tf$placeholder(tf$int16, shape = list(1L, 1L))
> x[,0L]
Tensor("StridedSlice:0", shape=(1,), dtype=int16)
```

**Comment by jjallaire** [comment]
@goldingn Is this something we can support?

**Comment by goldingn** [comment]
Thanks @dfalbel!

This wasn't too hard to fix, I've opened a PR for it now.

**Comment by dfalbel** [comment]
@goldingn  Thank you!!
