### ISSUE TITLE
Type Error with tf$contrib$layers$bucketized_column

### ISSUE THREAD

**Issue by peterwsetter** [rstudio/tensorflow#14]
I'm working on an R version of the [Tensorflow Linear Model tutorial.](https://www.tensorflow.org/versions/r0.11/tutorials/wide/index.html)

I can create the age column, but when I attempt to bucket it, I receive the following error:

`
age <- tf$contrib$layers$real_valued_column("age")

age_buckets <- tf$contrib$layers$bucketized_column(age, boundaries = c(18, 25, 30, 35, 40, 45, 50, 55, 60, 65))
`

Error in eval(substitute(expr), envir, enclos) : 
  TypeError: source_column must be an instance of _RealValuedColumn. source_column: {'default_value': None, 'dtype': tf.float32, 'dimension': 1, 'column_name': 'age'}

**Comment by jjallaire** [comment]
We were converting named tuples to named lists, which was over-aggressive as it loses type information (named tuples are always a custom python class). Fixed here: https://github.com/rstudio/tensorflow/commit/c686951a2f0a239b9fc7616fa11bb0cb358294ba

**Comment by terrytangyuan** [comment]
@peterwsetter Thanks for already testing TF.Learn out! Could you share the result once you get it working?

**Comment by peterwsetter** [comment]
@terrytangyuan Absolutely. Right now, I'm trying to figure out how to access tf.contrib.learn.LinearClassifier.fit and .evaluate . . .

**Comment by jjallaire** [comment]
Great news that you are working on a TF.Learn tutorial! Let me know if
there's anything I can do to help and of course please give us a PR if you
can!
