### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by khailper** [rstudio/tensorflow#146]
I was attempting to install tensorflow folling the directions at https://tensorflow.rstudio.com/.  The TF package installed from Github without errors. But when I ran install_tensorflow(), I got this error:

Error: parse error: trailing garlbage
          [last 4 letters of username] \\Documents\\.condarc" } Using Anaconda Cloud api site h
 (right here) ------^

(formatting that last line isn't working, the arrow was pointing at Using.)
Any advice?

**Comment by jjallaire** [comment]
Can you run this from the command line:

conda info --json

And let me know what the output is?

**Comment by khailper** [comment]
C:\Users\Karl Hailperin>conda info --json
Using Anaconda Cloud api site https://api.anaconda.org
{
  "channels": [
    "https://repo.continuum.io/pkgs/free/win-64/",
    "https://repo.continuum.io/pkgs/free/noarch/",
    "https://repo.continuum.io/pkgs/pro/win-64/",
    "https://repo.continuum.io/pkgs/pro/noarch/"
  ],
  "conda_build_version": "1.20.0",
  "conda_version": "4.0.5",
  "default_prefix": "C:\\Users\\Karl Hailperin\\Anaconda2",
  "envs": [
    "C:\\Users\\Karl Hailperin\\Anaconda2\\envs\\dato-env"
  ],
  "envs_dirs": [
    "C:\\Users\\Karl Hailperin\\Anaconda2\\envs"
  ],
  "is_foreign": false,
  "pkgs_dirs": [
    "C:\\Users\\Karl Hailperin\\Anaconda2\\pkgs"
  ],
  "platform": "win-64",
  "python_version": "2.7.11.final.0",
  "rc_path": null,
  "requests_version": "2.9.1",
  "root_prefix": "C:\\Users\\Karl Hailperin\\Anaconda2",
  "root_writable": true,
  "sys_rc_path": "C:\\Users\\Karl Hailperin\\Anaconda2\\.condarc",
  "user_rc_path": "C:\\Users\\Karl Hailperin\\.condarc"
}

**Comment by khailper** [comment]
Ended up getting around the problem by switching to Python 3.5 and manually installing TF.  Ran Rstudio's  test code and got: b'Hello, TensorFlow!' (which I assume is the intended output).

**Comment by jjallaire** [comment]
Okay, that's extremely helpful output as it will allow me to reproduce and work around the problem. I will push a fix soon, it would be great if you could try again with conda once I have the fix.

**Comment by jjallaire** [comment]
Okay, I just pushed a fix. Could you try again after installing the reticulate package from GitHub:

```r
devtools::install_github("rstudio/reticulate")
```

**Comment by khailper** [comment]
I don't know if I can reproduce your fix.  As noted above I unistalled 2.7/Anaconda and replaced it with a non-Anaconda version of 3.5 (having both was causing problems I couldn't get around).  I'll try to replicate, but if I can't I apologize for putting you through that work for nothing.

**Comment by jjallaire** [comment]
Not a problem at all! It was actually a real bug that needed to be fixed.
BTW the issue only occurs with older version of Anaconda (4.0 as opposed to
the more recent 4.3).

I was able to reproduce locally so no worries if you can't verify as I have
already done so with my local repro

**Comment by khailper** [comment]
In that case, I don't think I'll be able to reproduce.  I don't have the original installer and Continuum seems to only have the current version available.

**Comment by jjallaire** [comment]
Okay, thanks again for the help with diagnosing, glad we found and fixed
this!
