### ISSUE TITLE
Tensorflow for R throws an error when loading MNIST data set

### ISSUE THREAD

**Issue by stiero** [rstudio/tensorflow#150]
My system is set up as follows - R v3.4.0, Python v3.6.1 (Anaconda custom)

I've installed Tensorflow for R on my Ubuntu machine. The introductory "Hello, Tensorflow" code snippet works fine. 

I'm now trying to run the [MNIST tutorial](https://tensorflow.rstudio.com/tutorial_mnist_beginners.html). When I get to 
`mnist <- datasets$mnist$read_data_sets("MNIST-data", one_hot = TRUE)`,    
I get the following error message - 

> Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   URLError: <urlopen error unknown url type: https>
> 
> Detailed traceback: 
>   File "/home/user/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 235, in read_data_sets
>     SOURCE_URL + TRAIN_IMAGES)
>
>   File "/home/user/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 208, in maybe_download
>     temp_file_name, _ = urlretrieve_with_retry(source_url)
>
>   File "/home/user/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 165, in wrapped_fn
>     return fn(*args, **kwargs)
>
>   File "/home/user/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 190, in urlretrieve_with_retry
>     return urllib.request.urlretrieve(url, filename)
>
>   File "/home/user/anaconda3/envs/r-tensorflow/lib/python3.6/urllib/request.py", line 248 

      

Can someone help me out here? I've tried reinstalling the Tensorflow library, reinstalling Python, setting the Python path via Rccp but to no avail.   

Is there anything I'm doing wrong or should know about?

**Comment by jjallaire** [comment]
You may not be on the network, or may have a proxy server between you and the server with the dataset. Alternatively your Python installation might have a problem SSL certificates. It could be any number of things, but it's not something we can overcome in the tensorflow package as the fundamental error/problem is network related.
