### ISSUE TITLE
install_tensorflow() documentation and test coverage should be more explicit about Python binary expectations

### ISSUE THREAD

**Issue by missaugustina** [rstudio/tensorflow#154]
I recently submitted https://github.com/rstudio/tensorflow/pull/153 when my local install of Python failed the install_tensorflow() assumptions. As this is meant to be a "convenience method", I would recommend that the documentation for using this install method be more explicit about the expectations of where it expects Python to live (ie, it only works with a system python installed in /usr/bin or /usr/local/bin). If someone is a pyenv user, I think we can assume they can follow the alternate instructions, but it needs to be more explicit.

Additionally, it was mentioned in the response that using "which" failed in certain scenarios including MacOS with homebrew. My recommendation would be to add test coverage for this scenario so that someone else coming along and submitting this patch sees very clearly the pitfalls of a similar approach. TravisCI offers the ability to test on different platforms, so if MacOS is the problem child, then you should be able to replicate the failing homebrew scenario.

Installation methods documentation:
https://tensorflow.rstudio.com/installation.html#installation_methods

**Comment by jjallaire** [comment]
Okay, thanks. Will try to amend the docs to be more clear about this.

**Comment by jjallaire** [comment]
Added to the docs here: https://github.com/rstudio/tensorflow.rstudio.com/commit/614bb62f8bf03471b08bde7521383df304bab248#diff-eb30fad68ace7157bbdc53d4e1b1daf5
