### ISSUE TITLE
processx not avaiable

### ISSUE THREAD

**Issue by Chandrak1907** [rstudio/tensorflow#155]
I am trying to install tensorflow . As I was not able to use  install_github function. I downloaded the zip file from git repo and then used 'R CMD build tensorflow' to create tar file for tensorflow. Then I used, 

> install.packages("./tensorflow_0.9.0.9002.tar.gz",repos=NULL,

 type='source')

And I get below error:

> ERROR: dependency ‘processx’ is not available for package ‘tensorflow’
> Warning in install.packages :
>   installation of package ‘./tensorflow_0.9.0.9002.tar.gz’ had non-zero exit status

**Comment by jjallaire** [comment]
If you install from .tar.gz then you need to install all dependencies
manually.

You could also try devtools::install_local on the .tar.gz

**Comment by Chandrak1907** [comment]
Where do I find processx. I did not find this package in this Rstudio organization. Can you pls let me know?

**Comment by jjallaire** [comment]
install.packages("processx")

**Comment by Chandrak1907** [comment]
What is the R version requirements for processx. I tried this.

> package ‘processx’ is not available (for R version 3.2.3)

**Comment by eddelbuettel** [comment]
It's the twisted maze of too many nested dependencies.  processx itself is fine, but something somewhere wants R 3.3 or even R 3.4.

You could upgrade.  R 3.2.* is two years old.

**Comment by jjallaire** [comment]
There are no R version requirements for it as far as I can see but as Dirk
points out perhaps one of it's dependencies has a more recent version
requirement.

The issue may be that you are running against a CRAN mirror that has a
snapshot of an older version of CRAN (e.g. Microsoft R Open uses MRAN
snapshots by default).

**Comment by Chandrak1907** [comment]
Thank you. I downloaded the binary file from cran and build it.  processx has two more dependencies - crayon and bugme.

**Comment by jjallaire** [comment]
It looks like the only recursive dependency of process X with an R version
requirement is R6 (which requires R >= 3.0). No idea what might be going on
here.
