### ISSUE TITLE
Rstudio tf$placeholder problem

### ISSUE THREAD

**Issue by netmr** [rstudio/tensorflow#156]
Hi,

When running the following two lines in Rstudio, 
`
library(tensorflow)
input1 <- tf$placeholder(tf$float32)
`
I have the following error:

`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: as_list() is not defined on an unknown TensorShape.

Detailed traceback: 
  File "C:\Programs\MINICO~1\envs\R-TENS~1\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 758, in as_list
    raise ValueError("as_list() is not defined on an unknown TensorShape.")`

There will be no error if I run the same two lines in R console, not through Rstudio. Does anyone know what went wrong here? I am using windows 7, R v3.4.0, Python v3.6.1 (via Miniconda), Rstudio v1.0.143, and tensorflow 0.9.

Also, it will be helpful to update the R tensorflow package. The latest version is v1.2.

Thanks a lot!

**Comment by jjallaire** [comment]
The R tensorflow package works with all versions of tensorflow (so it will work fine with TF v1.2).

I can reproduce the error you are seeing, I have a feeling it is related to the print/str method for tensors. Back soon with more.

**Comment by jjallaire** [comment]
Thanks for the report, fixed here: https://github.com/rstudio/tensorflow/commit/87884b7d782fe68b388fe6e063cb43d5556a8389
