### ISSUE TITLE
Can't get tensorflow (GPU) to work when running R as root or in crontab

### ISSUE THREAD

**Issue by JamesAllingham** [rstudio/tensorflow#159]
I have successfully been using Keras in R for a while. However, I have been having trouble with getting it to work with crontab (I want to run a model daily). I get this error when I try run the crontab executes. 

```
Error: Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /usr/bin/python2.7
 /usr/bin/python3.4

You can install TensorFlow using the install_tensorflow() function.
```
Occasionally I also get an error message similar to this: 
```
Error: Python module tensorflow was not found.

Detected Python configuration:
...
```
I have also noticed that the model doesn't work when the user is root, or when I run `sudo Rscript myscript.R`. The first error can be reproduced by running the following code in a root R session (`sudo R`):

```
library(tensorflow)
sess = tf$Session
```
I managed to get my script to work with the CPU version of tensorflow, so I suspect the problem is something to do with the LD_LIBRARY_PATH environment variable. 

I followed the GPU and multi-user installation guide [here](https://tensorflow.rstudio.com/installation_gpu.html) and the GPU version does work for all users (except root). As per the guide here is the relevant content of the files: 

/etc/profile:
```
export PATH=$JAVA_HOME/bin:$PATH
export CUDA_HOME=/usr/local/cuda
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64/:/usr/local/cuda/extras/CUPTI/lib64
```
/usr/lib/R/etc/Rprofile.site:
```
Sys.setenv(CUDA_HOME="/usr/local/cuda")
Sys.setenv(PATH=paste(Sys.getenv("PATH"), "/usr/local/cuda/bin", sep = ":"))
Sys.setenv(LD_LIBRARY_PATH=paste(Sys.getenv("LD_LIBRARY_PATH"),"/usr/local/cuda/lib64/:/usr/local/cuda/extras/CUPTI/lib64", sep = ":"))
```
I am thinking that the problem is with that last line and setting the LD_LIBRARY_PATH since the original guide set that in /etc/rstudio/rserver.conf, but that doesn't help if you aren't running the code from Rstudio.

**Comment by jjallaire** [comment]
I agree that this is almost certainly a result of distinct environment variables being available to the root user. For example see:

- https://askubuntu.com/questions/161924/how-do-i-set-persistent-environment-variables-for-root
- https://help.ubuntu.com/community/EnvironmentVariables#sudo_caveat

You might also consider running the cron job as another user: https://serverfault.com/questions/352835/crontab-running-as-a-specific-user

**Comment by jjallaire** [comment]
BTW have you seen the keras package: https://rstudio.github.io/keras (much more straightforward interface to Keras than using `tf$contrib$keras`)

**Comment by JamesAllingham** [comment]
@jjallaire Thanks for the quick response, I seem to have fixed the issue (at least in the case of running R as root) by following instructions [here](https://askubuntu.com/questions/807872/cannot-set-ld-library-path-in-etc-profile-d). The issue was that since Ubuntu 9.04, LD_LIBRARY_PATH cannot be set in HOME/.profile, /etc/profile, nor /etc/environment. Your second link pointed to this problem and with a little googling I was able to find the solution I linked. In case the link goes down, all I had to do was create a `/etc/ld.so.conf.d/` file and add the following lines (one for each path to be added to the LD_LIBRARY_PATH):

```
/usr/local/cuda/lib64/
/usr/local/cuda/extras/CUPTI/lib64/
```

And the finally run `sudo ldconfig` after which my code started working as expected.

And yes, I have been using your Keras package - it is amazing, please keep up the good work. It has been extremely nice to be able to stay inside the R ecosystem for doing deep learning on structured data. Being able to use `dplyr` for data manipulation while still using the Keras interface has saved me a lot of time!

**Comment by jjallaire** [comment]
Great, glad to hear on all counts!

**Comment by eddelbuettel** [comment]
@JamesAllingham  I am not sure that link is entirely correct.  `LD_LIBRARY_PATH` is AFAIK a per-user fudge.  If and when you want to set a library directory system-wide, a much easier way is to deploy `/etc/ld.so.conf.d/*conf`.

**Comment by JamesAllingham** [comment]
@eddelbuettel perhaps I am confused but is that not what is being done in the linked solution? Perhaps the wording of my previous comment was misleading, if so I will happily edit it to make it more clear.

**Comment by eddelbuettel** [comment]
@JamesAllingham You are correct. We both said the same thing. My bad for initially misreading.

**Comment by JamesAllingham** [comment]
@eddelbuettel No worries, glad to have cleared that up! 

@jjallaire I am going to close this issue now, since the fix works and we seem to have come to a consensus that it is the correct way of doing things.
