### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/tensorflow#16]
Seems like more and more tutorials are coming soon, including some functionalities from `contrib` module. For example, some people are testing `TF.Learn` out by following its [tutorials](https://www.tensorflow.org/versions/r0.11/tutorials/tflearn/index.html). See https://github.com/rstudio/tensorflow/issues/14

It would be good to setup continuous integration for the repo so some tutorials will be tested against master branch of TF since `contrib` interface will be changing quite often until it's merged into core.

**Comment by eddelbuettel** [comment]
Sure. We are all big fans of Travis CI. Do you time to set up a branch and try something?  Start small, increment from a working basis.

Greetings from across Chicago.

**Comment by terrytangyuan** [comment]
@eddelbuettel I just quickly spin Travis up for the repo in https://github.com/rstudio/tensorflow/pull/18. Don't have too much time at this moment but at least it's a head start for future contributors. 

Excited to know that you are in Chicago! Would love to meet for coffee at some point. :-)

**Comment by jjallaire** [comment]
Just made some tweaks which will hopefully get all the tests running
(including some optional tests that execute all of the examples).

I'd love to get together sometime (virtually or when next in Chicago) to
discuss your opinions about the next phase of work on R tensorflow
bindings, which could encompass providing R wrapper functions for the
higher-level TF APIs (Learn/Slim).

The approach we have to the base API is nice because it's general but I
think it's not as usable as it should be. If we can pick the right subset
of TF to wrap at a higher level I think it will be a huge win.


On Sat, Oct 1, 2016 at 11:28 PM, Yuan (Terry) Tang <notifications@github.com

**Comment by terrytangyuan** [comment]
Sure, happy to talk anytime.

**Comment by eddelbuettel** [comment]
I am wondering if I should coax my two colleagues who play(ed) more with (Python) tensorflow into a room,  maybe at the end of the day, get @terrytangyuan to come to the loop and we video chat with you in Boston.  Any chance to get you on a late late afternoon?   We here in Central time could then move on to another establishment and have cold beverages....

**Comment by jjallaire** [comment]
That would be great! Weeks of 10/10 and 10/17 are both pretty open for me.

On Sun, Oct 2, 2016 at 11:00 AM, Dirk Eddelbuettel <notifications@github.com

**Comment by terrytangyuan** [comment]
Sounds good! Week of 10/10 works for me except for Tuesday and Friday. Let's move the discussion to email so it's easier to track.

**Comment by jjallaire** [comment]
@terrytangyuan We are unable to build the tensorflow package against the version of python on the travis server (https://travis-ci.org/rstudio/tensorflow/builds/164462360). The issue appears to be that the version of python in /opt/python is not built with the -fpic flag (i.e. likely not built with `--enable-shared`. Here's the error message:

```
/usr/bin/ld: /opt/python/2.7.10/lib/python2.7/config/libpython2.7.a(abstract.o): relocation
R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared
object; recompile with -fPIC
/opt/python/2.7.10/lib/python2.7/config/libpython2.7.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [tensorflow.so] Error 1
ERROR: compilation failed for package ‘tensorflow’
* removing ‘/usr/local/lib/R/site-library/tensorflow’
Error: Command failed (1)
```

Here's some possibly relevant discussion: 

https://github.com/travis-ci/travis-ci/issues/5021
https://github.com/travis-ci/travis-ci/issues/6437

Do you know whether there is a way to avoid using the python installed in `/opt/python`? (the system python would be fine). I'll try the `before_install` workaround mentioned in one of those threads now.

**Comment by eddelbuettel** [comment]
Just glanced at the first link. Pruning the `$PATH` should help.  Weird that one needs such acrobatics...

**Comment by jjallaire** [comment]
Hooray, that did it!

**Comment by eddelbuettel** [comment]
Awesomesauce!
