### ISSUE TITLE
Can not install with install_github (), any alternative?

### ISSUE THREAD

**Issue by Tetsujinfr** [rstudio/tensorflow#160]
Hi, install_github () returns a "Installation failed: Timeout was reached", which is likely due to a firewall on the network. I do not ha e priviledge access and can not change the security settings of the network.

So, assuming I download the repo as a zip file and I unzip on my local drive, how can I tell R to install the data without using install_github () or how can I specify my local folder?

Could not find a solution to this despite searching all over  the place.

All my other dependencies seem fine (conda, nunpy all found, just missing tensorflow)

Can you help with a local install file?

Thanks
Tets

**Comment by jjallaire** [comment]
You should be able to unzip it and then just do R CMD INSTALL
<path-to-unzipped-package>

**Comment by Tetsujinfr** [comment]
I am under Windows, can I do that under R GUI? Does Not work under CMD. Not sure of the syntax.
Thanks

Tets

**Comment by jjallaire** [comment]
That's something you need to do from the command line. See docs here: https://stat.ethz.ch/R-manual/R-devel/library/utils/html/INSTALL.html

**Comment by Tetsujinfr** [comment]
I DID use the install function of devtools to try to do it. It did start to
install but then I have some "Timour was reached" again, but this time
arising from the curl package.

Any chance I can install this without having some automatic url request
being triggered? Can not access internet connection from R or pip or
similar soft here at the office. So I would like to manage it with a local
file only install.

What is this install doing that std Cram pkg do not do? Does it need to
compile stuff?

Thanks
Tets

**Comment by jjallaire** [comment]
It's just installing the most up to date version of the package. 

There is actually a CRAN release available as well: https://cran.r-project.org/web/packages/tensorflow/index.html

We'll be issuing an update to the CRAN version in the next week or so.

**Comment by Tetsujinfr** [comment]
Ok I Will try that tomorrow. I think I tried to install a tensorflow CRAN
pkg earlier today, did a "library(tensorflow)" with no pb, but when calling
sess=tf$session() it did return an error saying "tensorflow [not found]".

Not sure if that was the same version as the one you pointed out above.
Will come back tomorrow.

Thanks for your very prompt replies today.
Tets

On 24 Jul 2017 8:10 pm, "JJ Allaire" <notifications@github.com> wrote:

It's just installing the most up to date version of the package.

There is actually a CRAN release available as well:
https://cran.r-project.org/web/packages/tensorflow/index.html

We'll be issuing an update to the CRAN version in the next week or so.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rstudio/tensorflow/issues/160#issuecomment-317524731>,
or mute the thread

**Comment by jjallaire** [comment]
The tensorflow package also requires that you install tensorflow itself, which is a pip install with lots of dependencies (so you will almost certainly not get it to work while not connected to the internet). Your only hope is probably to download the source code of tensorflow and it's dependencies and then install from source. This is not necessarily a straightforward process so I can't really provide additional step by step help here.

Once you get tensorflow installed you can point the tensorflow package at it via: https://tensorflow.rstudio.com/installation.html#custom_installation

**Comment by Tetsujinfr** [comment]
If I do from source, I would have to compile it no? In which case I am dead.

Mxnet was so smooth to get working, but I thought that this R package was
similar, meaning no compile/complex setup required.

I just do not have enough permission rights here as I would have on a
personal PC. Sad I can not use at the office.

Tets

**Comment by jjallaire** [comment]
It's easy to set up, so long as you can connect to the internet.
