### ISSUE TITLE
Issue with tf$python_io$tf_record_iterator()

### ISSUE THREAD

**Issue by statist-bhfz** [rstudio/tensorflow#162]
Hi,

I don't understand how to use iterators in Tensorflow R package. I have tried to run simplest example from https://tensorflow.rstudio.com/using_tensorflow_api.html#iterators:
```
records <- iterate(tf$python_io$tf_record_iterator("test.txt"))
```
**test.txt**  contains one column with few numbers:
```
1
2
3
```
It gives me an empty list:
```
> records
list()
```

Both Tensorflow and Keras (latest versions) work fine.

**Comment by jjallaire** [comment]
I think this is because the `tf_record_iterator` expects a TFRecord file (see https://www.tensorflow.org/api_guides/python/python_io) rather than a plain text file.

**Comment by statist-bhfz** [comment]
@jjallaire thanks, so I'm going to create TFRecord file first, as described in http://www.machinelearninguru.com/deep_learning/tensorflow/basics/tfrecord/tfrecord.html
Is it possible to create iterator for plain text (txt, csv...) files? I'm looking for something like this: https://github.com/apache/incubator-mxnet/blob/master/docs/tutorials/r/CustomIteratorTutorial.md

**Comment by jjallaire** [comment]
If you just use the Python open function you get an iterator. Something like this:

```r
library(reticulate)

py <- import_builtins()

with(py$open('test.txt') %as% file, {
  iterate(file, function(line) {
    print(line)
  })
})

```

**Comment by statist-bhfz** [comment]
@jjallaire thank you!
