### ISSUE TITLE
Sample code in webpage runtime error

### ISSUE THREAD

**Issue by charleswg** [rstudio/tensorflow#163]
After installing tensorflow in R:

Running the sample code in https://tensorflow.rstudio.com/tutorial_mnist_pros.html

> keep_prob <- tf$placeholder(tf$float32)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: as_list() is not defined on an unknown TensorShape.

Detailed traceback: 
  File "C:\PROGRA~3\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 758, in as_list
    raise ValueError("as_list() is not defined on an unknown TensorShape.")

> tf$VERSION
[1] "1.2.1"

**Comment by charleswg** [comment]
Not sure if it's version related.  But this change fixes it:
keep_prob <- tf$placeholder(tf$float32,shape())

**Comment by jjallaire** [comment]
Interesting. That's still exactly how the code reads in the Python version of the tutorial: https://www.tensorflow.org/get_started/mnist/pros#dropout. I wonder if that also no longer works?

This example which includes the same tf$placholder call also seems to work: https://github.com/rstudio/tensorflow/blob/master/inst/examples/mnist/mnist_with_summaries.R#L106 (although it doesn't use the placeholder in exactly the same way)

I don't want to just change it to `shape()` without understanding that this is the correct behavior. Do you have any additional speculation based on your experimenting as to what this should be?

**Comment by charleswg** [comment]
It find the correct environment and I can confirm it runs the original code if I use the r-tensorflow\python environment directly. I just don't know why it doesn't run within R.
  
### reticulate::py_config()
python:         C:\PROGRA~3\ANACON~1/envs/r-tensorflow/python.exe
libpython:      C:/PROGRA~3/ANACON~1/envs/r-tensorflow/python36.dll
pythonhome:     C:\PROGRA~3\ANACON~1\envs\R-TENS~1
version:        3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\PROGRA~3\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.13.1
tensorflow:     C:\PROGRA~3\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow

python versions found: 
 C:\PROGRA~3\ANACON~1/envs/r-tensorflow/python.exe
 C:\PROGRA~3\ANACON~1\python.exe

=====
I installed R tensorflow in another PC and the original code works but it's using tf$VERSION 1.2.0.
