### ISSUE TITLE
tf.decode_csv requires list of lists as an argument

### ISSUE THREAD

**Issue by TroyHernandez** [rstudio/tensorflow#164]
I'm struggling to get `tf$decode_csv` to work due to the `record_defaults` argument in python requiring a list of lists.  I've attempted passing in a matrix with one column, which I believe to be the numpy version of a list of lists.  No luck.  The data dimension is `c(1024 ^ 2, 8)`.  It's unclear how to accomplish this within `tensorflow` or even `reticulate`.

Here is approximately my last best attempt to get this to work according to [this guide](https://www.tensorflow.org/programmers_guide/reading_data).

```R
filename_queue <- tf$train$string_input_producer(list.files())
reader <- tf$TextLineReader()
key.value <- reader$read(queue = filename_queue)
record_defaults <- c(tf$constant(1L, tf$int32), tf$constant(1L, tf$int32),
                     tf$constant(1L, tf$int32), tf$constant(1L, tf$int32),
                     tf$constant(1L, tf$int32))
col1to5 = tf$decode_csv(key.value$value, record_defaults=unlist(record_defaults))
```
 Any help would be greatly appreciated.

**Comment by jjallaire** [comment]
This code does it for me:

```r
library(reticulate)

record_defaults <- list(
  list(1L),
  list(1L),
  list(1L),
  list(1L),
  list(1L)
)

r_to_py(record_defaults)
```

Which prints a Python list of lists:

```python
[[1], [1], [1], [1], [1]]
```

**Comment by TroyHernandez** [comment]
That was easy enough.  Thank you.  I was reading [this](https://tensorflow.rstudio.com/using_tensorflow_api.html#api_reference) and thought that python lists were generated exclusively by R vectors.

For future reference here's some working code:
```
filename_queue <- tf$train$string_input_producer(list.files())
reader = tf$TextLineReader()
key.value = reader$read(queue = filename_queue)

record_defaults <- list(list(1L), list(1L), list(1L), list(1L),
                        list(1L), list(1L), list(1L), list(1L))
col1to5 = tf$decode_csv(key.value$value,
                        record_defaults = r_to_py(record_defaults))
features = tf$stack(col1to5)

sess <- tf$InteractiveSession()
coord = tf$train$Coordinator()
threads = tf$train$start_queue_runners(coord=coord)

# Retrieve a single instance
# Can be repeated using for and while loops
example.label <- sess$run(features)
cat(example.label, "\n")
  
coord$request_stop()
coord$join(threads)
sess$close()
```

**Comment by jjallaire** [comment]
Okay, thanks for pointing that out. Just updated the docs to be more clear!
