### ISSUE TITLE
R tensorflow object detection api

### ISSUE THREAD

**Issue by michaelhogersosis** [rstudio/tensorflow#167]
Hi there,

Thanks for the effort on getting tensorflow in R. I am not too well versed in tensorflow and python, but saw that recently the object detection api was released for tensorflow:  https://github.com/tensorflow/models/tree/master/object_detection
Is it already possible to use this via R's tensorflow implementation?

My apologies for my lack of knowledge here and thanks for the effort on this R implementation of tensorflow, 

Michael

**Comment by jjallaire** [comment]
Yes you can use all tensorflow APIs from R. The `tf` object exported by the tensorflow pakcage is essentially equivalent to this in R:

```r
tf <- import("tensorflow")
```

Which is equivalent to this in Python:

```python
import tensorflow as tf
```

Analogously, any Python library can be imported as follows:

```r
np <- import("numpy")
```

So if there are new tensorflow libraries released you can just import them as numpy is imported above.

All of that said, the installation instructions for the object detection API seem a bit involved so you may want to get someone more familiar with Python to walk you through the installation before attempting to access from R.

**Comment by keithhurley** [comment]
Michael,

Did you ever get the object detection API running in R?  I'm attempting it but am running into the predictable roadblocks.
