### ISSUE TITLE
How to uninstall tensorflow in R

### ISSUE THREAD

**Issue by kibtes** [rstudio/tensorflow#168]
I tried the basic command to remove packages but it didn't work.
`remove.packages(tensorflow)`
gave up `Error in remove.packages: object 'tensorflow' not found`.
So How can i uninstall tensorflow from Rstudio?

**Comment by eddelbuettel** [comment]
Try quotes:  `remove.packages("tensorflow")`

Or use the command-line:   `R CND REMOVE tensorflow`
