### ISSUE TITLE
Tensorflow installation for GPU version is completed successfully but "Installation not found Error"

### ISSUE THREAD

**Issue by Gupta-Vipul** [rstudio/tensorflow#175]
Hi,

I have successfully installed tensorflow for GPU version. Following are the details.
CUDA 8
CUDNN 7
Python 3.5
Windows OS

I did installation using install_tensorflow(method = "system", version = "gpu")

**Logs**:
Preparing for installation (updating pip if necessary)
Collecting pip
  Using cached pip-9.0.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 8.1.2
    Uninstalling pip-8.1.2:
      Successfully uninstalled pip-8.1.2
Successfully installed pip-9.0.1
Installing TensorFlow...
Collecting tensorflow-gpu
  Using cached tensorflow_gpu-1.3.0-cp35-cp35m-win_amd64.whl
Collecting h5py
  Using cached h5py-2.7.1-cp35-cp35m-win_amd64.whl
Collecting pyyaml
  Using cached PyYAML-3.12-cp35-cp35m-win_amd64.whl
Collecting requests
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting Pillow
  Using cached Pillow-4.2.1-cp35-cp35m-win_amd64.whl
Collecting wheel>=0.26 (from tensorflow-gpu)
  Using cached wheel-0.29.0-py2.py3-none-any.whl
Collecting tensorflow-tensorboard<0.2.0,>=0.1.0 (from tensorflow-gpu)
  Using cached tensorflow_tensorboard-0.1.5-py3-none-any.whl
Collecting six>=1.10.0 (from tensorflow-gpu)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting protobuf>=3.3.0 (from tensorflow-gpu)
  Using cached protobuf-3.4.0-py2.py3-none-any.whl
Collecting numpy>=1.11.0 (from tensorflow-gpu)
  Using cached numpy-1.13.1-cp35-none-win_amd64.whl
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting olefile (from Pillow)
Collecting bleach==1.5.0 (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow-gpu)
  Using cached bleach-1.5.0-py2.py3-none-any.whl
Collecting html5lib==0.9999999 (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow-gpu)
Collecting markdown>=2.6.8 (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow-gpu)
Collecting werkzeug>=0.11.10 (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow-gpu)
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Collecting setuptools (from protobuf>=3.3.0->tensorflow-gpu)
  Using cached setuptools-36.4.0-py2.py3-none-any.whl
Installing collected packages: wheel, six, html5lib, bleach, setuptools, protobuf, numpy, markdown, werkzeug, tensorflow-tensorboard, tensorflow-gpu, h5py, pyyaml, urllib3, chardet, certifi, idna, requests, olefile, Pillow
Successfully installed Pillow-4.2.1 bleach-1.5.0 certifi-2017.7.27.1 chardet-3.0.4 h5py-2.7.1 html5lib-0.9999999 idna-2.6 markdown-2.6.9 numpy-1.13.1 olefile-0.44 protobuf-3.4.0 pyyaml-3.12 requests-2.18.4 setuptools-36.4.0 six-1.10.0 tensorflow-gpu-1.3.0 tensorflow-tensorboard-0.1.5 urllib3-1.22 werkzeug-0.12.2 wheel-0.29.0

Installation of TensorFlow complete.

Installation of TensorFlow complete.

But when I try to run sample program, I get following error:

Error: Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\Users\vgupta\AppData\Local\Continuum\Anaconda3\python.exe

You can install TensorFlow using the install_tensorflow() function.
> b <- tf$Variable(tf$zeros(shape(1L)))
Error: Python module tensorflow was not found.

Detected Python configuration:

python:         C:\Users\vgupta\AppData\Local\CONTIN~1\ANACON~1\python.exe
libpython:      C:/Users/vgupta/AppData/Local/CONTIN~1/ANACON~1/python35.dll
pythonhome:     C:\Users\vgupta\AppData\Local\CONTIN~1\ANACON~1
version:        3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\vgupta\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\numpy
numpy_version:  1.13.1
tensorflow:     C:\Users\vgupta\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\tensorflow

I feel that I am missing some environment variable settings. Your help in this is greatly appreciated

**Comment by jjallaire** [comment]
It's almost certainly because your PATH doesn't contain the CUDA and cuDNN libraries. Also note that TensorFlow v1.3 uses cuDNN v6.0 rather than v7.0 as you indicate you are using above (this could also be the source of the problem).

**Comment by Gupta-Vipul** [comment]
You are correct. It was because of cuDNN v7... I replaced it with v6.0 and all set. Thanks for your help.

**Comment by sushant097** [comment]
Please visit this link for detail explanation on installing the TensorFlow gpu in windows 10
http://sushantprogramming.blogspot.com/2017/12/tensorflowgpu.html . 
I explained everything in there!﻿
