### ISSUE TITLE
devtools::install_github("rstudio/reticulate")

### ISSUE THREAD

**Issue by sa4465i** [rstudio/tensorflow#181]
Unable to install reticulate on mac.
Error:
Downloading GitHub repo rstudio/reticulate@master
from URL https://api.github.com/repos/rstudio/reticulate/zipball/master
Installation failed: Could not find build tools necessary to build reticulate

**Comment by jjallaire** [comment]
That means that you need to install the Command Line Tools for Mac. See https://www.google.com/search?q=xcode+command+line+tools

You could also just install the binary from CRAN with `install.packages("reticulate")` (or do `install.packages("tensorflow")` which will also get you the latest reticulate binary).

**Comment by sa4465i** [comment]
Installation of keras from github used to throw errors when i install the binaries for reticulate and tensorflow from cran. 
Now it is working fine after i install the command line tools for mac.
Thanks a lot.
