### ISSUE TITLE
Problem running `install_tensorflow()` on win10 using CRAN version

### ISSUE THREAD

**Issue by stephlocke** [rstudio/tensorflow#184]
Running `install_tensorflow()` I get

> Could not install requirement tensorflow==1.3.1 from https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.3.1-cp36-cp36m-win_amd64.whl because of error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.3.1-cp36-cp36m-win_amd64.whl

    > sessionInfo()
    R version 3.4.1 (2017-06-30)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows >= 8 x64 (build 9200)

**Comment by jjallaire** [comment]
We just updated the CRAN version to work around this issue (there is no binary for TensorFlow v1.3.1 so we substitute v1.3.0 automatically). If you re-install v1.4 of the tensorflow package from CRAN this error should go away.
