### ISSUE TITLE
expand_dim

### ISSUE THREAD

**Issue by tyokota** [rstudio/tensorflow#190]
I have a table that I'd like to include in an LSTM model. The issue that that the `dim()` is not 3D:
```
dim(X_tr)
[1] 1142    3
```

 I tried using the keras backend, but received the following error:
```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: slice indices must be integers or None or have an __index__ method
```

Is there an R-Studio/Tensorflow solution?

**Comment by jjallaire** [comment]
You need to provide a minimally reproducible example (I can't speculate about what call you are making that yields this error). If you provide the smallest possible code snippet that results in this error it should be easy to sort out.

**Comment by tyokota** [comment]
Here is the code:
```
library(data.table)
library(tensorflow)
library(keras)

use_condaenv("tensorflow")

K <- backend()

set.seed(124)
train <- 11:110 + rnorm(100, sd = 2)

time_step <- 5
X_train <- t(sapply(1:(length(train) - time_step), function(x) train[x:(x + time_step - 1)]))

y_train <- sapply((time_step + 1):(length(train)), function(x) train[x])

dim(X_train)
#[1] 95  5

X_train <- K$expand_dims(X_train, axis = 2)
```

The goal would be to complete a forecast using LSTM. TIA!

**Comment by jjallaire** [comment]
You just need to be explicit about the axis argument being an integer:

```r
X_train <- K$expand_dims(X_train, axis = 2L)
```
Since when you use `K$` you are effectively programming directly against the TensorFlow backend, the advice here is worth reviewing: https://tensorflow.rstudio.com/tensorflow/articles/using_tensorflow_api.html

**Comment by tyokota** [comment]
Ah... Thanks, @jjallaire! Good to know and thank you for the link to understanding how to use the TF API.

**Comment by tyokota** [comment]
Sorry to ask, but now I am seeing the following error:
```
Error in dim(x) <- length(x) : invalid first argument
```

I've used the following:
```
model %>% 
fit(train, test, batch_size=1, epochs=500)
```

**Comment by jjallaire** [comment]
You need to provide more context than that (obviously basic fitting is not broken or our tests which call fit ~ 100 times would fail). What are train and test? I need a complete (and minimal) example of the code that is breaking.

**Comment by tyokota** [comment]
Expanding on the previous code:

```
library(data.table)
library(tensorflow)
library(keras)

use_condaenv("tensorflow")

K <- backend()

set.seed(124)
train <- 11:110 + rnorm(100, sd = 2)

time_step <- 5
X_train <- t(sapply(1:(length(train) - time_step), function(x) train[x:(x + time_step - 1)]))

Y_train <- sapply((time_step + 1):(length(train)), function(x) train[x])

dim(X_train)
#[1] 95  5

X_train <- K$expand_dims(X_train, axis = 2)

nb_sample <- dim(X_train)[1]
nb_steps <- dim(X_train)[2]
nb_features <- dim(X_train)[3]

model <- keras_model_sequential()

inputs <- layer_input(shape=c(nb_steps, nb_features))

outputs <- inputs %>%
layer_lstm(units=4, return_sequences=TRUE) %>%
layer_dense(units=1)

model <- keras_model(inputs=inputs, outputs=outputs)

model %>% compile(
loss='mse',
optimizer='adam')

model %>% 
fit(x=list(inputs=X_train), y=list(outputs=Y_train), batch_size=1, epochs=500)
# Error in dim(x) <- length(x) : invalid first argument
```

**Comment by jjallaire** [comment]
You can't feed a tensor to `fit` (`X_train` is a tensor). You can turn it into an array with:

```r
X_train <- K$eval(X_train)
```

**Comment by tyokota** [comment]
Ah, got it. Thanks, @jjallaire and the rest of the team for bringing TF to R!

**Comment by reaperiit** [comment]
I too have similar kind of trouble. 


train_x<- t(sapply(1:(length(temp) - tsteps), function(x) temp[x:(x+tsteps-1)] ))
train_y <-t(sapply((tsteps +1):length(temp), function(x) temp[x] ))
dim(train_x) # 54 5
dim(train_y)# 1 54
k <- backend()
train_x <-k$eval(k$expand_dims(train_x, axis = 2L))
dim(train_x) # 54 5 1

features <- dim(train_x)[3]
tsteps<- 5
batch_size <- 1
epochs = 500

model <- keras_model_sequential()
model %>%
layer_lstm(units = 4, input_shape = c(tsteps, features), batch_size = batch_size,
return_sequences = TRUE, stateful = TRUE) %>%
layer_dense(units = 1)
model %>% compile(loss = 'mse', optimizer = 'rmsprop')

for (i in 1:epochs) {
model %>% fit(train_x, train_y, batch_size = batch_size,
epochs = 1, verbose = 1, shuffle = FALSE)

model %>% reset_states()
}

Error: Error in py_call_impl(callable, dots$args, dots$keywords): ValueError: Error when checking model target: expected dense_9 to have 3 dimensions, but got array with shape (1, 54)

**Comment by jjallaire** [comment]
You already posted this on the Keras repo so no need to double-post. Please provide a complete reproducible example that exhibits the error.

**Comment by reaperiit** [comment]
Ah! I fixed it, by making return_sequences = FALSE, as there is no 2nd lstm layer.
But, there is one more thing I require, how to  plot the history of the model, as is done in kerasR package?

**Comment by jjallaire** [comment]
The `fit()` method returns a `history` object which you can plot with:

```r
plot(history)
```

**Comment by amlandutta** [comment]
Hi @jjallaire ,

Would be thankful, if you can guide on how to get the forecasts? 
How to utilize 'y_train' (in code below) for testing against actual?
Once the model is built, how to utilize it to get forecasts for _N_ periods?
On trying to run 'pred_test <- model %>% predict(y_train, batch_size = 1)'  gives error
_ValueError: Error when checking : expected lstm_31_input to have 3 dimensions, but got array with shape (95, 1)_

`set.seed(7777)
trend_train <- 11:110 + rnorm(100, sd = 2)
trend_test <- 111:130 + rnorm(20, sd =2)

lstm_num_timesteps <- 5
X_train <- t(sapply(1:(length(trend_train) - lstm_num_timesteps), function(x) trend_train[x:(x +                                                                                             lstm_num_timesteps - 1)]))
y_train <- sapply((lstm_num_timesteps + 1):(length(trend_train)), function(x) trend_train[x])

library(data.table)
library(tensorflow)
library(keras)

use_condaenv("tensorflow")

K <- backend()
X_train <- K$expand_dims(X_train, axis = 2L)
X_train <- K$eval(X_train)
num_samples <- dim(X_train)[1]
num_steps <- dim(X_train)[2]
num_features <- dim(X_train)[3]
c(num_samples, num_steps, num_features)

model <- keras_model_sequential()
model %>%
  layer_lstm(units = 4, input_shape = c(num_steps, num_features), batch_size = 1,
             return_sequences = F, stateful = TRUE) %>%
  layer_dense(units = 1)
model %>% compile(loss = 'mse', optimizer = 'rmsprop')

model %>% 
  fit(X_train, y_train, batch_size=1, epochs=500)

pred_train <- model %>% predict(X_train, batch_size = 1)`

**Comment by JigyasaK** [comment]
When I faced a similar error, it was solved by changing 

> expand_dims(dim=-2)

 to 

> expand_dims(axis=-2)

.
