### ISSUE TITLE
Error: Prerequisites for installing TensorFlow not available

### ISSUE THREAD

**Issue by linliu-stats** [rstudio/tensorflow#201]
Hi,
When I tried to install tensorflow in R I ran into the following errors
```
> library(tensorflow) 
> install_tensorflow()
Error: Prerequisites for installing TensorFlow not available.  
Execute the following at a terminal to install the prerequisites:  
$ sudo /usr/local/bin/pip install --upgrade virtualenv
```

I tried the following: `reticulate::use_python('/usr/local/bin/python2.7')` but it doesn't solve the problem.
I've installed virtualenv already but still got this error.
Thanks

**Comment by jjallaire** [comment]
We had an error like this in a previous release but fixed in recently. Could you install the latest version from GitHub to see if the problem persists?

Also, what is the output of:

```
Sys.which('virtualenv')
file.exists('/usr/local/bin/virtualenv')
```

**Comment by linliu-stats** [comment]
Thanks! I did the following:
```cd /Library/Frameworks/Python.framework/Versions/2.7/bin
ln virtualenv /usr/local/bin/virtualenv```
And problem solved.

**Comment by stephenpg** [comment]
@linliu-stats me too - thanks!

**Comment by poldham** [comment]
@linliu-stats many thanks, worked for me also. @jjallaire a link on [https://tensorflow.rstudio.com/tensorflow/](https://tensorflow.rstudio.com/tensorflow/) docs could be useful for others running into this.

**Comment by cainesap** [comment]
+1 for the error message and fix;
A warning about this on the Rstudio Keras page would be great too https://keras.rstudio.com/articles/getting_started.html

**Comment by whotank** [comment]
I still have the problem. I do not understand what this:

cd /Library/Frameworks/Python.framework/Versions/2.7/bin
ln virtualenv /usr/local/bin/virtualenv

means. Can someone help me?

**Comment by KarAnalytics** [comment]
I couldn't get the problem resolved using the virtualenv in MacOS. I tried install_keras(conda = "/Users/.../Python/anaconda3/bin/conda") and it worked!
