### ISSUE TITLE
using a different conda environment

### ISSUE THREAD

**Issue by gdkrmr** [rstudio/tensorflow#205]
Is it possible to install tensorflow into a different `conda` environment than `r-tensorflow`? I am working on a cluster environment where this is necessary, until now I could get away with a single conda installation and separate environments.

**Comment by jjallaire** [comment]
Yes, you can install tensorflow into whatever environment you want to, you'll just need to do so via `pip install` or `conda install`. The tensorflow package will detect tensorflow wherever you install it, if this doesn't happen for some reason then you can use an explicit call to `use_condaenv` to direct it to the right spot.

**Comment by gdkrmr** [comment]
Thanks for the quick answer! Works!
