### ISSUE TITLE
Using tensorflow to automatically compute gradients w.r.t. spectral decomposition error

### ISSUE THREAD

**Issue by mingu6** [rstudio/tensorflow#209]
Hi,

I'm having issues with evaluating the gradients of eigenvalues/eigenvectors with respect to the underlying matrix. Tensorflow evaluates the gradients, however when compared against analytical derivations and numerical (finite difference approx.) differentiation the gradients are generally inconsistent (I understand numerical can be unstable). I'd like to understand is there's a bug in the gradients or if a different methodology was employed to the one cited below.

We are using tf.self_adjoint_eig to evaluate the spectral decomposition for the tensorflow variable input. The input to this is symmetric so this gives the correct eigenvalues and eigenvectors. 

The analytical gradients of eigenvalues and vectors can be found in the paper "On differentiating Eigenvalues and Eigenvectors" by Magnus, Theorem 1 eqn (6) + (7). For the eigenvalues, the gradients are similar, however the eigenvectors are off by quite a bit outside the diagonal entries. To start, define a matrix A as (excuse the matrix output formatting from R)

        [,1] [,2] [,3]
[1,]   -3   -2    4
[2,]   -2    1    1
[3,]    4    1    5

we can find the spectral decomposition as 

eigen() decomposition
$values
[1]  6.661666  1.769050 -5.430716

$vectors
          [,1]                    [,2]                 [,3]
[1,] 0.3769768 -0.31452619 -0.8711841
[2,] 0.0303395  0.94426587 -0.3277827
[3,] 0.9257257  0.09713517  0.3655089

We now wish to find the gradients of the third eigenvalue (-5.430716) with respect to A. 

[1] "Analytical gradient:"

           [,1]                   [,2]             [,3]
[1,]  0.7589618  0.2855591 -0.3184255
[2,]  0.2855591  0.1074415 -0.1198075
[3,] -0.3184255 -0.1198075  0.1335967

[1] "Numerical gradient:"

            [,1]                     [,2]                  [,3]
[1,]  0.75896178 -0.29699635 -0.03055155
[2,] -0.29699635  0.10744148  0.09172142
[3,] -0.03055155  0.09172142  0.13359674

[1] "Tensorflow gradient:"
[[1]]
           [,1]                  [,2]             [,3]
[1,]  0.7589618  0.0000000 0.0000000
[2,]  0.5711181  0.1074415 0.0000000
[3,] -0.6368511 -0.2396150 0.1335967

The lower triangle of the analytical gradient is exactly half of the tensorflow evaluated gradient. We have done the same thing with the gradients of the eigenvectors. Suppose we wish to take the gradient of element (2,3) in the eigenvector matrix (-0.3277827). I have taken individual elements since tensorflow aggregates gradients if the output is a vector. Results below:

[1] "Analytical gradient:"

            [,1]                      [,2]                   [,3]
[1,] -0.03511309 -0.013211284  0.014731839
[2,]  0.10795607  0.040618426 -0.045293411
[3,]  0.01312188  0.004937104 -0.005505341

[1] "Numerical gradient:"

             [,1]                       [,2]                 [,3]
[1,]  0.035113085  0.03524435  0.003625532
[2,] -0.004634473 -1.19683265  0.001431265
[3,]  0.007039400 -0.02113358 38.853658605

 "Tensorflow gradient:"

              [,1]                   [,2]                     [,3]
[1,] -0.03511309  0.00000000  0.000000000
[2,]  0.09474478  0.04061843  0.000000000
[3,]  0.02785372 -0.04035631 -0.005505341

Note that the diagonals of the tensorflow and analytical align, however the off diagonals are not quite right. The code below should reproduce the output above. Any insight into this would be appreciated.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: YES
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS High Sierra 10.13.1
- **TensorFlow installed from (source or binary)**: pip install tensor flow
- **TensorFlow version (use command below)**: v1.2.0-5-g435cdfc 1.2.1
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A 

`########### Start program ########### 

library(tensorflow)

#create upper triangular matrix
A_vec = c(-3,-2,4,-2,1,1,4,1,5)
A = matrix(A_vec, nrow = 3, ncol = 3)
e = eigen(A)
#extract eigenvalues and eigenvectors
e_val = e$values
e_vec = e$vectors

#tensorflow variables
A_tf = tf$Variable(tf$constant(A))
e_tf = tf$self_adjoint_eig(A_tf)
#extract eigenvalues and eigenvectors
e_val_tf = e_tf[[1]]
e_vec_tf = e_tf[[2]]

#initialise variables and run session
sess = tf$Session()
sess$run(tf$global_variables_initializer())

#show eigenvalues for Tensorflow and R
print("Tensorflow eigenvalues:")
sess$run(e_tf[[1]])
print("R eigenvalues:") 
e$values

############# Eigenvector element gradient #############

####from the above, index 3 in R is the same as index 1 in TF. Select this to take gradient w.r.t. A

eval_grad_tf = tf$gradients(e_val_tf[1], A_tf) #Tensorflow gradient

#numerical differentiation
eigenval <- function(X_vec){
  X = matrix(X_vec,c(3,3))
  return(eigen(X)$values[3])
}

eval_grad_num = grad(eigenval, A_vec) #gradient of the 3rd eigenvalue from R output
eval_grad_num = matrix(eval_grad_num,c(3,3))

#analytical gradient 
eigenvec3 = eigen(A)$vectors[,3]

#analytical deriv from analytical gradient of eigenvalue from Magnus (1985), "On differentiating
#Eigenvalues and Eigenvectors", Theorem 1 eqn (6)
eval_grad_analytical = outer(eigenvec3,eigenvec3)

print("Analytical gradient:")
eval_grad_analytical
print("Numerical gradient:")
eval_grad_num
print("Tensorflow gradient:")
sess$run(eval_grad_tf)

############# Eigenvector element gradient #############

#numerical differentiation

###from above, eigenvector 3 in R is the negative of eigenvector 1 in Tensorflow

evec_grad_tf = tf$gradients(e_vec_tf[2,1], A_tf) #Tensorflow gradient

#numerical differentiation
eigenvec <- function(X_vec){
  X = matrix(X_vec,c(3,3))
  return(eigen(X)$vectors[2,3])
}

evec_grad_num = grad(eigenvec, A_vec) #gradient of the 3rd eigenvalue from R output
evec_grad_num = matrix(evec_grad_num,c(3,3))

#analytical gradient 

#analytical deriv from analytical gradient of eigenvalue from Magnus (1985), "On differentiating
#Eigenvalues and Eigenvectors", Theorem 1 eqn (7)
evec_grad_analytical = kronecker(eigenvec3, ginv(e_val[3]*diag(3)-A)) #calculates derivatives for each component of eigenvector 3
evec_grad_analytical3 = matrix(evec_grad_analytical[,2],c(3,3)) #retrieves column 2 which should correspond to the gradient of eigenvector 3 element 2 w.r.t. A

print("Analytical gradient:")
evec_grad_analytical3
print("Numerical gradient:")
evec_grad_num
print("Tensorflow gradient:")
sess$run(evec_grad_tf)
`

**Comment by jjallaire** [comment]
Thanks for the detailed write up. I'm afraid that I'm not personally familiar enough with the parts of TensorFlow you are exercising to say what's happening here. The only thing I could speculate on is that perhaps there is an array alignment issue (as described here: https://rstudio.github.io/reticulate/articles/arrays.html) although since you are dealing with simple matrices rather than 3D or 4D tensors this seems unlikely. You could test this out by everywhere you are creating an R matrix, create a 2D NumPy array using the `reticulate::np_array()` function.

Hopefully someone else has some better speculation than that, as I don't actually believe that is the source of the problem.

**Comment by mingu6** [comment]
Thanks for reading. I believe array alignment isn't the issue since the gradients are fundamentally different in some places and exactly the same in others and shifting around the alignment of the gradient matrix doesn't seem to address the problem.

Do you think I should post this in the tensorflow GitHub issues section? This is more around their actual methodology/algorithm than the R wrapper. It just so happens I was using R to implement this so I posted here.

**Comment by jjallaire** [comment]
I think it does belong in the tensorflow GitHub issues section, but I would strongly suggest that you re-write it in Python before posting there as for that audience it will be much more understandable / reproducible if you do so. If you need any help with this let me know as I've done plenty of porting of Python <-> R tensorflow code in both directions!

**Comment by mingu6** [comment]
Thanks for the tip (and offer of assistance)! I've rewritten and posted a Python version of that script on the tensorflow GitHub issues section instead.

**Comment by K0stIa** [comment]
Hey @mingu6.
I have faced the same issue. Have you solved it? If so, could you share your solution?

**Comment by mingu6** [comment]
Hi K0stia,

Someone suggested that this may contribute to the issue.

https://en.wikipedia.org/wiki/Eigenvalue_perturbation

Apparently this might explain the multiple of 2 issue.
