### ISSUE TITLE
TF model training with GPU Python, using the model with R

### ISSUE THREAD

**Issue by silentstrikeFIN** [rstudio/tensorflow#210]
I'm developing TF-based predictive models with a gpu/python setup, and I would like to deploy the pretrained model to my coworkers without server/cloud implementation. Is it possible to develop a model this way, then use the pretrained model with RStudio and Tensorflow for R? Basically develop with python, then use with R.

**Comment by jjallaire** [comment]
Yes, you can absolutely do this (a SavedModel is the exact same no matter whether it's trained with R or Python). 

Here is some example code for loading a SavedModel within R (it's part of a tfserve package that is not yet released): https://github.com/rstudio/tfserve/blob/master/R/serve.R
