### ISSUE TITLE
Tab completion does not work

### ISSUE THREAD

**Issue by chuanwen** [rstudio/tensorflow#22]
After typing "tf$Var", if one types tab, it becomes "tf$", instead of "tf$Variable" as expected.

My system: Ubuntu 14.04, python 3.4.3,  tensorflow 0.10, installed Rtensorflow with Sys.setenv(TENSORFLOW_PYTHON_VERSION = 3).

**Comment by eddelbuettel** [comment]
Which version of RStudio (Preview) are you running?

**Comment by jjallaire** [comment]
I would download the most recent version of the RStudio Preview release and
things should work as you expect.

On Sat, Oct 8, 2016 at 10:04 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by chuanwen** [comment]
I did not use RStudio (Preview). I am using R 3.3.1, install TF per instruction on the github: devtools::install_github("rstudio/tensorflow")

**Comment by eddelbuettel** [comment]
The tab completion works inside of RStudio; it ties into RStudio's help mechanism.

**Comment by jjallaire** [comment]
Tab completion is a feature of whatever R environment you are using rather
than of the package. In the package we just implement the `.DollarNames`
method which will be used in different ways by various front-ends:
https://github.com/rstudio/tensorflow/blob/5a7b01656022df303b75b3ab49655d17d629ac8b/R/python.R#L100-L118
