### ISSUE TITLE
Error with conditional function tf$cond

### ISSUE THREAD

**Issue by tomiesm** [rstudio/tensorflow#220]
Hi,

I want to use the conditional tensorflow function tf$cond. However, when I use it like this:
`reconstruction_targets=tf$cond(mask_with_labels,y,y_pred,name="reconstruction_targets")`

it throws the error:
` Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: true_fn must be callable. `

In python, the correct usage is simply with the help of lambda function:

`reconstruction_targets = tf.cond(mask_with_labels, # condition
                                 lambda: y,
                                 lambda: y_pred,
                                 name="reconstruction_targets")`

I know there isn't a direct alternative for this lambda function in rstudio, but maybe there is other way?
The code is from https://github.com/ageron/handson-ml/blob/master/extra_capsnets.ipynb, which I'm trying to transfer to R language  - so far everything when smoothly except for the tf$cond function.

**Comment by jjallaire** [comment]
You could try this:

```r
reconstruction_targets=tf$cond(mask_with_labels,function() y, function() y_pred,name="reconstruction_targets")
```

If that doesn't work then please provide a complete reproducible example and I'll see if there is another workaround possible.

**Comment by tomiesm** [comment]
Worked like a charm! Many thanks for this.
