### ISSUE TITLE
MultiRNNCell cannot be used in seq2seq dynamic decoding

### ISSUE THREAD

**Issue by SchultzBen** [rstudio/tensorflow#221]
Hello,

I am trying to use a sequence-to-sequence model with your package. I am using the tf$contrib$seq2seq functions and I am getting an error when using a MultiRNNCell with a BasicDecoder and dynamic_decode. See a smaller toy example below:

```R
library("tensorflow")

N = 12
max_length = 16
input_dim = 1

data <- array( rnorm(N*max_length*input_dim), dim = c(N, max_length, input_dim) )

main_input     <- tf$placeholder( tf$float32, shape( NULL, max_length, input_dim ))
decoder_input  <- tf$placeholder( tf$float32, shape( NULL, max_length, input_dim ))
decoder_output <- tf$placeholder( tf$float32, shape( NULL, max_length, input_dim ))
source_length  <- tf$placeholder( tf$int32, shape( NULL ))

encoder_inside_cells <- lapply(
  1:2,
  function(i){
    tf$nn$rnn_cell$LSTMCell( 5 )
  }
)
encoder_cell <- tf$nn$rnn_cell$MultiRNNCell( encoder_inside_cells )

encoder_outputs <- tf$nn$dynamic_rnn(encoder_cell, main_input, dtype=tf$float32)

encoder_state <- encoder_outputs[[2]]

decoder_inside_cells <- lapply(
  1:2,
  function(i){
    tf$nn$rnn_cell$LSTMCell( 5 )
  }
)
decoder_cell <- tf$nn$rnn_cell$MultiRNNCell( decoder_inside_cells )

helper <- tf$contrib$seq2seq$ScheduledOutputTrainingHelper(
  decoder_input, 
  sequence_length = source_length,
  sampling_probability = 0.4
)

projection_layer <- tf$layers$Dense( input_dim )

decoder <- tf$contrib$seq2seq$BasicDecoder(
  decoder_cell, helper,
  encoder_state,
  output_layer = projection_layer
)

dec_outputs <- tf$contrib$seq2seq$dynamic_decode(decoder)

result  <- dec_outputs[[1]]$rnn_output
```

The above code produces the following error (specifically when executing the dynamic decoding on line 49):

`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: The two structures don't have the same sequence type. First structure has type <class 'list'>, while second structure has type <class 'tuple'>.`

It seems to me, that some type conversion from R to python is faulty. The network runs perfectly if I use just one LSTMCell instead of a MultiRNNCell. Also note, that when the same thing is implemented in python, then it runs as expected.

Thanks in advance!

**Comment by jjallaire** [comment]
If you cast the `encoder_state` to a tuple then the code runs:

```r
decoder <- tf$contrib$seq2seq$BasicDecoder(
  decoder_cell, helper,
  tuple(encoder_state),
  output_layer = projection_layer
)
```

**Comment by SchultzBen** [comment]
I see, thank you for your quick answer!
