### ISSUE TITLE
Problems faced in installing Tensorflow in RStudio

### ISSUE THREAD

**Issue by shiraz14** [rstudio/tensorflow#224]
Hi,

I recently tried installing Tensorflow for GPU in RStudio, and faced problems getting it to work. Please see the code below for details & please advise what could have gone wrong here.

Thanks.

Code:
> library(tensorflow)
> use_condaenv("r-tensorflow")
> sess <- tf$Session()
Error: Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\Users\Sz-PC\AppData\Local\conda\conda\envs\r-tensorflow\python.exe
 C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe
 C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe
 C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\python.exe

You can install TensorFlow using the install_tensorflow() function.
> reticulate::py_config()
python:         C:\Users\Sz-PC\AppData\Local\conda\conda\envs\r-tensorflow\python.exe
libpython:      C:/Users/Sz-PC/AppData/Local/conda/conda/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\Sz-PC\AppData\Local\conda\conda\envs\R-TENS~1
version:        3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\Sz-PC\AppData\Local\conda\conda\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.14.1
tensorflow:     C:\Users\Sz-PC\AppData\Local\conda\conda\envs\R-TENS~1\lib\site-packages\tensorflow

python versions found: 
 C:\Users\Sz-PC\AppData\Local\conda\conda\envs\r-tensorflow\python.exe
 C:\PROGRA~2\MICROS~2\Shared\PYTHON~1\python.exe
 C:\PROGRA~2\MICROS~2\Shared\PYTHON~1\\python.exe
 C:\PROGRA~2\MICROS~2\Shared\ANACON~1\python.exe
> reticulate::conda_list()
          name                                                                         python
1 r-tensorflow C:\\Users\\Sz-PC\\AppData\\Local\\conda\\conda\\envs\\r-tensorflow\\python.exe

**Comment by jjallaire** [comment]
Installation of TensorFlow GPU on Windows is notoriously finicky. You need to follow all of the instructions here very carefully: https://www.tensorflow.org/install/install_windows. It's especially important that you update your system PATH with the locations of CUDA and cuDNN.

**Comment by shiraz14** [comment]
Hi,

Alright, I'll try this out again soon, possibly sometime mid-next week. If there are any further issues, I'll add them to this thread.

Thanks.
