### ISSUE TITLE
Search path hardcoded in install.R causes error.

### ISSUE THREAD

**Issue by ncravino** [rstudio/tensorflow#231]
Hi, I was trying an installation and came up with a strange bug where `virtualenv` was installed but I was still getting an error as if it didn't. After looking at the code I've identified the problem: the installation does not support modules installed with the `--user` flag.

Please allow for function `python_unix_binary` in file `install.R` to search for paths other than `/usr/bin` and `/usr/local/bin` to correct this behaviour. For instance by adding `~/.local/bin` to the function, or using environment variables to get a full search path akin to that available to `which` under linux or `where` under windows.

This situation will break the installation, for instance, when the user installed `virtualenv` in `~/.local/bin` via `pip` with `--user` flag (e.g. when using a non-privileged account in a shared environment, with no write permissions to `/usr/bin` or `/usr/local/bin`).

Will produce the *Prerequisites for installing TensorFlow not available* error followed by *Please install the following Python packages before proceeding: virtualenv* (in `virtualenv` situation).

**Comment by jjallaire** [comment]
The reason we don't do a broader search is that we are specifically looking for the system version of Python (as that is the best tested with TensorFlow). e.g. we had lots of trouble on Mac OS X when allowing this to resolve to Homebrew Python. That said, it seems like locating virtualenv in the user bin location wouldn't violate that principle. I'll make that change.

**Comment by jjallaire** [comment]
Fixed via: https://github.com/rstudio/tensorflow/commit/f6031766143389a243cfb99499609286da04a605
