### ISSUE TITLE
ImportError: No module named tensorflow

### ISSUE THREAD

**Issue by axelurbiz** [rstudio/tensorflow#24]
R tensorflow installation goes fine, but attaching the package gives an error (as shown below). TensorFlow was installed using Pip and, as indicated below, tests show no issues.

> Sys.setenv(TENSORFLOW_PYTHON="/usr/local/bin/python")
> devtools::install_github("rstudio/tensorflow")
installing to /Library/Frameworks/R.framework/Versions/3.3/Resources/library/tensorflow/libs
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (tensorflow)

> library(tensorflow)
ImportError: No module named tensorflow
If you have not yet installed TensorFlow, see https://www.tensorflow.org/get_started/
  Configuration:
  python:    /usr/local/bin/python
libpython: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
numpy:     /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include

> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
  [1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
  [1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
  [1] tensorflow_0.3.0

loaded via a namespace (and not attached):
  [1] httr_1.1.0      R6_2.2.0        tools_3.3.0     withr_1.0.2     curl_2.1        Rcpp_0.12.7    
  [7] memoise_1.0.0   digest_0.6.10   devtools_1.11.1

### From command line (installation test goes fine)

$ python
...
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
>>> print(sess.run(hello))
Hello, TensorFlow!

**Comment by axelurbiz** [comment]
This was a problem unrelated to the R package. Re-installing python via brew, and re-installing pip as a result, fixed it. 

Many thanks RStudio for creating this package!

**Comment by jjallaire** [comment]
Great, glad to hear!
