### ISSUE TITLE
TensorFlow probability

### ISSUE THREAD

**Issue by Fooourche** [rstudio/tensorflow#245]
Hi, 

Great work on this package and the documentation is amazing.
Are there any plans to integrate tensorflow proability ? https://github.com/tensorflow/probability

Thanks 
Fabien

**Comment by jjallaire** [comment]
As part of `install_tensorflow()` we currently install not just the pip tensorflow package but also the keras and tensorflow-hub packages: 

https://github.com/rstudio/tensorflow/blob/master/R/install.R#L39

We could add tensorflow-probability to this, and then export a `tfp` object the same way we currently export a `tf` object.

My biggest concern here would be whether this would break when installing older versions of TF (but we could put a filter on for that).

**Comment by jjallaire** [comment]
It's also important to note that you can use tfp from R right now as follows:

```r
library(tensorflow)
install_tensorflow(extra_packages = c("keras", "tensorflow-hub", "tensorflow-probability"))

tfp <- reticulate::import("tensorflow_probability")
```

All we'd be doing in the suggestion above is doing this by default (and exporting the `tfp` object from the tensorflow package).

**Comment by kieranrcampbell** [comment]
Thanks that's really useful - didn't realize it was an option
