### ISSUE TITLE
Error: Prerequisites for installing TensorFlow not available.

### ISSUE THREAD

**Issue by mhofert** [rstudio/tensorflow#246]
I installed TensorFlow (GPU version; see below) on a remote machine, but if I do...

    library(tensorflow)
    install_tensorflow() 

... I obtain (R-3.5.0; the remote machine runs CentOS 7.4.1708):

    Error: Prerequisites for installing TensorFlow not available.
    Please install the following Python packages before proceeding: pip, virtualenv

Both 'pip' and 'virtualenv' are available, for example:

    > Sys.which("pip")
                                                                     pip 
    "/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/python-3.5.2/bin/pip" 

What's the problem? 

I found the same (?) issue here: https://github.com/rstudio/tensorflow/issues/201 But I work with the latest versions (as of today)...

Cheers,
M

More information:
- TensorFlow was installed on the remote machine as described here (official doc for the machine): https://docs.computecanada.ca/wiki/Tensorflow
- In particular, these were the steps (obviously, pip and virtualenv are thus available):
1) module load python/3.5 
2) virtualenv tensorflow 
3) source tensorflow/bin/activate 
4) pip install tensorflow-gpu

**Comment by mhofert** [comment]
Okay, I debugged the problem. The underlying tensorflow:::python_unix_binary only sees the file locations /usr/bin, /usr/local/bin and ~/.local/bin. Symbolic linking of pip and virtualenv there gets the installation going.

**Comment by jekriske-lilly** [comment]
The problem is definitely 
https://github.com/rstudio/tensorflow/blob/master/R/install.R#L540

If anything, it'd be nice if it grabbed the output of something like:
`python -c  "import sys; print(sys.exec_prefix)"`
with the python that's in the current path and tacked it on to that list.

Right now, in our environment, this issue makes both `install_keras()` and `install_tensorflow()` unusable.

**Comment by jjallaire** [comment]
One of the reasons we did this originally was to ensure that the system version of Python was used (as we originally had problems with users installing TF with e.g. homebrew Python on the Mac or Python built from source on Linux). That said, it seems like most of these issues have been worked through so we should do as you suggest.

**Comment by jekriske-lilly** [comment]
If the user has no permissions then the pip command may have to tack on `--user`

This would be handy in HPC environments when people aren't using a virtualenv.

**Comment by sebastian-burlacu** [comment]
I'm getting this same issue in an HPC environment. My issue is further compounded by the fact that I can run the first line below fine, but not the second:

`install.packages("tensorflow")`
`tensorflow::install_tensorflow()`

`> install.packages("tensorflow")`
```
also installing the dependencies ‘config’, ‘reticulate’, ‘tfruns’

trying URL 'https://cran.seoul.go.kr/src/contrib/config_0.3.tar.gz'
Content type 'application/x-gzip' length 12344 bytes (12 KB)
==================================================
downloaded 12 KB

```

etc
```

** testing if installed package keeps a record of temporary installation path
* DONE (tensorflow)

The downloaded source packages are in
	‘/tmp/Rtmp9bQwZq/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
> tensorflow::install_tensorflow()
Error: Prerequisites for installing TensorFlow not available.

Please install the following Python packages before proceeding: pip, virtualenv

> 

```

Where would I go to edit the source for this second piece? Even when I do insert the path to my own python binary file before I install tensorflow, it still fails on the second piece.

**Comment by dfalbel** [comment]
Can you try setting the `TENSORFLOW_PYTHON` environmental variable:

```
library(tensorflow)
Sys.setenv(TENSORFLOW_PYTHON="/usr/local/bin/python")
```
