### ISSUE TITLE
Following installation steps lead to an error in python.cpp

### ISSUE THREAD

**Issue by RoiViber** [rstudio/tensorflow#25]
After having python installed (version 2.7) and tensorflow installed via pip,
I run devtools::install_github("rstudio/tensorflow") and get:

> Downloading GitHub repo rstudio/tensorflow@master
from URL https://api.github.com/repos/rstudio/tensorflow/zipball/master
Installing tensorflow
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL '/tmp/Rtmpb2mK9G/devtools29c434292a2/rstudio-tensorflow-e1b488a'  \
  --library='/home/roir/R/x86_64-pc-linux-gnu-library/3.0' --install-tests 

> \* installing *source* package ‘tensorflow’ ...
Using python binary at /usr/bin/python
Using python version 2
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
configure: creating ./config.status
config.status: creating src/Makevars
config.status: creating R/config.R
** libs
g++ -I/usr/share/R/include -DNDEBUG -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -D PYTHONLIBFILE=libpython2.7.so  -I"/home/roir/R/x86_64-pc-linux-gnu-library/3.0/Rcpp/include"   -fpic  -O3 -pipe  -g  -c RcppExports.cpp -o RcppExports.o
g++ -I/usr/share/R/include -DNDEBUG -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -D PYTHONLIBFILE=libpython2.7.so  -I"/home/roir/R/x86_64-pc-linux-gnu-library/3.0/Rcpp/include"   -fpic  -O3 -pipe  -g  -c python.cpp -o python.o
python.cpp: In function ‘PyObjectXPtr py_dict(const List&, const List&)’:
python.cpp:959:13: error: ‘i’ does not name a type
   for (auto i = 0; i<keys.length(); i++) {
             ^
python.cpp:959:20: error: expected ‘;’ before ‘i’
   for (auto i = 0; i<keys.length(); i++) {
                    ^
python.cpp:959:20: error: ‘i’ was not declared in this scope
make: *** [python.o] Error 1
ERROR: compilation failed for package ‘tensorflow’
> \* removing ‘/home/roir/R/x86_64-pc-linux-gnu-library/3.0/tensorflow’
Error: Command failed (1)

**Comment by jjallaire** [comment]
It looks like we allowed some C++11 to sneak in. Fixed here: https://github.com/rstudio/tensorflow/commit/5eea29cefafb8a19f86ad2b70e7a61939984c55e
