### ISSUE TITLE
bug in `[`

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/tensorflow#253]
Since I wrote this I'll try to fix it, but it'll be a few days before I can dig into it.
 
``` r
library(tensorflow)

x <- tf$constant(1:10)

# trying to drop 1 element at the tail
x[`:-2`, style = "R"] # should have shape = (9,)
#> Tensor("strided_slice:0", shape=(7,), dtype=int32)
```

Created on 2018-06-28 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by jjallaire** [comment]
Okay, I am hoping to submit another version to CRAN in roughly 2 weeks. If you can get these changes in over the next few days it will make that release (as I want to make sure we have an adequate testing window). Otherwise we can apply them in the release after that.
