### ISSUE TITLE
Cannot train one layer network with dnn_regressor

### ISSUE THREAD

**Issue by petrpas** [rstudio/tensorflow#255]
Hi folks,
   I am new to tfestimators and I have just encountered this problem:

When I try to train this single hidden layer model

`model <- dnn_regressor(6, feature_columns = cols)`

I get this error:

> Error in py_call_impl(callable, dots$args, dots$keywords) : TypeError: 'int' object is not iterable

When I use two hidden layers:

`model <- dnn_regressor(c(6,1), feature_columns = cols)`

Everything works fine. 

I guess, there is a problem somewhere between R and Python. R makes no difference between single value and a vector of size 1 while python does.

Thanks for a fix,
Petr Pascenko

P.S.: I installed tfestimators today, latest verision of everything.

**Comment by jjallaire** [comment]
Could you provide the full script you are using here? (will make it easier for us to reproduce and fix)

**Comment by petrpas** [comment]
Well, if you think it helps...

```{r reg}

x=seq(0,1,0.001)
y=0.5+0.45*sin(4.5*pi*x)+0.05*rnorm(1000)
#plot(x,y)

d.sin=data.table(x,y)

# return an input_fn for a given subset of data
sinus_input_fn <- function(data, num_epochs = 1) {
  input_fn(data, 
           features = c("x"), 
           response = "y",
           batch_size = 32,
           num_epochs = num_epochs)
}

cols <- feature_columns( 
  column_numeric("x")
)

model <- linear_regressor(feature_columns = cols)
model <- dnn_regressor(40,feature_columns = cols, activation_fn = 'relu')

indices <- sample(1:nrow(d.sin), size = 0.80 * nrow(d.sin))
train <- d.sin[indices, ]
test  <- d.sin[-indices, ]

# train the model
model %>% train(sinus_input_fn(train, num_epochs = 100))

model %>% evaluate(sinus_input_fn(test))

obs <- d.sin
pred=predict(model, sinus_input_fn(obs))
yp=unlist(pred$predictions)

plot(x,y, pch=16)
lines(x,yp,col='red', lwd = 2)

```
PP

**Comment by skeydan** [comment]
Your script runs fine for me with the following versions (mostly installs using

```
devtools::install_github("rstudio/<pkg>")
```

)

```

> packageVersion("tensorflow")
[1] ‘1.8.0.9003’
> packageVersion("tfestimators")
[1] ‘1.5.9002’
> packageVersion("reticulate")
[1] ‘1.8.0.9003’
> tensorflow::tf_config()
TensorFlow v1.9.0-rc1 (~/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/keras)
Python v3.6 (~/anaconda3/envs/r-tensorflow/bin/python)

```
