### ISSUE TITLE
Mac OS X : impossible d'installer TensorFlow ou Kereas

### ISSUE THREAD

**Issue by guillaumeFAGOT** [rstudio/tensorflow#257]
Bonjour
J'ai l'erreur suivante dans R
`>install_tensorflow()`

> Erreur : Prerequisites for installing TensorFlow not available

J'ai lancé cette commande dans le terminal (pour obtenir les prérequis)
`$ sudo /usr/local/bin/pip install --upgrade virtualenv`
et j'ai des erreurs de ce type en réponse
[](Could not fetch URL https://pypi.python.org/simple/: connection error: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/ (Caused by <class 'httplib.CannotSendRequest'>:
Est ce que je suis bloqué par ma connection ou il y a une autre explication ?
Dans ce cas, que faire ?
Merci de votre retour.

**Comment by eddelbuettel** [comment]
English is preferred around here but your error looks like a (possibly local?) issue accessing the pypi server.  This project has no control over pypi.python.org so you may have to debug this locally.

**Comment by monogenea** [comment]
guillaumeFAGOT you might also want to change your username. Try passing proxy settings into R using .Renviron:

`nano .Renviron
http_proxy="ENTER_HTTP"
https_proxy="ENTER_HTTPS"
ftp_proxy="ENTER_FTP"`

Should essentially be your IP address with any additional info on ports.
