### ISSUE TITLE
choose Python version in install_tensorflow?

### ISSUE THREAD

**Issue by skeydan** [rstudio/tensorflow#258]
I wonder if in ```install_keras``` and ```install_tensorflow``` we should give the user an option to choose a Python version.

Alternatively, should we check that TensorFlow is available for a Python version before installing it?

My concrete case is that as of today, using conda, I get Python 3.7 but there is no TF binary available for it, so the only workarounds are a manual install or some dirty hacking ;-)

**Comment by znmeb** [comment]
Yeah, I ran into the same thing with Conda (on Arch Linux, where the default is virtualenv, which works fine). I don't think any code changes are necessary - there just needs to be a centralized documentation page on how to set things up in the `reticulate`, `tensorflow` and `keras` libraries for someone who isn't a Python programmer / virtual environment aware.

**Comment by skeydan** [comment]
#259

**Comment by skeydan** [comment]
https://github.com/rstudio/tensorflow/issues/263

**Comment by jjallaire** [comment]
I think I have a solution to this for now: we can just force Python 3.6 (rather than allowing 3.7 to be used if it's the default within the local conda toolset). Here is the commit: https://github.com/rstudio/tensorflow/commit/1093719908e959e1d5533135ae30e256236214ed

**Comment by skeydan** [comment]
wonderful, then I don't need my local tweak any more :-) Thanks!
