### ISSUE TITLE
404 Error when using install_tensorflow(version = "gpu")

### ISSUE THREAD

**Issue by elofgren** [rstudio/tensorflow#263]
As it says on the tin, both gpu and nightly-gpu are throwing 404 errors.

> > install_tensorflow(version = "gpu")
> Using r-tensorflow conda environment for TensorFlow installation
> Determining latest installable release of TensorFlow...done
> Installing TensorFlow...
> Collecting tensorflow-gpu==1.9.0 from https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.9.0-cp37-cp37m-linux_x86_64.whl
>   HTTP error 404 while getting https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.9.0-cp37-cp37m-linux_x86_64.whl
>   Could not install requirement tensorflow-gpu==1.9.0 from https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.9.0-cp37-cp37m-linux_x86_64.whl because of error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.9.0-cp37-cp37m-linux_x86_64.whl
> Could not install requirement tensorflow-gpu==1.9.0 from https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.9.0-cp37-cp37m-linux_x86_64.whl because of HTTP error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.9.0-cp37-cp37m-linux_x86_64.whl for URL https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.9.0-cp37-cp37m-linux_x86_64.whl
> You are using pip version 10.0.1, however version 18.0 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> Error: Error 1 occurred installing packages into conda environment r-tensorflow

I updated pip after this error, but that doesn't fix the error.

**Comment by elofgren** [comment]
Curiously, this now also happens with the non-GPU version (previously, I had been successful in installing this).

> > library(tensorflow)
> > install_tensorflow()
> 
> Remove all packages in environment /home/elofgren/anaconda2/envs/r-tensorflow:
> 
> 
> ## Package Plan ##
> 
>   environment location: /home/elofgren/anaconda2/envs/r-tensorflow
> 
> 
> The following packages will be REMOVED:
> 
>     ca-certificates: 2018.03.07-0           
>     certifi:         2018.4.16-py37_0       
>     libedit:         3.1.20170329-h6b74fdf_2
>     libffi:          3.2.1-hd88cf55_4       
>     libgcc-ng:       7.2.0-hdf63c60_3       
>     libstdcxx-ng:    7.2.0-hdf63c60_3       
>     ncurses:         6.1-hf484d3e_0         
>     openssl:         1.0.2o-h20670df_0      
>     pip:             10.0.1-py37_0          
>     python:          3.7.0-hc3d631a_0       
>     readline:        7.0-ha6073c6_4         
>     setuptools:      39.2.0-py37_0          
>     sqlite:          3.24.0-h84994c4_0      
>     tk:              8.6.7-hc745277_3       
>     wheel:           0.31.1-py37_0          
>     xz:              5.2.4-h14c3975_4       
>     zlib:            1.2.11-ha838bed_2      
> 
> Creating r-tensorflow conda environment for TensorFlow installation...
> Solving environment: ...working... done
> 
> ## Package Plan ##
> 
>   environment location: /home/elofgren/anaconda2/envs/r-tensorflow
> 
>   added / updated specs: 
>     - python
> 
> 
> The following NEW packages will be INSTALLED:
> 
>     ca-certificates: 2018.03.07-0           
>     certifi:         2018.4.16-py37_0       
>     libedit:         3.1.20170329-h6b74fdf_2
>     libffi:          3.2.1-hd88cf55_4       
>     libgcc-ng:       7.2.0-hdf63c60_3       
>     libstdcxx-ng:    7.2.0-hdf63c60_3       
>     ncurses:         6.1-hf484d3e_0         
>     openssl:         1.0.2o-h20670df_0      
>     pip:             10.0.1-py37_0          
>     python:          3.7.0-hc3d631a_0       
>     readline:        7.0-ha6073c6_4         
>     setuptools:      39.2.0-py37_0          
>     sqlite:          3.24.0-h84994c4_0      
>     tk:              8.6.7-hc745277_3       
>     wheel:           0.31.1-py37_0          
>     xz:              5.2.4-h14c3975_4       
>     zlib:            1.2.11-ha838bed_2      
> 
> Preparing transaction: ...working... done
> Verifying transaction: ...working... done
> Executing transaction: ...working... done
> #
> # To activate this environment, use:
> # > source activate r-tensorflow
> #
> # To deactivate an active environment, use:
> # > source deactivate
> #
> 
> Determining latest installable release of TensorFlow...done
> Installing TensorFlow...
> Collecting tensorflow==1.9.0 from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.9.0-cp37-cp37m-linux_x86_64.whl
>   HTTP error 404 while getting https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.9.0-cp37-cp37m-linux_x86_64.whl
>   Could not install requirement tensorflow==1.9.0 from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.9.0-cp37-cp37m-linux_x86_64.whl because of error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.9.0-cp37-cp37m-linux_x86_64.whl
> Could not install requirement tensorflow==1.9.0 from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.9.0-cp37-cp37m-linux_x86_64.whl because of HTTP error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.9.0-cp37-cp37m-linux_x86_64.whl for URL https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.9.0-cp37-cp37m-linux_x86_64.whl
> You are using pip version 10.0.1, however version 18.0 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> Error: Error 1 occurred installing packages into conda environment r-tensorflow

**Comment by elofgren** [comment]
It appears the issue is that the conda environment that's created uses Python 3.7, and there *is* no Python 3.7 Tensorflow package. Not fully sure how to fix that.

**Comment by skeydan** [comment]
Yes, unfortunately at the moment you would have to install manually as described in 

https://tensorflow.rstudio.com/tensorflow/articles/installation.html#custom-installation

**Comment by jjallaire** [comment]
We now create a Python 3.6 based conda environment by default, which should resolve this issue. See https://github.com/rstudio/tensorflow/commit/1093719908e959e1d5533135ae30e256236214ed
