### ISSUE TITLE
Compatibility for MacOS High Sierra and R 3.5.1

### ISSUE THREAD

**Issue by devssh** [rstudio/tensorflow#268]
The readme suggests using devtools, but unfortunately I cannot install devtools itself as it does not support R 3.5.1. And this repo itself is meant to be an alternative to install tensorflow so I am stranded without tensorflow on R. The dependencies like git2r which uses lib2git themselves are not updated for Mac Sierra or R 3.5.1. 
I wouldn't call this a bug, more of a compatibility request.

**Comment by skeydan** [comment]
Installation from CRAN (`install.packages("tensorflow")` ) does not work for you?

**Comment by devssh** [comment]
Ya, `install.packages("tensorflow")` does not work as I am using MacOS High sierra and R 3.5.1 on Rstudio on Anaconda

**Comment by skeydan** [comment]
We don't recommend using RStudio on Anaconda, please consider using standalone RStudio (possible to combine with Anaconda python).
