### ISSUE TITLE
Problem with pip when installing tensorflow

### ISSUE THREAD

**Issue by htejero** [rstudio/tensorflow#273]
Hi, I'm trying to install tensorflow in R and I get the following error after 

library(tensorflow)
install_tensorflow()

Traceback (most recent call last):
  File "/home/htejero/.virtualenvs/r-tensorflow/bin/pip", line 7, in <module>
    from pip import main
ImportError: cannot import name main
Error: Error 1 occurred installing TensorFlow

I think is a problem with the pip version in the virtualenv as I have no problem in my system

**Comment by skeydan** [comment]
Hi,
yeah there seem to be/have been ugly problems with pip 10. 
Please consider either using a working version of pip or using conda (which seems to work pretty stably overall).
