### ISSUE TITLE
ImportError: No module named tensorflow

### ISSUE THREAD

**Issue by skeydan** [rstudio/tensorflow#28]
Sorry if  I'm making a stupid mistake here (but I don't see which it could be) - I have a problem that looks similar to an already closed issue (#24)

I've created a virtualenv with my system python, which is python 2.7 (in order not to use any of my existing conda envs), and I have the following:

> Sys.setenv(TENSORFLOW_PYTHON="/home/key/tensorflow/bin/python")
> devtools::install_github("rstudio/tensorflow", force=TRUE)
Downloading GitHub repo rstudio/tensorflow@master
from URL https://api.github.com/repos/rstudio/tensorflow/zipball/master
Installing tensorflow
'/usr/lib64/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/Rtmp3Ocl57/devtools30276a92640/rstudio-tensorflow-dfe2f1a'  \
  --library='/home/key/R/x86_64-redhat-linux-gnu-library/3.3' --install-tests 

* installing *source* package ‘tensorflow’ ...
Using python binary at /home/key/tensorflow/bin/python
...
...
** building package indices
** testing if installed package can be loaded
* DONE (tensorflow)
Reloading installed tensorflow
ImportError: No module named tensorflow
If you have not yet installed TensorFlow, see https://www.tensorflow.org/get_started/
Configuration:
 python:    /home/key/tensorflow/bin/python
 libpython: libpython2.7.so
 numpy:     /home/key/tensorflow/lib/python2.7/site-packages/numpy/core/include
> 

Would be great if you could help!
Many thanks
Sigrid

**Comment by eddelbuettel** [comment]
Just guessing, but maybe the virtual env gets in the way?   

All works swimmingly for me with (system) Python 2.7.

**Comment by jjallaire** [comment]
This error typically means exactly what it says: it can't find a version of
tensorflow installed in the Python site-library associated with the Python
binary you are using. As to why this could be that it wasn't installed, it
wasn't installed correctly (i.e. failed to complete), was somehow installed
to an alternate site-library, etc. I unfortunately can't do anything other
than speculate on that front.

**Comment by skeydan** [comment]
Hi,
thanks a lot for your answer - ufortunately, I get the same with system python:

Downloading GitHub repo rstudio/tensorflow@master
from URL https://api.github.com/repos/rstudio/tensorflow/zipball/master
Installing tensorflow
'/usr/lib64/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpzvfMSK/devtools3e6ff9a1b21/rstudio-tensorflow-dfe2f1a'  \
  --library='/home/key/R/x86_64-redhat-linux-gnu-library/3.3' --install-tests 

* installing *source* package ‘tensorflow’ ...
Using python binary from PATH
checking for gcc... gcc -m64
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -m64 accepts -g... yes
checking for gcc -m64 option to accept ISO C89... none needed
configure: creating ./config.status
config.status: creating src/Makevars
config.status: creating R/config.R
** libs
g++ -m64  -I/usr/include/R -DNDEBUG -I/usr/include/python2.7 -I/usr/include/python2.7 -I/usr/lib64/python2.7/site-packages/numpy/core/include -D PYTHONLIBFILE=libpython2.7.so -I/usr/local/include -I"/home/key/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include"   -fpic  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -c RcppExports.cpp -o RcppExports.o
g++ -m64  -I/usr/include/R -DNDEBUG -I/usr/include/python2.7 -I/usr/include/python2.7 -I/usr/lib64/python2.7/site-packages/numpy/core/include -D PYTHONLIBFILE=libpython2.7.so -I/usr/local/include -I"/home/key/R/x86_64-redhat-linux-gnu-library/3.3/Rcpp/include"   -fpic  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -c python.cpp -o python.o
g++ -m64 -shared -L/usr/lib64/R/lib -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -o tensorflow.so RcppExports.o python.o -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -L/usr/lib64/R/lib -lR
installing to /home/key/R/x86_64-redhat-linux-gnu-library/3.3/tensorflow/libs
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
  converting help for package ‘tensorflow’
    finding HTML links ... done
    dict                                    html  
    import                                  html  
    parse_flags                             html  
    shape                                   html  
    tensorflow                              html  
    tf                                      html  
    with-as-operator                        html  
    with.tensorflow.builtin.object          html  
** building package indices
** testing if installed package can be loaded
* DONE (tensorflow)
> library(tensorflow)
ImportError: No module named tensorflow
If you have not yet installed TensorFlow, see https://www.tensorflow.org/get_started/
Configuration:
 python:    /usr/bin/python
 libpython: libpython2.7.so
 numpy:     /usr/lib64/python2.7/site-packages/numpy/core/include
> 
Would you have an idea what could be the cause?

Thx a lot
Sigrid

**Comment by eddelbuettel** [comment]
As JJ said, the _R_ package you are installing here _requires_ the actual _Python_ package to be present.  

In the default Python path.  If it needs configuration, env.vars etc pp you _must_ set those before calling R to install the R side of things.

**Comment by skeydan** [comment]
Hi,

thank you both very much for your help!

TensorFlow in the virtualenv runs fine:

key@key tensorflow]$ alias tf
alias tf='source ~/tensorflow/bin/activate'
[key@key ~]$ tf
(tensorflow) [key@key ~]$ ipython
WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
Python 2.7.12 (default, Sep 29 2016, 13:30:34) 
Type "copyright", "credits" or "license" for more information.

IPython 3.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import tensorflow as tf

In [2]: tf
Out[2]: <module 'tensorflow' from '/home/key/tensorflow/lib/python2.7/site-packages/tensorflow/__init__.pyc'>

I haven't tried installing into system python yet coz I'm always a bit cautious with that ;-)

But I'm not sure if this here is ok:
If you have not yet installed TensorFlow, see https://www.tensorflow.org/get_started/
Configuration:
 python:    /home/key/tensorflow/bin/python
 libpython: libpython2.7.so
 numpy:     /home/key/tensorflow/lib/python2.7/site-packages/numpy/core/include

... there is no libpython2.7.so in the virtualenv, just on system path and some anaconda envs...
(I must admit I haven't used virtualenv before, just conda, so I don't really know if there should be an own .so or not ... sorry)

**Comment by skeydan** [comment]
Sorry again for taking your time :-(
I really don't want to take more of it so now I've installed into system python and there it works fine :-)

I guess I am doing sth wrong with the virtualenv, but that's for me to find out ;-)
thx 
Sigrid

**Comment by eddelbuettel** [comment]
Yes:

>  so now I've installed into system python and there it works fine :-)

is pretty much what I was trying to get at.  AFAIK virtualenv is meant to 'shield' an installation from other parts and side-effects, and I presume it does that so well that ... R does not see it so that we cannot have our (R) tensorflow use any (Python) tensorflow tucked away in there.

**Comment by skeydan** [comment]
makes sense :-)

**Comment by jjallaire** [comment]
Okay, glad you got it working. Cheers!

**Comment by jjallaire** [comment]
I'm not sure what's going on then (the variations of python environment /
version / numpy version / site packages location / tensorflow installation
are dizzying and it's hard to remote debug any of this).

**Comment by eddelbuettel** [comment]
@jjallaire Are you aware of existing uses with `virtualenv`?

As a scratchpad, maybe open a wiki here?

**Comment by skeydan** [comment]
Thx again :-) 
Yes, I thought it was ok to use virtualenv as it's described in the TensorFlow documentation AND mentioned on https://github.com/rstudio/tensorflow (and as we should not use R tensorflow with anaconda)
So it would be interesting to know if yi did sth wrong or really it doesn't work :-)

**Comment by jjallaire** [comment]
I just tested out using a virtualenv for tensorflow (w/ system python 2.7 on OS X) and everything worked. One oddity though, in my python config I see that the copy of libpython being used is actually from homebrew python (no idea how that happened):

```
$python
[1] "/Users/jjallaire/tensorflow/bin/python"

$libpython
[1] "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib"

$numpy
[1] "/Users/jjallaire/tensorflow/lib/python2.7/site-packages/numpy/core/include"
```
