### ISSUE TITLE
FR: allow user to force pure conda tensorflow install

### ISSUE THREAD

**Issue by treysp** [rstudio/tensorflow#281]
Thanks so much for all your work on reticulate, tensorflow, and keras - truly fantastic!

I'm working on a shared computing platform running CentOS 7, and `install_tensorflow()` was failing. After some tinkering in conda I believe it is because `pip` is not functional in our platform even when it's running from within a conda environment.

I was able to successfully execute `install_tensorflow()` by using `debug()` and: 

1. Changing `packages` to "tensorflow" after [this line](https://github.com/rstudio/tensorflow/blob/14beca91750604b1a586f33bb895bbe81b9a3840/R/install.R#L328) sets it based on googleapis.com
2. Stepping into [this call to `conda_install()`](https://github.com/rstudio/tensorflow/blob/14beca91750604b1a586f33bb895bbe81b9a3840/R/install.R#L346) and setting `pip = FALSE`
3. Stepping into [this call to `conda_install()`](https://github.com/rstudio/tensorflow/blob/14beca91750604b1a586f33bb895bbe81b9a3840/R/install.R#L356) and setting `pip = FALSE`

Even though `pip` is the officially supported way to install tensorflow and keras, would it be possible to add an argument to `install_tensorflow()` that forces a pure conda install (as in the [windows short-circuit](https://github.com/rstudio/tensorflow/blob/14beca91750604b1a586f33bb895bbe81b9a3840/R/install.R#L285)) for people in situations like mine? 

It could print a note that GPU installs are not available via conda and that `pip` is the only officially supported installation method so people understand they're going rogue.

Alternatively, the documentation could inform users that they can and demonstrate how to create and configure the `r-tensorflow` conda environment in conda then run a tensorflow version of `is_keras_available()` to confirm R can successfully access and use the environment.

Thanks for considering!

EDIT: `pip` specification of `--user` as described [here](https://github.com/rstudio/tensorflow/issues/246#issuecomment-415799413) might be relevant to why it wasn't working for me, but I'm neither sysadmin nor python savvy so not sure

**Comment by jjallaire** [comment]
We are in the course of doing some work on the reticulate installation functions which will ultimately supplant the TF installation functions (we'll just delegate to reticulate). So, it would be great if you could re-post this request on the reticulate repo. Thanks!

cc @kevinushey

**Comment by kevinushey** [comment]
> I'm working on a shared computing platform running CentOS 7, and install_tensorflow() was failing. 

Can you share the error message you were seeing in this case?

**Comment by treysp** [comment]
I'll try to replicate it when I'm back in the office on Monday - do you want me to answer here or in the [new issue in the reticulate repo](https://github.com/rstudio/reticulate/issues/402#issue-388957933)?

**Comment by kevinushey** [comment]
Let's move all discussion to the new issue. (I'll close since you've forwarded everything now)
