### ISSUE TITLE
Error installing tensroflow

### ISSUE THREAD

**Issue by mgsrikanthan** [rstudio/tensorflow#29]
I have use the following commands to install tensorflow on studio 
       >>library(devtools)
       >>devtools::install_github("rstudio/tensorflow")
but I got following error messages
       Downloading GitHub repo rstudio/tensorflow@master
       from URL https://api.github.com/repos/rstudio/tensorflow/zipball/master
       Error: Could not find build tools necessary to build tensorflow
please help me to install tensorflow on Studio environment

**Comment by eddelbuettel** [comment]
Please see the ten or so existing issue tickets here, as well as existing documentation.

We have this covered in our documentation.  Please read it.

**Comment by jjallaire** [comment]
Tensorflow requires a C/C++ compiler toolchain to install. This is
automatic with Linux, on the Mac you need to install XCode and/or the OS X
command line tools. See
https://support.rstudio.com/hc/en-us/articles/200486498-Package-Development-Prerequisites

**Comment by mgsrikanthan** [comment]
Thank you very much.
I’ll try your suggestion.
Sri





Srikanthan Govindaraj
Dean of Teaching & Learning

St. Patrick's College
Duncan House
High Street
Stratford
London, E15 2JB, United Kingdom
Direct:  +44 (0)20 7432 2976
Switchboard:  +44 (0)20 7287 6664
Fax:  +44 (0)20 7287 6282
Email : sri@st-patricks.ac.uk
Web :  www.st-patricks.ac.uk





[http://stpatrickslibrary.net/userfiles/stp_banner.jpg]<http://www.st-patricks.ac.uk>


<http://www.lsbf.org.uk/>






Notice: The information contained in this email and any attachments is confidential and may be privileged. If you are not the intended recipient you should not use, disclose, distribute or copy any of the content of it or of any attachment; you are requested to notify the sender immediately of your receipt of the email and then to delete it and any attachments from your system. St. Patrick’s College endeavours to ensure that emails and any attachments generated by its staff are free from viruses or other contaminants. However, it cannot accept any responsibility for any such which are transmitted. We therefore recommend you scan all attachments. Please note that the statements and views expressed in this email and any attachments are those of the author and do not necessarily represent those of St. Patrick’s College. St. Patrick’s International College Ltd. is registered in England (company registration No. 3698965) with the registered office at Belmont House, Station Way, Crawley, West Sussex, RH10 1JA.
