### ISSUE TITLE
Evaluation error: ModuleNotFoundError: No module named 'rpytools'.

### ISSUE THREAD

**Issue by TullioM94** [rstudio/tensorflow#300]
Hi! 

I am trying to fit a NN in R using Tensorflow, the code works fine on python. Before running the code I have installed and called the following packages: 

### Loading the packages 
library(keras)
library(tensorflow)
install_tensorflow()
library(tfestimators)
library(tfdatasets)
library(reticulate)

## Importing the numpy library
np <- import("numpy")

And I activate the r-tensorflow enviroment. I have no problem in performing basic operations: 

sess = tf$Session()
hello <- tf$constant('Hello, TensorFlow!')
tullio <- tf$constant(4)
puppy <- tf$sqrt(tullio)

sess$run(hello)
sess$run(puppy)

When I try to execute a more complicate code, it seems to work for at least the first iteration and then I receive the following error: 

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  Evaluation error: ModuleNotFoundError: No module named 'rpytools'.

And I have not found anywhere a similar problem to mine. 

Thank you so much for your help 

Tullio

**Comment by skeydan** [comment]
Can you share the output of

```
library(reticulate)
sys <- import("sys")
sys$path
```

?

**Comment by TullioM94** [comment]
Hi! 

I have managed to solve it thank you!!

**Comment by skeydan** [comment]
cool!
