### ISSUE TITLE
Help Needed; "Error: Prerequisites for installing TensorFlow not available."

### ISSUE THREAD

**Issue by Matsie1100** [rstudio/tensorflow#302]
Hello all, 

The problem I am facing is when I run the following command:
library(keras)
install_keras()

I get the following error:
"
Error: Prerequisites for installing TensorFlow not available.

Execute the following at a terminal to install the prerequisites:

$ sudo /usr/bin/easy_install pip
$ sudo /usr/local/bin/pip install --upgrade virtualenv
"

My question is what are the prerequisites for installing Tensorflow? and why are they not available? Does is have to do with the kind op laptop (macOS)? Do I need to run specific code to install those prerequisites? Is there anything I could do to solve this problem? (I have seen it a douzens of times as a problem but answer does not seem to hit the right spots)

Thanks in Advance,
a fellow ML student

**Comment by harryprince** [comment]
before use keras, you need to install tensorflow.

@Matsie1100

**Comment by skeydan** [comment]
Try the `conda` method explicitly.
Download Anaconda for your OS - probably this one

https://repo.anaconda.com/archive/Anaconda3-2018.12-MacOSX-x86_64.pkg

and then in `rstudio`, type 

```
install_tensorflow(method="conda")
```

Does this work for you?
