### ISSUE TITLE
autograph and tf.function support in tensorflow 2.0

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/tensorflow#308]
Hello,

I'm guessing there have been internal discussions related to this, but from the outside it'd be nice to get some minimal sense of what your current thoughts on this are.

It seems that with tensorflow 2.0, the `tf.function` decorator is going to be the primary way users are encouraged to write tensorflow graphs. Taking a quick look at the [implementation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/core/converter.py) it would appear that they're taking the python expressions and substituting nodes in the abstract syntax tree. It's a laudable approach for sure, though I can't help but also think it's a little unfortunate that they're pouring tons of effort to re-implement features that come out of the box with R (seemingly part of a [pattern](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/util/tf_export.py)). 

However, I don't see a straighforward path to support `tf.function` for R functions, without reimplementing a R-side AST translator with it's own [limitations table](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/LIMITATIONS.md). 

Are there any plans to support AutoGraph construction for R functions in tensorflow 2.0?

**Comment by skeydan** [comment]
Hi Tomasz,

we don't have any concrete plans to provide this as it is a lot of work, but we'd be happy to work with contributors who'd be willing to take it on.

**Comment by t-kalinowski** [comment]
Thanks Sigrid,

That's what I figured was the case. I am in principle willing to help out, but I think I'll wait until 2.0 is out of alpha before I start building anything on top of it.

**Comment by skeydan** [comment]
Makes sense, and thanks already for being interested!

**Comment by t-kalinowski** [comment]
So, I got curious and tinkered with this for a minute. I still think it'll be a lot of work, but it might be less than I originally thought. Apparently. `substitute` also works for language tokens like `if` (I had only ever used it for symbols or functions in the past). There are still a million loose ends and I'm not sure how we hook into tracking graphs associated with different inputs, but here is a quick mock up of how it might work at least from the initial R ast manipulation side:

``` r
library(magrittr)
library(tensorflow)
substitute_q <- function(x, env) {
  call <- substitute(substitute(y, env), list(y = x))
  eval(call)
}

lang2tf_mapping <- alist(
  `if` = tf_if,
  `for` = tf_for,
  `while` = tf_while
)


substitute_lang_for_tf_wrappers <- function(fun) {
  functionBody(fun) <- substitute_q(functionBody(fun), lang2tf_mapping)
  fun
}


tf_function_decorate <- function(f) {
  f <- substitute_lang_for_tf_wrappers(f)
  environment(f) <- tf_translation_wrappers
  f

  }

# taking two examples from https://www.tensorflow.org/alpha/guide/autograph
# def square_if_positive(x):
#   if x > 0:
#     x = x * x
#   else:
#     x = 0
# return x
square_if_positive <- function(x) {
  if(x > 0)
    x <- x * x
  else
    x <- 0
  x
}


# def sum_even(items):
#   s = 0
#   for c in items:
#     if c % 2 > 0:
#       continue
#     s += c
#   return s
sum_even <- function(items) {
  s <- 0
  for (c in items) {
    if ((c %% 2) > 0)
      next
    s <- s + c
  }
  s
}


tf_translation_wrappers <- new.env(parent = getNamespace("tensorflow"))

evalq(envir = tf_translation_wrappers, {
  
  tf_if <- function(cond, true, false = NULL) {
    tf$cond(substitute(cond),
            function() substitute(true),
            function() substitute(false))
  }
  
  tf_while <- function(cond, body) {
    tf$while_loop(substitute(cond),
                  function() substitute(body),
                  loop_vars = 
                    lapply(all.vars(c(substitute(cond), substitute(body))),
                           function(v) eval.parent(as.name(v), 2)))
  }
  
  tf_for <- function(x, items, body) 
    NULL
  
  
})

square_if_positive %>% tf_function_decorate() %>% print
#> function (x) 
#> {
#>     tf_if(x > 0, x <- x * x, x <- 0)
#>     x
#> }
#> <environment: 0x55f3ca1ea788>
sum_even           %>% tf_function_decorate() %>% print
#> function (items) 
#> {
#>     s <- 0
#>     tf_for(c, items, {
#>         tf_if((c%%2) > 0, next)
#>         s <- s + c
#>     })
#>     s
#> }
#> <environment: 0x55f3ca1ea788>
```

<sup>Created on 2019-03-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by skeydan** [comment]
Cool! Should we be using `rlang`?

**Comment by t-kalinowski** [comment]
Maybe.... though I don't think there is an equivalent in rlang for this particular use of `substitute`... also, I'm a little hesitant because rlang because it seems to be constantly evolving (admittedly, for the better), and I'd rather wait until it's essentially stable before using it in this kind of task that involves these very esoteric language manipulation tasks.

In any case, I'm going to let this sit dormant until tf 2.0 is officially out and maybe revisit then.

**Comment by skeydan** [comment]
That totally makes sense!!

**Comment by skeydan** [comment]
I did a quick check if we could perhaps get some major features (like looping) "for free" (based on code from https://www.debugmind.com/2019/04/07/a-primer-on-tensorflow-2-0/), but unfortunately it didn't work.
I'm leaving it here just in case someone would see an easy way to make this work (as something like this would be a "quick win" saving quite some development time):

```
library(tensorflow)
matmul_many <- function(tensor) {
  accum <- tensor
  for (x in tf$range(100)) {
    accum <- tf$matmul(accum, tensor)
    accum
  }
}

matmul_many_ <- tf$`function`(reticulate::py_func(matmul_many))

tf$autograph$to_code(matmul_many_)
```

Error:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AutoGraphError: Unexpected error transforming <tensorflow.python.eager.def_function.Function object at 0x7f75b7401f60>. If you believe this is due to a bug, please set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output when filing the bug report. Caused by: 'Function' object has no attribute '__code__'

```

@dfalbel

**Comment by t-kalinowski** [comment]
Thanks, for sharing, that a good link, I enjoyed the read.

I think there would need to be an R wrapper for each of the operators (e.g, something that takes an R expression and uses it to call [this `for_stmt` function](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/operators/control_flow.py) )

**Comment by dfalbel** [comment]
I have experimented a little with the a possible implementation of tf.function for R here: https://github.com/dfalbel/tensorflow/blob/autograph/R/autograph.R

It seems that it's working for most cases in the `if` statement.

**Comment by skeydan** [comment]
That's great!
However, I'm still stuck with a step before this. I would like to be able to wrap simple function calls, without any logic, like the things we discussed on slack.

For me, your example

```
library(tensorflow)
#tf$enable_v2_behavior()

add <- tf$`function`(function(x) {
  x <- x + 1
})

add(tf$constant(3))
```

still crashes with the v1 nightly as well as the v2 one...

**Comment by dfalbel** [comment]
`__true_fn__` and `__false_fn__` are added to the function environment in this [line](https://github.com/dfalbel/tensorflow/blob/autograph/R/autograph.R#L53). 

They are the body of `if` and `else` as a function and just need to be there when the translated expression: https://github.com/dfalbel/tensorflow/blob/autograph/R/autograph.R#L69 is evaluated.

We wouldn't need `__res__` if we just used the returned value of the `if` expression, but we need to be able to use any variable created inside the if statement for example:

```
fun <- function(x) {
  
  if (tf$reduce_sum(x) > 5) {
    a <- 1
    b <- 2
  } else {
    a <- 2
    b <- 3
  }
  
  a/b  
}
```

`__res__` is there so we can know when the function returns directly (even if it created local variables inside).

```
fun <- function(x) {
  
  if (tf$reduce_sum(x) > 5) {
    a <- 1
    x + 1
  } else {
    a <- 2
    x + 2
  }
}
```

**Comment by dfalbel** [comment]
`__true_fn__` and `__false_fn__` are temporary functions that contains the body of the `if` expression. They are  [injected into the function](https://github.com/dfalbel/tensorflow/blob/7e6f6eb86d130800108d21b12ecdfcb84365bf2a/R/autograph.R#L53) environment. They just need to be there when the [translated expression](https://github.com/dfalbel/tensorflow/blob/7e6f6eb86d130800108d21b12ecdfcb84365bf2a/R/autograph.R#L61) is evaluated. 

Since the `tf.cond` works like a functional, we can't access the variables created inside it. In order to let us reuse the variables created inside `if` statements we return the entire environment of `__true_fn__` or `__false_fn__`. But we also need a way to know what's the return value of the `if` expression so cases like this also works:

```
fun <- function(x) {
  if (tf$reduce_sum(x) > 5) {
    a <- 1
    x + 1
  } else {
    a <- 2
    x + 2
  }
}
```

**Comment by t-kalinowski** [comment]
Ahh I see, thank you.  FYI, not surprising but this doesn't work for me on tf 1.13 even with the `tf$enable_v2_behavior()`. I can't easily test against tf 2.0 at the moment, but will try later.

**Comment by t-kalinowski** [comment]
I just tried to play with autographed functions from R ran into some roadblocks. 

The object returned by the python decorator `@tf.function` behavies like a function in that it has a `__call__` method, but is actually a custom class `Function` with some involved mechanics going on behind the scenes. 

The first road block is that reticulate doesn't seem to call the `Function` correctly. The same issue presents whether it's a function marked for R conversion or not (`r_to_py`'ed), or whether it's called using `reticulate::py_call` or called directly `fun()` or `fun.__call__()`. 

My best guess about the cause of the errors is that it’s because
`@tf.function` does code inspection by reading the contents of
`__file__`, and in contexts where there is no `__file__` (e.g.,
`reticulate::source_python()` `py_eval()` `py_run_string()`, anything at
the repl prompt, etc.), then `@tf.function` fails. Importing the module
to R instead of sourcing it gives the expected
behavior. 

Here is a short example:


R Notebook
================

This is with tensorflow built from master branch (with nightly flag)
earlier this week

``` r
knitr::opts_chunk$set(error = TRUE)
Sys.setenv(CUDA_VISIBLE_DEVICES="")
Sys.setenv(AUTOGRAPH_VERBOSITY=10)
library(reticulate)
library(tensorflow)

tf$enable_v2_behavior()
tf$version$VERSION
```

    ## [1] "1.13.1"

``` r
tf$version$GIT_VERSION
```

    ## [1] "v1.12.1-3079-gdbb0de2739"

``` r
py_config()
```

    ## python:         /usr/local/bin/python3
    ## libpython:      /usr/local/lib/libpython3.7m.so
    ## pythonhome:     /usr/local:/usr/local
    ## version:        3.7.0 (default, Jun  1 2019, 15:07:43)  [GCC 7.4.0]
    ## numpy:          /home/tomasz/.local/lib/python3.7/site-packages/numpy
    ## numpy_version:  1.16.4
    ## tensorflow:     /home/tomasz/.local/lib/python3.7/site-packages/tensorflow
    ## 
    ## NOTE: Python version was forced by RETICULATE_PYTHON

``` python
import tensorflow as tf

@tf.function
def square_if_positive(x):
  if x > 0:
    x = x * x
  else:
    x = 0
  return x
```

``` r
autographed_fun <- py$square_if_positive
autographed_fun <- r_to_py(autographed_fun)

x <- tf$constant(2L)
x <-  r_to_py(x)
```

``` r
autographed_fun
```

    ## <tensorflow.python.eager.def_function.Function>

``` r
autographed_fun(x)
```

    ## Error in autographed_fun(x): could not find function "autographed_fun"

``` r
py_call(autographed_fun, x)
```

    ## Error in py_call_impl(x, dots$args, dots$keywords): TypeError: in converted code:
    ## 
    ##     <string>:3 square_if_positive
    ##         
    ##     /home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:690 __bool__
    ##         raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
    ## 
    ##     TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.
    ## 
    ## 
    ## Detailed traceback: 
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 416, in __call__
    ##     self._initialize(args, kwds, add_initializers_to=initializer_map)
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 359, in _initialize
    ##     *args, **kwds))
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1360, in _get_concrete_function_internal_garbage_collected
    ##     graph_function, _, _ = self._maybe_define_function(args, kwargs)
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1648, in _maybe_define_function
    ##     graph_function = self._create_graph_function(args, kwargs)
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1541, in _create_graph_function
    ##     capture_by_value=self._capture_by_value),
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 716, in func_graph_from_py_func
    ##     func_outputs = python_func(*func_args, **func_kwargs)
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 309, in wrapped_fn
    ##     return weak_wrapped_fn().__wrapped__(*args, **kwds)
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 706, in wrapper
    ##     raise e.ag_error_metadata.to_exception(type(e))

``` r
autographed_fun$`__call__`(x)
```

    ## Error in py_call_impl(callable, dots$args, dots$keywords): TypeError: in converted code:
    ## 
    ##     <string>:3 square_if_positive
    ##         
    ##     /home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:690 __bool__
    ##         raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
    ## 
    ##     TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.
    ## 
    ## 
    ## Detailed traceback: 
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 408, in __call__
    ##     results = self._stateful_fn(*args, **kwds)
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1334, in __call__
    ##     graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1648, in _maybe_define_function
    ##     graph_function = self._create_graph_function(args, kwargs)
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1541, in _create_graph_function
    ##     capture_by_value=self._capture_by_value),
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 716, in func_graph_from_py_func
    ##     func_outputs = python_func(*func_args, **func_kwargs)
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 309, in wrapped_fn
    ##     return weak_wrapped_fn().__wrapped__(*args, **kwds)
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 706, in wrapper
    ##     raise e.ag_error_metadata.to_exception(type(e))

``` python
x = tf.constant(2)
res = square_if_positive(x)
# print(res) 
```

    ## Error in py_call_impl(callable, dots$args, dots$keywords): TypeError: in converted code:
    ## 
    ##     <string>:3 square_if_positive
    ##         
    ##     /home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:690 __bool__
    ##         raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
    ## 
    ##     TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.
    ## 
    ## 
    ## Detailed traceback: 
    ##   File "<string>", line 1, in <module>
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 408, in __call__
    ##     results = self._stateful_fn(*args, **kwds)
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1334, in __call__
    ##     graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1648, in _maybe_define_function
    ##     graph_function = self._create_graph_function(args, kwargs)
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1541, in _create_graph_function
    ##     capture_by_value=self._capture_by_value),
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 716, in func_graph_from_py_func
    ##     func_outputs = python_func(*func_args, **func_kwargs)
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 309, in wrapped_fn
    ##     return weak_wrapped_fn().__wrapped__(*args, **kwds)
    ##   File "/home/tomasz/.local/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 706, in wrapper
    ##     raise e.ag_error_metadata.to_exception(type(e))

It seems to work fine if you don’t go through R. (this chunk is in bash)

``` bash
export CUDA_VISIBLE_DEVICES=""
#tmpfile=$(mktemp)
tmpfile=/tmp/tf_func.py
cat > $tmpfile << EOM
#!/usr/local/bin/python3

import tensorflow as tf
tf.enable_v2_behavior()

@tf.function
def square_if_positive(x):
  if x > 0:
    x = x * x
  else:
    x = 0
  return x

x = tf.constant(2)
res = square_if_positive(x)
print(res)
EOM

python3 $tmpfile
```

    ## WARNING: Logging before flag parsing goes to stderr.
    ## W0602 10:45:55.189188 140555804837376 deprecation_wrapper.py:118] From /tmp/tf_func.py:4: The name tf.enable_v2_behavior is deprecated. Please use tf.compat.v1.enable_v2_behavior instead.
    ## 
    ## 2019-06-02 10:45:55.189916: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
    ## 2019-06-02 10:45:55.192481: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
    ## 2019-06-02 10:45:55.192502: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: tower
    ## 2019-06-02 10:45:55.192506: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: tower
    ## 2019-06-02 10:45:55.192528: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 418.67.0
    ## 2019-06-02 10:45:55.192541: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 418.67.0
    ## 2019-06-02 10:45:55.192545: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 418.67.0
    ## 2019-06-02 10:45:55.202760: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3696000000 Hz
    ## 2019-06-02 10:45:55.203390: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5611448a69a0 executing computations on platform Host. Devices:
    ## 2019-06-02 10:45:55.203400: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
    ## 2019-06-02 10:45:55.260284: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1483] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
    ## tf.Tensor(4, shape=(), dtype=int32)

It works when you import into R though.

``` r
tffunc <- reticulate::import_from_path("tf_func", "/tmp")$square_if_positive
tffunc
```

    ## <tensorflow.python.eager.def_function.Function>

``` r
tffunc(x)
```

    ## tf.Tensor(4, shape=(), dtype=int32)

**Comment by skeydan** [comment]
Hi Tomasz,

yes I think it needs a file, and in Python too it seems like you actually have to `import` it...

https://github.com/tensorflow/tensorflow/issues/28316

Comparing the 2 Python-only ways you list

- definition as well as usage in same (saved) file
- definition as well as usage  in same unsaved python script

I guess this means that whether Python or R, we always need to save the source, right?

**Comment by t-kalinowski** [comment]
Just to give an update, I'm still mulling away on this. I've spent a bunch of time reading through the autograph implementation on the python side, and I have some thoughts...
we should be able to do a little more elegant from the R side.

**Comment by dfalbel** [comment]
@t-kalinowski Glad to know you are working on this! Let me know if I there's something I can help you with. 

As for the `@tf.function` annotation, I think we shouldn't need this from R side. I think we could always use `tf.function` directly - and it doesn't seem to require code to be on a file.

**Comment by t-kalinowski** [comment]
I started writing, here's what I have so far: https://github.com/t-kalinowski/tfautograph

Implemented so far are `if` `while` and `for`.

I've also translated all the [tests found here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/converters/control_flow_test.py#L173) from python to R.  All tests are currently passing against tensorflow version 1.14. 

Next I'm planning to work on handling `break` `next` and early `return`'s, but it probably won't be until next weekend or maybe even the following weekend before I'll wrap that up. (only so much free time to go around)

@dfalbel, @skeydan, if you're interested in helping, some tasks I would appreciate help with:

- Implement autographing of python `assert` / R `stopifnot`. One strategy might be to mask R's `stopifnot` with a function that builds a context with `tf.control_dependencies`, evals ````context$`__enter__()```` in the parent frame and ````on.exit(context$`__exit__())````, which some care taken to make sure that we don't pollute the `parent.frame()` but that the right `context` is still found.
- autographing of `print` calls
- Documentation (R documentation for autograph, and a README).
- More tests

**Comment by dfalbel** [comment]
@t-kalinowski this is awesome! I just opened a PR with some tests. I'll take a closer look later.

**Comment by t-kalinowski** [comment]
Thanks for the PR @dfalbel. Merged. 

I just pushed up implementations for `break` and `next` in `while` loops (not `for` loops yet). Admittedly, the new features are quite sparse on tests at the moment.

I'm going to start thinking about how to translate equivalents of python `append` and `pop` to produce variably sized outputs. On the python side this is one of the places where the autograph abstraction leaks heavily, [requiring the end-user to write autograph-specific code](https://www.tensorflow.org/guide/autograph#lists). I hopeful we'll be able to avoid that on the R side. The solution I'll be working towards will be to export ``` `append<-`()``` as a normal R function that wraps `x[[length(x)+1]] <- value`, and then mask it with an autographing `ag_append<-` in autographed functions.

**Comment by t-kalinowski** [comment]
Just pushed up some more changes. `stopifnot` now autographs. 

I'm holding off on how to deal with growing objects at the moment. It looks like there was an intent to export [`tensor_list`](https://github.com/tensorflow/tensorflow/blob/f98fa7beca612279019a788d2719a3ebaaeaff85/tensorflow/python/autograph/__init__.py#L70) but looks like that didn't happen for tensorflow 1.14. 
I could theoretically still reach in directly and grab what I would need directly via
```python
from tensorflow.python.autograph.lang.special_functions import tensor_list
``` 
or maybe even
```python
from tensorflow.python.autograph.utils.tensor_list import TensorList
```
but neither of these seem like stable footholds to built atop of. The python implementation of autograph is still a moving target and this is one area where it seems breaking changes are likely. In any case, the benefits of TensorLists seem mostly about ergonomics for python idioms around `pop` and `append`. I'm not sure they'd be that useful on the R side.

I think it'll be cleanest to skip `TensorList` support for the time being, and encourage people to use `TensorArray`'s instead. To that it would be straightforward to just write simple `[<-` and `[` methods for  `ta.write` and `ta.read`, respectively.

**Comment by t-kalinowski** [comment]
@skeydan @dfalbel
I'm planning to submit [tfautograph](https://t-kalinowski.github.io/tfautograph/) to CRAN in the next week or two. It would be great if you (or anyone else interested) could "kick the tires" on it before it goes out. Let me know what (if any) issues you encounter and/or where the documentation should be improved.

**Comment by dfalbel** [comment]
Thanks @t-kalinowski ! Will take a look as soon as possible

**Comment by t-kalinowski** [comment]
🎉 [tfautograph](https://cran.r-project.org/package=tfautograph) is now on CRAN 🎉 🎈

**Comment by skeydan** [comment]
awesome!
