### ISSUE TITLE
When following the "Installing TensorFlow", I receive the following error bellow.

### ISSUE THREAD

**Issue by RitschDS** [rstudio/tensorflow#314]
I'm trying to install tensorflow per the "Installing Tensorflow" instructions.

The install from github works successfully. 

devtools::install_github("rstudio/keras")

However, when I select the library, I get the following error. Could this be a versioning issue - Running 3.5.3

> library("tensorflow")
Error in value[[3L]](cond) : 
  Package ‘tensorflow’ version 1.13.1 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘tensorflow’ is imported by ‘keras’ so cannot be unloaded

**Comment by dfalbel** [comment]
Does this error appear when you try `library(tensorflow)` on a clean session?
