### ISSUE TITLE
Memory issue?

### ISSUE THREAD

**Issue by bwlewis** [rstudio/tensorflow#32]
I see excessive memory use transferring numeric objects between R and Python. I'm trying to track this down in the source now.

```{r}
packageDescription("tensorflow")
# Version: 0.3.0
# Date: 2016-10-11
# Built: R 3.3.1; x86_64-pc-linux-gnu; 2016-11-03 18:41:44 UTC; unix
# RemoteRepo: tensorflow
# RemoteRef: master
# RemoteSha: f85748ec526c4ff4d6e400ef8a8c92abea6d27c8
```

Tiny example:
```{r}
library(tensorflow)
np <- import("numpy")
x <- runif(2e8)
object.size(x)
# 1600000200 bytes

x <- np$array(x)
rm(x)
gc()
```
Ideally this would use maybe 3.2GB RAM, or at worst I expect something like 4.8GB. But on my system this takes over 10 GB resident RAM, and consumes 4.6 GB resident RAM even after the gc() after deleting the data. The good news is that the residual RAM use does not seem to be a leak, it's maybe just a hidden cache somewhere. Still, a >2x worst-case memory overhead is a bit excessive, right? That kind of rules out sharing anything but relatively small objects.

**Comment by jjallaire** [comment]
Yeah, that's awful! I don't know where that cache is. Here's the call where
we create the FORTRAN array from the numpy array:

https://github.com/rstudio/tensorflow/blob/master/src/python.cpp#L465

I couldn't find anything about that call leaking anywhere online. A mystery
:-\

**Comment by bwlewis** [comment]
It's not really a leak, and i think the extra memory use is on the other
end going from R to Python. Will work on this...

**Comment by bwlewis** [comment]
The problem is in python, here is a repro:

```{python}
import numpy as np
x = np.ones(2e8)
x = x.tolist()
```

Monitoring memory use of the above Python program shows the same bad behavior. :(

**Comment by jjallaire** [comment]
Wow, that's surprising and a huge bummer!

**Comment by bwlewis** [comment]
See the hack-ish solution demonstrated here:  https://github.com/bwlewis/tensorflow/blob/rpy/src/python.cpp#L661

That approach converts numeric vectors (but not character vectors) to 1-d numpy ndarrays instead of Python lists (character vectors are still returned as Python lists).  I think that this is the approach I'm going to take in the "python" package fork of this. Users are free to call $tolist() if they really want a Python list. But in the tensorflow package that might not be a viable option, not sure.

Anyway, that hack makes the higher-level conversions of sparse Matrix objects (which need vectors) work vastly more efficiently in the python fork.

**Comment by jjallaire** [comment]
Okay, that seems like the right call!
