### ISSUE TITLE
CondaHTTPError when using Conda in Windows

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/tensorflow#325]
Running `tensorflow::install_tenorflow` from RStudio in new EC2 Windows instance with Anaconda triggers:

```
> tensorflow::install_tensorflow()
Creating r-tensorflow conda environment for TensorFlow installation...
Collecting package metadata: ...working... failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/r/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/r/noarch/repodata.json.bz2 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))


Error: Error 1 occurred creating conda environment r-tensorflow

Restarting R session...
```

This I fixed by running `tensorflow::install_tenorflow` using the Anaconda Prompt, then RStudio started working properly.

I think is worth investigating further since we are recommending (through a TF message) to install Anaconda for Windows users.

**Comment by skeydan** [comment]
> This I fixed by running tensorflow::install_tenorflow using the Anaconda Prompt, then RStudio started working properly.

What do you mean by Anaconda Prompt?

We keep getting similarly-looking issues which might be related to the presence of proxy settings and/or the way RStudio uses them, see e.g. 

https://stackoverflow.com/questions/46803208/install-keras-in-rstudio-fails-with-http-connection-error
https://github.com/rstudio/keras/issues/649

I wonder what the EC2 default proxy config is?

**Comment by javierluraschi** [comment]
By Anaconda Prompt I mean:

https://docs.anaconda.com/anaconda/user-guide/getting-started/#open-anaconda-prompt

Not sure exactly why that would be different, but it certainly fixed it for me. Could be an EC2 issue, who knows.

We can close this issue but figured it would be good to at least open it to help others use this workarounds if they hit this issue as well.

**Comment by skeydan** [comment]
Ah okay thanks, per that link this seems to be just an invocation of `python`  on the command line.
So then probably 

`R -e tensorflow::install_tensorflow()` 

on the command line would have worked too, right, and we can "neither confirm nor deny" that it could be related to proxy issues when calling inside RStudio ;-))

**Comment by dfalbel** [comment]
Another solution is to install openSSL on Windows. You can find a download link in this page: https://slproweb.com/products/Win32OpenSSL.html
