### ISSUE TITLE
tf$compat$v1$enable_v2_behavior()

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/tensorflow#328]
https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/python/compat/compat.py#L144-L158

Few questions about this...

1. This comment
>   This function is called in the main TensorFlow `__init__.py` file, user should not need to call it, except during complex migrations.

seems to imply we'd get this for free, but we don't, why is that?

2. What happens if user tries to call this function if they're running TF2?

2. Would it make sense to create a friendly wrapper and export it in both rstudio/tensorflow and rstudio/keras?

**Comment by dfalbel** [comment]
1) I think the comment is misleading. Maybe it's automatically called in the v2.0 branch?

2) Tried and nothing happens.

3) I don't think so. I don't think it's recommended to use this. I would use TF 2.0 directly if I want it's behavior.
