### ISSUE TITLE
install_tensorflow does not respect RETICULATE_PYTHON_ENV

### ISSUE THREAD

**Issue by cboettig** [rstudio/tensorflow#329]
`reticulate::py_install()` provides a user-configurable name for the virtualenv by setting `RETICULATE_PYTHON_ENV` (which is also respected in determining the python configuration in `py_config()`.  However, `install_tensorflow()` does not respect this environmental variable, though it does include an argument for envname (defaulting to `r-tensorflow`).  

It would be nice if tensorflow followed the same pattern as reticulate, by defaulting to an system environmental variable (e.g. `RETICULATE_PYTHON_ENV` or `TENSORFLOW_PYTHON_ENV`, like it does with `RETICULATE_PYTHON`/`TENSORFLOW_PYTHON`), and only falling back on the default fixed name.  (Is there a good reason to have different virutalenv names as the default in reticulate and tensorflow?)

This problem becomes more acute in `keras::install_keras`, where we lose both the ability to specify the envname as an argument or as an env var! https://github.com/rstudio/keras/issues/808

**Comment by dfalbel** [comment]
The main reason for using a different default `envname` for TensorFlow and for reticulate is that `install_tensorflow` will always re-create the environment while `py_install` will only install the module if the environment already exists.

We could add a `TENSORFLOW_PYTHON_ENV`, but TF would still have different behavior compared to reticulate. 

Also, you can always install tensorflow using `py_install("tensorflow")` and this is perfectly fine.
`install_tensorflow` install other commonly used libraries, but is not required.

**Comment by cboettig** [comment]
Thanks @dfalbel !  That makes sense.  I noticed that `install_tensorflow()` destroys the environment if it already exists -- but I don't really know why it does so.  This seemed like rather surprising behavior to me.  It seems reasonable to me that the user will point `install_tensorflow()` to an existing environment, and to have it removed (which in my case also removed the the python/pip/virtualenv symlinks I was pointing to and thus caused `install_tensorflow` to fail) seems undesirable... Maybe an interactive warning at least would be appropriate?  

I'm familiar with `py_install()`, yup that works as expected.  And it makes sense to me that you provide `install_tensorflow()` as a convenience function too (the docs also make it more transparent how to specify a specific version and specify the gpu flavor or not; though as I side note it seems I can't both specify a version and the gpu flavor?,  `install_tensorflow(version="gpu-13.1.1")`).  As noted above, I refer explicitly to `install_tensorflow()` instead of `py_install()` because that's also what `install_keras()` calls, and it gives no way to control the environment at all; so naturally I looked for the ability to set that as an env var, like we do in reticulate, and was just surprised it wasn't an option.

**Comment by jjallaire** [comment]
It destroys the existing environment because we found TF upgrades to be
extremely buggy and error prone (thus resulting in lots of support overhead
wherein all the tickets were resolved by just nixing the environment and
re-installing from scratch)

**Comment by cboettig** [comment]
@jjallaire Excellent point, thanks JJ!  Being able to do a clean install instead of upgrade is definitely a good case for keeping `tensorflow` virtual env isolated from the python env (though a warning still might be nice). 

I've also struggled with changing TF versions myself (even on clean installs) which is partly why I'm trying to get a decent Docker image into the Rocker stack that has this configured.  Unfortunately I've had mixed success with this; (e.g. https://github.com/rstudio/tensorflow/issues/332) and would appreciate any pointers on constructing a stable TF environment.  Things appear to work fine on our CUDA [9.0-based images](https://hub.docker.com/r/rocker/tensorflow-gpu) but as I detailed in #332 not so much luck doing the same thing but building on the (ubuntu-18:04 based) CUDA 10.1 images, where `py_config()` finds the tensorflow libs but `reticulate:::py_module_available` and thus `tf_config()` do not).

**Comment by dfalbel** [comment]
I think TensorFlow requires CUDA 10.0 and won't work with 10.1 (I had this problem recently) - https://www.tensorflow.org/install/gpu#software_requirements - also see [here](https://github.com/tensorflow/tensorflow/issues/26150#issuecomment-471079486)

The problem you are facing when running `py_config()` and then loading tensorflow happens usually because when using `py_config()`, reticulate will attach the first python environment that has `numpy` installed - or the one in the `RETICULATE_PYTHON` env var. This environment may not have `tensorflow` installed. This does not happen when you load tensorflow first. It could also be that tensorflow is installed (and is found by reticulate) but cannot be loaded and we get this message `Error: Installation of TensorFlow not found.`. See here for example: https://github.com/rstudio/keras/issues/755

I am planning to add a `recreate=TRUE` argument to `install_tensorflow` so you can install without destroying the environment.

I also just pushed a fix to `install_keras` allowing you to specify an `envname` when installing.

**Comment by cboettig** [comment]
@dfalbel sweet, thanks a ton, it was totally the 10.0 vs 10.1 thing.  I got bit by that before with 9.2 vs 9.0 but had forgotten.  I have R `tensorflow` working in 9.0 and 10.0 working now (the former using 1.12.0, the latter using 1.13.1). 

feel free to close!

**Comment by skeydan** [comment]
Just as a note, the upcoming TensorFlow 1.14 will still need CUDA 10.0 when using the official wheel (but allows for manual builds to use 10.1).

**Comment by dfalbel** [comment]
@cboettig Glad it worked!

 I'll try to figure out how to print a different message when loading fails but the package is installed.
