### ISSUE TITLE
tab completion?

### ISSUE THREAD

**Issue by bwlewis** [rstudio/tensorflow#33]
works in the command line (Linux), not from RStudio though. That is, tab completion of python objects like `np` below:
```{r}
library(tensorflow)
np <- import("numpy")
```

RStudio (Server) Version 0.99.903 

platform       x86_64-pc-linux-gnu         
svn rev        69053                       
version.string R version 3.2.2 (2015-08-14)

Any ideas?

**Comment by eddelbuettel** [comment]
Can you upgrade?  I think you may need more recent RStudio Server >= 1.0.*.   The recently announced verson 1.0.106 is probably good.  I usually take the daily previews.

**Comment by bwlewis** [comment]
Yep, 1.0.44 fixes things. Thanks!
