### ISSUE TITLE
tf_config() fails to find libs even though py_config() can, and possibly related install issues

### ISSUE THREAD

**Issue by cboettig** [rstudio/tensorflow#332]
I consistently manage to create a setup in which `py_config()` happily finds my tensorflow libraries, but `tf_config()` and `tf_version()` etc do not.  

You should be able to reproduce this behavior using this (relatively vanilla) [Dockerfile](https://github.com/rocker-org/ml/blob/f375b27bb7e7476e47a9799a4588aa9a829aaa45/nvidia/Dockerfile).  

I'd also be open to more general advice about how best to create a shared python3 virtualenv environment that plays nicely with R `reticulate`/`tensorflow`/`keras` triad.  So far I get mostly weird behavior.  For instance (also reproducible with the Dockerfile above):

- [ ] If you start a new R session and call `py_config()` before loading `library(tensorflow)`, then `library(tensorflow)` fails with the trace:

```
library(tensorflow)
Error: package or namespace load failed for 'tensorflow':
 .onLoad failed in loadNamespace() for 'tensorflow', details:
  call: py_module_import(module, convert = convert)
  error: ImportError: Traceback (most recent call last):
  File "/opt/virtualenvs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/opt/virtualenvs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/opt/virtualenvs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in
``` 

Calling `library(tensorflow)` before the first time you call `py_config()` avoids this error, but this behavior still feels like a bug.  

- [ ] `install_tensorflow()` fails because it starts off by deleting the existing `r-tensorflow`, which is where my virtualenv is setup on the Dockerfile (thus it deletes the links for virtualenv & pip and then says it cannot find them).  Note that the Dockerfile had already installed `tensorflow-gpu` through pip.  

- [ ] If I give `install_tensorflow()` another `envname` to use, it succeeds on installing, but `tf_config()` still doesn't find it, even after `use_virtualenv()`.

Sorry for all the issues, they may be related so I didn't break these out into separate issue threads, but let me know if I should.

**Comment by dfalbel** [comment]
@cboettig In the dev version we are now delegating all installation to `reticulate::py_install`. In consequence `install_tensorflow` is completely consistent with reticulate in respect of env vars, environment names and etc.

**Comment by cboettig** [comment]
@dfalbel Thanks very much for this, and for the follow up note.  This is great.
