### ISSUE TITLE
I am developing r shiny app using keras package but I find following error? Please help

### ISSUE THREAD

**Issue by aks10000** [rstudio/tensorflow#334]
1. WHEN I TRY TO INSTALL KERAS, I FIND FOLLOWING OUTPUT and ERROR in last lines---

Installing package into ‘C:/Users/arunkumar/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.6/keras_2.2.4.1.zip'
Content type 'application/zip' length 3886934 bytes (3.7 MB)
downloaded 3.7 MB

package ‘keras’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\arunkumar\AppData\Local\Temp\RtmpkFqw1l\downloaded_packages
Error in fetch(key) : 
  lazy-load database 'C:/Users/arunkumar/Documents/R/win-library/3.6/keras/help/keras.rdb' is corrupt

2. AND WHEN I CALL KERAS FROM LIBRARY, FOLLOWING ERROR OCCURS?

Error: package or namespace load failed for ‘keras’:
 .onLoad failed in loadNamespace() for 'tensorflow', details:
  call: py_module_import(module, convert = convert)
  error: ImportError: No module named tensorflow

Please Help??

**Comment by dfalbel** [comment]
You need to install the tensorflow python module after installing Keras. You can do this by calling: `install_keras` after instaling keras from CRAN.
