### ISSUE TITLE
Version 1.14 - installation error

### ISSUE THREAD

**Issue by RamiKrispin** [rstudio/tensorflow#337]
Hello,

I am trying to install tensorflow version 1.14 using:
`tensorflow::install_tensorflow(version = "1.14")` and getting the following error:
`Installing TensorFlow...
Collecting tensorflow==1.14.0 from https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.14.0-py3-none-any.whl
  ERROR: HTTP error 404 while getting https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.14.0-py3-none-any.whl
  ERROR: Could not install requirement tensorflow==1.14.0 from https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.14.0-py3-none-any.whl because of error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.14.0-py3-none-any.whl
ERROR: Could not install requirement tensorflow==1.14.0 from https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.14.0-py3-none-any.whl because of HTTP error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.14.0-py3-none-any.whl for URL https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.14.0-py3-none-any.whl
Error: Error 1 occurred installing packages into conda environment r-tensorflow`

Any suggestion why I cannot download those files?

my system info:
`Sys.info()
                                                                                           sysname 
                                                                                          "Darwin" 
                                                                                           release 
                                                                                          "18.6.0" 
                                                                                           version 
"Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64" 
                                                                                          nodename 
                                                                         "Ramis-MacBook-Pro.local" 
                                                                                           machine 
                                                                                          "x86_64" 
                                                                                 `

Thanks,
Rami

**Comment by dfalbel** [comment]
What's your tensorflow R package version? Can you try with the GitHub version?

**Comment by RamiKrispin** [comment]
Thanks @dfalbel,

The installed version I had was version 1.13 and I installed the dev version from github (1.13.9000). I received another error while running `tensorflow::install_tensorflow()`, which related to Python missing elements. Installing the following Python packages solved the issue:
`$ /usr/bin/python -m easy_install --upgrade --user pip`, and
`/usr/bin/python -m pip install --upgrade --user virtualenv`

Thanks,
Rami

**Comment by dfalbel** [comment]
Great! Glad it worked! If you want to use conda you can always run:

`tensorflow::install_tensorflow(version = "1.14", method = "conda")`
