### ISSUE TITLE
Need improvement on tensorflow installation documentation

### ISSUE THREAD

**Issue by dracodoc** [rstudio/tensorflow#344]
I met quite some problems in installing tensorflow in windows. Most problems are solved now but I'm hoping the installation guide can have some notes so that other users will have a smoother experience.

- When using anaconda, if conda is not added to system path, `install_tensorflow` will not detect conda properly. 
  For some reason, anaconda installer strongly discourage to put conda into system path. I followed that suggestion and found `install_tensorflow` cannot detect conda. 
  After some reading I tried to use `use_condaenv` to specify the conda path, but that's not enough. In the end I have to reinstall anaconda or add conda to path to make it work.
- The installation article referred to tensorflow official installation guide, which only provided method with pip. I tried that route and met problem in every step. Both tensorflow site and R tensorflow package site didn't mention you can install tensorflow with anaconda, which I found out later, and it worked much better.
- In the end this worked for me:
  - Install tensorflow in anaconda
  - Add anaconda and anaconda\Scripts to PATH
  - use `use_condaenv("tensorflow_env", required = TRUE)` to specify the environment.

I also tried virtualenv method, however the tensorflow R package cannot recognize it with `use_virtualenv`. I searched and found [this](https://rstudio.github.io/reticulate/reference/virtualenv-tools.html)

>Virtual environment functions are not supported on Windows

If this is the case, there should be some notes in the installation guide about the `use_*` methods.

**Comment by dfalbel** [comment]
I am sorry you had issues with the installation and thank you for your report. We are trying to improve it.

1) Actually, you don't need to have conda on the path if you installed it in common installation locations. Do you mind sharing where is your conda binary installed?

2) It's recommended to use `pip` to install TensorFlow, even if inside of a conda env. The conda TensorFlow package is not updated at the same frequency as the pypi package. For instance, conda is installing 1.13 and the current release is 1.14.

3) The installation article discusses the usage of `use_*` to locate the conda/virtualenv environments : https://tensorflow.rstudio.com/tensorflow/articles/installation.html#custom-installation  and also notes that it's not possible to use virtualenv on Windows.

**Comment by dracodoc** [comment]
1. I do have anaconda installed in a customized location `d:\Lib\anaconda3` which is not common place (I don't like the default approaming folder or other folder in C because C: is limited in size). I totally understand it will be difficult for R package to look for this location if it's not in path (unless look for registries which is another layer of complexity). So adding conda to path will solve the problem, just this is against anaconda installer and may need some notes in guide.
2. We are not allowed to use github version package in company so we have to use CRAN version of R tensorflow, which need the 1.13 version tensorflow. In my experience of following python/pip route, the pip itself created lots of problem in every step.  If I have to use pip, using pip with anaconda distribution is still better than python3/pip for me.
3. I looked at the installation guide again, it mentioned the virtualenv limit but it's in the section of `install_tensorflow()` method, not the `use_*` method section in the end. In some of my attempts I was installing tensorflow in command line(with anaconda it was very smooth and simple), then try to make `tensorflow` package recognize the installed package, thus I looked at the `use_*` section and the documentation of the methods, both of them didn't mention this.

I think the `use_virtualenv` method help definitely need to mention this. I only found the information in `reticulate` documents, and it's in some other functions `virtualenv_list`!

**Comment by dracodoc** [comment]
And today I found `keras` documentation said

>The only supported installation method on Windows is "conda"

**Comment by dfalbel** [comment]
@dracodoc I will incorporate this to the installation docs and I'll let you know.

**Comment by dfalbel** [comment]
I just pushed some changes to the installation docs.
