### ISSUE TITLE
Error: Installation of TensorFlow not found.

### ISSUE THREAD

**Issue by Glender** [rstudio/tensorflow#349]
After following the guide (https://tensorflow.rstudio.com/tensorflow/articles/installation.html) to install Tensorflow, the following errors appears when running:

imdb <- dataset_imdb(num_words = 10000)

Error: Installation of TensorFlow not found.
Python environments searched for 'tensorflow' package:
 C:\Users\Glender\Anaconda3\python.exe
You can install TensorFlow using the install_tensorflow() function.

I have already read similar issues about this topic, but was unable to fix the problem.
Help is deeply appreciated. :)

**Comment by dfalbel** [comment]
Could you please try installing the dev version of `reticulate`. We just pushed a fix for this.

`devtools::install_github("rstudio/reticulate")`

You may need to [install RTools](https://cran.r-project.org/bin/windows/Rtools/index.html) in order to install reticulate from source.

**Comment by Glender** [comment]
Thanks for your quick response. 
It worked!

**Comment by dfalbel** [comment]
Glad it worked!
