### ISSUE TITLE
GPU not working with TF on Rstudio 

### ISSUE THREAD

**Issue by Glender** [rstudio/tensorflow#352]
**System:**
OS: Windows 10 
PC: MSI GS65 8RF-040NL - Gaming Laptop
GPU: NVIDIA GeForce GTX 1070

**Problem:**
After installing CUDA v9 , the necessary drivers and cuDNN, I get an error when trying to verify if the GPU is working (see below: CUDA_ERROR_UNKNOWN). Can someone help me solve this problem? Help is deeply appreciated because I'm working on it all day but I'm keep getting errors all the time.  

> library(keras)
> library(reticulate)
> Sys.setenv(TENSORFLOW_PYTHON="C:/Users/Glender/Anaconda3/envs/r-tensorflow/python.exe")
> use_python("C:/Users/Glender/Anaconda3/envs/r-tensorflow/python.exe", required = T)

> reticulate::py_config()
python:         C:/Users/Glender/Anaconda3/envs/r-tensorflow/python.exe
libpython:      C:/Users/Glender/Anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\Glender\ANACON~1\envs\R-TENS~1
version:        3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\Glender\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.16.4
tensorflow:     C:\Users\Glender\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\__init__.p

NOTE: Python version was forced by use_python function
> k = backend()
> sess = k$get_session()
2019-08-12 21:53: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-08-12 21:53: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcuda.dll
2019-08-12 21:53: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2019-08-12 21:53: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: MSI
2019-08-12 21:53: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: MSI

> reticulate::py_config()
python:         C:/Users/Glender/Anaconda3/envs/r-tensorflow/python.exe
libpython:      C:/Users/Glender/Anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\Glender\ANACON~1\envs\R-TENS~1
version:        3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\Glender\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.16.4
tensorflow:     C:\Users\Glender\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\__init__.p

NOTE: Python version was forced by use_python function
> tensorflow::tf_config()
TensorFlow v1.14.0 (C:\Users\Glender\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\__init__.p)
Python v3.6 (C:/Users/Glender/Anaconda3/envs/r-tensorflow/python.exe)

**Comment by dfalbel** [comment]
@Glender TensorFlow requires CUDA v10.0
Did you try with it?

**Comment by Glender** [comment]
Thanks for your mail Daniel.

No, I didnt try that but I certainly will. I chose v9 because the rstudio
website stated that as a requirement.

Op do 15 aug. 2019 20:37 schreef Daniel Falbel <notifications@github.com>:

**Comment by dfalbel** [comment]
@Glender Sorry about that. I will update the tutorial ASAP. At this point it's best to follow the Requirements from here: https://www.tensorflow.org/install/gpu#hardware_requirements

**Comment by Glender** [comment]
@dfalbel  It is still not working with Cuda v10.0. I think I will try installing it on Linux, I hope that will smooth things up.

**Comment by dfalbel** [comment]
@Glender have your worked it out?

Are you using the dev version of Tensorflow? `remotes::install_github("rstudio/tensorflow")`?

**Comment by Glender** [comment]
I was unable to solve it, so I am now running it on Linux without any
problems so far. Anyway, thx for your help.

Op di 20 aug. 2019 21:27 schreef Daniel Falbel <notifications@github.com>:

**Comment by dfalbel** [comment]
ok! I'll close this issue. Feel free to reopen if you need any other help.
