### ISSUE TITLE
Tensorflow install fails on cluster with custom python installation

### ISSUE THREAD

**Issue by lemairecarl** [rstudio/tensorflow#354]
Hi,
I'm trying to install TensorFlow for R on a cluster where the base python installation is in a custom location. I suspect this is not fully supported by the current installation process.
Here are the steps I follow:

1. Load modules gcc 7.3.0, R 3.6.0, and python 3.6.3
2. Create virtualenv and activate it
3. Install tensorflow using our custom wheel
4. Verify that I can import and use tensorflow in python
5. Launch R
6. Install devtools and reticulate (I tried both the CRAN and GitHub versions of reticulate)
7. `library(reticulate)`
7. `use_virtualenv("/home/lemc2220/tests/tensorflow", required=TRUE)`
7. Install tensorflow using `devtools::install_github("rstudio/tensorflow")`
8. `library(tensorflow)`
9. `sess = tf$Session()`

Result:
```
Error: Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /home/lemc2220/tests/tensorflow/bin/python

You can install TensorFlow using the install_tensorflow() function.
```

When I launch `reticulate::repl_python()` and try to import tensorflow, I get this ImportError:
```
ImportError: Traceback (most recent call last):
  File "/home/lemc2220/tests/tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/lemc2220/tests/tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/lemc2220/tests/tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libiomp5.so: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```
Please note that TF imports correctly in python outside of R.

Here is the output of `reticulate::py_config()`:
```
python:         /home/lemc2220/tests/tensorflow/bin/python
libpython:      /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/libpython3.6m.so
pythonhome:     /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3:/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3
virtualenv:     /home/lemc2220/tests/tensorflow/bin/activate_this.py
version:        3.6.3 (default, Dec  4 2017, 16:33:31)  [GCC 5.4.0]
numpy:          /home/lemc2220/tests/tensorflow/lib/python3.6/site-packages/numpy
numpy_version:  1.16.3
tensorflow:     /home/lemc2220/tests/tensorflow/lib/python3.6/site-packages/tensorflow

NOTE: Python version was forced by use_python function
```
As you can see, some paths point to the base python installation, while others point to my virtualenv. I don't know the implications of this.
I tried setting LD_LIBRARY_PATH to the `/lib` subfolder of my virtualenv, but it didn't work.

Thanks for your help!

**Comment by skeydan** [comment]
Do I understand correctly that the virtualenv is created off the Python installation under `/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/`?

Can you do 

```
sudo updatedb
locate libiomp5.so
```

and report the output?

Also, could you indicate how you load TF from Python?

And what does 

```
ldd _/home/lemc2220/tests/tensorflow/lib/python3.6/site-packages/tensorflow/pywrap_tensorflow_internal.so
```
say? (assuming this is the correct path)?

**Comment by skeydan** [comment]
I'm not a linker guru either but I'd say these 2 entries "not found" are strange... 
If you want to continue investigating this I'd try to find out which lines in the (custom) build cause this (btw. neither the official PyPi wheels nor a "non-custom" custom build have an entry for `libiomp.so` ...)

Of course we can also close it as you've found a workaround :-)

**Comment by lemairecarl** [comment]
`libiomp5.so` shows up in the build scripts of TF, but specifically for MKL: https://github.com/tensorflow/tensorflow/search?q=libiomp5.so&unscoped_q=libiomp5.so

Anyhow, as this is more an issue about reticulate than the here repo, you can close.

**Comment by skeydan** [comment]
> libiomp5.so shows up in the build scripts of TF, but specifically for MKL:

oh I see, thanks!

Closing then.
