### ISSUE TITLE
R Crashes when loading tensorflow with latest 3.3.2 version

### ISSUE THREAD

**Issue by RDubos** [rstudio/tensorflow#36]
Hello,
I don't know if this has been reported yet, but i haven't seen any open issue relative to that (might be more an RStudio issue).

I was using microsoft R 3.3.1 with RStudio 1.0.44 and tensorflow was working like a charm (great job porting it to R btw!).

I switched to 3.3.2 and now, when I load tensorflow with `library(tensorflow)` (even on a clean session), the R session crashes (R Session Aborted message) and have to be restarted.

Here are my systems info:

```
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X El Capitan 10.11.6

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.2
```

Thanks for your time!

**Comment by eddelbuettel** [comment]
Try rebuilding / reinstalling all pieces below R in the toolchain.

**Comment by RDubos** [comment]
@eddelbuettel 
thanks for the quick reply
I haven't done that before, I googled that quickly without success
i tried to reinstall the tensorflow package, but it crashes the same way
do you know where i can find resources to do that?

**Comment by RDubos** [comment]
I uninstalled everything (R, RStudio, & __Packages__) and brew install everything back again, and it seems to be working again now.
Thanks for the help!

**Comment by eddelbuettel** [comment]
Thanks for reporting back, and for closing the issue.   These things can be frustrating, but there also is _a lot_ of code underneath it and that sometimes requires a little shaking of the compiler can...
