### ISSUE TITLE
changes in tensorflow pip packages

### ISSUE THREAD

**Issue by skeydan** [rstudio/tensorflow#364]
just quickly noting here:
- `tensorflow` now default has GPU support (but works without too)
- `tensorflow-cpu` available (see below)

> `tensorflow` pip package will by default include GPU support (same as `tensorflow-gpu` now) for the platforms we currently have GPU support. It will work on machines with and without Nvidia GPUs. We will continue uploading `tensorflow-gpu` packages, and also provide the CPU only packages at `tensorflow-cpu` for users who are concerned about package size.

**Comment by assulthoni** [comment]
i got same issue
