### ISSUE TITLE
Segfault when trying dataset.map() on a tfrecords dataset

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/tensorflow#365]
I'm not quite sure what's going on here. At first I thought this was a (python) tensorflow bug and I started to prepare a bug report to post there, but then after translating from R to python the issue went away. 
This is the R script, reproducible generates a segfault
```R
library(tensorflow)
print(tf$version$VERSION)

x = tf$io$serialize_tensor(tf$range(5L))
try(print(x)) # not really the issue I'm filing, but this also errors

x = x$numpy()
x = tf$train$BytesList(value = list(x))
x = tf$train$Feature(bytes_list = x)
x = tf$train$Features(feature = list('x'= x))
x = tf$train$Example(features = x)
x = x$SerializeToString()

pth = "/tmp/bugreport-r.tfrecords"

with(tf$io$TFRecordWriter(pth) %as% writer, {
  writer$write(x)
  writer$write(x)
  writer$write(x)
})

ds = tf$data$TFRecordDataset(pth)

parse_example <- function(x) {
  ex = tf$io$parse_single_example(x, list('x' = tf$io$FixedLenFeature(list(), tf$string)))
  x = tf$io$parse_tensor(ex$x, tf$int32)
  x
}

ds = ds$map(parse_example)

it <- reticulate::as_iterator(ds$take(1L))
batch <- iter_next(it)
print(batch)
```

gives me output like this:

![image](https://user-images.githubusercontent.com/8462255/66660437-32a94a80-ec13-11e9-81e1-3ac912ee3dfd.png)

meanwhile after translating to python:
```python
import tensorflow as tf

print tf.version.VERSION

x = tf.io.serialize_tensor(tf.range(5))
print x

x = x.numpy()
x = tf.train.BytesList(value = [x])
x = tf.train.Feature(bytes_list = x)
x = tf.train.Features(feature = {'x': x})
x = tf.train.Example(features = x)
x = x.SerializeToString()

pth = "/tmp/bugreport.tfrecords"

with tf.io.TFRecordWriter(pth) as writer:
  writer.write(x)
  writer.write(x)
  writer.write(x)
  
ds = tf.data.TFRecordDataset(pth)
 
def _parse_example(x):
  ex = tf.io.parse_single_example(x, {'x': tf.io.FixedLenFeature([], tf.string)})
  x = tf.io.parse_tensor(ex['x'], tf.int32)
  return x

ds = ds.map(_parse_example)

for x in ds.take(1):
  print x
```

gives the expected output:
![image](https://user-images.githubusercontent.com/8462255/66660391-21603e00-ec13-11e9-881d-63cd0ef9d116.png)

**Comment by kevinushey** [comment]
What version of reticulate are you using? We recently fixed a couple bugs around how iterators were handled in reticulate, which caused segfaults of this form. (Although it's of course possible we missed some.)

Perhaps more to the point, do you see any difference in behavior with CRAN reticulate vs. the development version of reticulate?

**Comment by t-kalinowski** [comment]
I just installed from master and the issue is solved! It must have been a very recent fix because I had just previously installed from master less than a week ago.

**Comment by t-kalinowski** [comment]
Thanks!

**Comment by t-kalinowski** [comment]
Thanks @kevinushey
