### ISSUE TITLE
Availability of tf$Session()

### ISSUE THREAD

**Issue by wlandau** [rstudio/tensorflow#366]
From https://github.com/tensorflow/tensorflow/issues/26816#issuecomment-474500687:

> It's by design that TF 2.0 does not have tf.Session.

From the `tensorflow` R package docs:

> You can confirm that the installation succeeded with:
>
> sess = tf$Session()
> hello <- tf$constant('Hello, TensorFlow!')
> sess$run(hello)

The above R code works when I try it with TensorFlow 1.13 but not 2.0. Is `tf_version()` sufficient to check that TensorFlow installed correctly?

**Comment by dfalbel** [comment]
yes! `tf_version()` is sufficient to verify that TensorFlow is correctly installed. 
We are in the process of updating all documentation for TensorFlow related packages to reflect 2.0 changes

**Comment by wlandau** [comment]
Awesome, thanks!

**Comment by cassiopagnoncelli** [comment]
@dfalbel Hi Daniel, is there any planned schedule to release new docs?

**Comment by dfalbel** [comment]
@cassiopagnoncelli documentation has been updated some time ago. You can find it here: https://tensorflow.rstudio.com/guide/tensorflow/eager_execution/
