### ISSUE TITLE
Could not locate error

### ISSUE THREAD

**Issue by henry-p** [rstudio/tensorflow#37]
I have python3 installed at _/usr/local/bin/python3_. I also installed Tensorflow using pip3.
When I enter `Sys.setenv(TENSORFLOW_PYTHON="/usr/local/bin/python3")` and then
`devtools::install_github("rstudio/tensorflow")`, I get the error

```
* installing *source* package ‘tensorflow’ ...
Using python binary at /usr/local/bin/python3
Could not locate 
ERROR: configuration failed for package ‘tensorflow’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/tensorflow’
Error: Command failed (1)
```

What did I do wrong?

System: macOS

**Comment by henry-p** [comment]
I got it to work with an (ugly) hotfix, as seen here (https://github.com/henry-p/tensorflow/commit/dabb79b406632437ea7b67b2ce22c571c7113d4e). Just seems to be some simple error in the config-script. I didn't want to mess with the logic of that script, but I hope this at least helps finding the root of the error quickly.

**Comment by ck37** [comment]
Thanks, I also ran into this error and the hotfix helped me debug it. There is no need to modify the source code, just do:

```r
Sys.setenv(TENSORFLOW_PYTHON="/usr/local/bin/python")
Sys.setenv(TENSORFLOW_PYTHON_VERSION = 3)
devtools::install_github("rstudio/tensorflow")
```

**Comment by diloreto** [comment]
@ck37 did the exact same what you listed above (OSX 10.11 with python3 installed) and seeing the following:

```R
> Sys.setenv(TENSORFLOW_PYTHON="/usr/local/bin/python3")
> Sys.setenv(TENSORFLOW_PYTHON_VERSION = 3)
> devtools::install_github("rstudio/tensorflow")

Downloading GitHub repo rstudio/tensorflow@master
from URL https://api.github.com/repos/rstudio/tensorflow/zipball/master
Installing tensorflow
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/t_/ft7ccn1n6p9dlk83pdv0bp7c00b4pj/T/RtmpezsLY8/devtools109d376922085/rstudio-tensorflow-f3f6496'  \
  --library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library'  \
  --install-tests 
* installing *source* package ‘tensorflow’ ...
Using python binary at /usr/local/bin/python3
Using python version 3
Could not locate 
ERROR: configuration failed for package ‘tensorflow’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/tensorflow’
Error: Command failed (1)
```

I can definitely import & use the library in python3, but for some reason R cannot find my python binary. Any idea?

**Comment by ck37** [comment]
@diloreto Does /usr/local/bin/python3 actually contain the python3 binary? For me it does via Homebrew, but the "could not locate" error makes me think it doesn't on your system.

**Comment by henry-p** [comment]
@diloreto You actually did not exactly do what @ck37 did:
It apparently should be (even with python3!):
```
> Sys.setenv(TENSORFLOW_PYTHON="/usr/local/bin/python")
> Sys.setenv(TENSORFLOW_PYTHON_VERSION = 3)
```
(not `Sys.setenv(TENSORFLOW_PYTHON="/usr/local/bin/python3"`)

Anyway, I think this is illogical and should be fixed.

**Comment by diloreto** [comment]
@ck37 unless I'm misinterpreting your response (and I very well might), I ran python3 from that path and seeing my interpreter:

```bash
tonydiloreto@tonydiloreto-macbookpro:~$ /usr/local/bin/python3
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

@henry-p I don't have a binary in that location:

```bash
tonydiloreto@tonydiloreto-macbookpro:~$ /usr/local/bin/python
-bash: /usr/local/bin/python: No such file or directory
```

Error in my python3 installation (via homebrew) or referencing in the R installation environment variables? Thanks!

**Comment by ck37** [comment]
@diloreto you need to run the exact commands that I reported in my post, as @henry-p has correctly suggested. It adds the 3 to the path internally.

**Comment by diloreto** [comment]
That worked - thanks!

**Comment by nikolayvoronchikhin** [comment]
Thank you @diloreto, your hotfix helped me to install it globally.
