### ISSUE TITLE
Tensor flow re-install error ; Tensorboard configuration Error 

### ISSUE THREAD

**Issue by gbortz27** [rstudio/tensorflow#376]
1) Tensorflow wont install - although it is running; I loaded it sometime back so I think my setup has changed. 

   i) it was not running initially and trying a certain number of combinations regarding the setting of environmental variables it started running. But this is a problem as now Tensorboard is not running.
  ii) firstly my setup (Windows 10) 

         a) R Tensorflow version : 2.0.0
         b) tfestimators version 1.9.1
         c) keras version 2.2.5.0 ( I intend to run keras eventually ) 
         e) Python 3.6
         d) environmental Variables :
                             Conda (C:\Users\gbort\Anaconda3\Scripts)
                             Python  (C:\Users\gbort\Anaconda3\envs\r-tensorflow)
          Question: Do I have to have another tensorflow or tensorboard env variables or does python 
           bind to these .. This is where my confusion lies 
          There is a python folder in the R library folder under reticulate 
          C:\Users\gbort\Documents\R\win-library\3.6\reticulate\python

THE PROBLEMS 

1) I want to re-install the tensorflow - conda config

1)  `install_tensorflow(method="conda")`

   Error: **Unable to create process using 'C:\Users\gbort\ANACON~1\python.exe C:\Users\gbort\ANACON~1\Scripts\conda-script.py "create" "--yes" "--name" "r-reticulate" "python=3.6"'
Error: Error 101 occurred creating conda environment r-reticulate**

Tensorboard Error , see below for the  code and errors 

2) ```{r   Creating a single step TensorBoard }

    # Set up your session
    EmployeeSession <- tf$Session()
    
    # Add your constants
    female <- tf$constant(150, name = "FemaleEmployees")
    male <- tf$constant(135, name = "MaleEmployees")
    total <- tf$add(female, male)
    print(EmployeeSession$run(total))
    
    # Write to file
    towrite <- tf$summary$FileWriter('./graphs', EmployeeSession$graph)
    
    # Open Tensorboard
    tensorboard(log_dir = './graphs')

```

Error: **invalid version specification ‘Traceback (most recent call last):’, ‘ File "C:\Users\gbort\ANACON~1\envs\R-TENS~1\Scripts\tensorboard-script.py", line 10, in <module>’, ‘ sys.exit(run_main())’, ‘ File "C:\Users\gbort\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorboard\main.py", line 51, in run_main’, ‘ server.configure(sys.argv[1:])’, ‘ File "C:\Users\gbort\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorboard\program.py", line 143, in configure’, ‘ loader.fix_flags(flags)’, ‘ File "C:\Users\gbort\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorboard\plugins\core\core_plugin.py", line 405, in fix_flags’, ‘ raise ValueError('A logdir or db must be specified. '’, ‘ValueError: A logdir or db must be specified. For example `tensorboard --logdir mylogdir` or `tensorboard --db sqlite:~/.tensorboard.db`. Run `tensorboard --helpfull` for details and examples.’**

Dont understand the error ,

Many Thanks


By ther way when I run 

    tf_config()

the response is:

**TensorFlow v1.10.0 (C:\Users\gbort\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\__init__.p) Python v3.6 (C:\Users\gbort\ANACON~1\envs\R-TENS~1\python.exe)**

**Comment by gbortz27** [comment]
I did realize though that when running the following code with the callback_tensorboard function , a log file was generated ie

`model %>%
	fit (
        x = train_x_M, y = train_y_V,epochs = 25,
      	batch_size = 32, validation_split = .2,
      	callbacks = callback_tensorboard("logs/run_1")
    )
# # Call TensorBoard
tensorboard("logs/run_1")`

the model fit code above  worked , using the call back and generated a file named

"events.out.tfevents.1573914782.LAPTOP-0946ACR2"

but the function 

`tensorboard("logs/run_1")`  is the problem!!!

**Comment by dfalbel** [comment]
The easiest solution in this case is to completely remove and reinstall tensorflow. You can do this by runnning:

```
reticulate::conda_remove("r-reticulate")
```

And then reinstalling tensorflow

**Comment by gbortz27** [comment]
Hi Daniel

Thanks for yor assistance but I tried this

As I mentioned in my mail

reticulate::conda_remove("r-reticulate")

Results in the following

Unable to create process using 'C:\Users\gbort\ANACON~1\python.exe
C:\Users\gbort\ANACON~1\Scripts\conda-script.py "remove" "--yes" "--name"
"r-reticulate" "--all"'
Error: Error 101 occurred removing conda environment r-reticulate

Many Thanks

Graham

**Comment by gbortz27** [comment]
Running Tensorboard I now get

Error: invalid version specification ‘Traceback (most recent call last):’,
‘ File
"C:\Users\gbort\ANACON~1\envs\R-TENS~1\Scripts\tensorboard-script.py", line
10, in <module>’, ‘ sys.exit(run_main())’, ‘ File
"C:\Users\gbort\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorboard\main.py",
line 51, in run_main’, ‘ server.configure(sys.argv[1:])’, ‘ File
"C:\Users\gbort\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorboard\program.py",
line 143, in configure’, ‘ loader.fix_flags(flags)’, ‘ File
"C:\Users\gbort\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorboard\plugins\core\core_plugin.py",
line 405, in fix_flags’, ‘ raise ValueError('A logdir or db must be
specified. '’, ‘ValueError: A logdir or db must be specified. For example
`tensorboard --logdir mylogdir` or `tensorboard --db
sqlite:~/.tensorboard.db`. Run `tensorboard --helpfull` for details and
examples.’""

**Comment by HUSAIN23** [comment]
installing tensorflow in r ,getting error
>install_tensorflow()
Error in install_tensorflow() : 
  Unable to install TensorFlow on this platform.Binary installation is only available for 64-bit platforms

how can i solve this error

**Comment by dfalbel** [comment]
There's currently no way to install TensorFlow on 32bit systems.
