### ISSUE TITLE
Reloading installed tensorflow ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory 

### ISSUE THREAD

**Issue by mwmytu** [rstudio/tensorflow#38]
When I installed the tensorflow package using the R shell, it's fine.

But when installing via the rstudio web GUI, I get the following error:
.......
* DONE (tensorflow)
Reloading installed tensorflow
ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory 
If you have not yet installed TensorFlow, see https://www.tensorflow.org/get_started/

......

**Comment by terrytangyuan** [comment]
You RStudio might be using different Python path from Recript on console. Try to see if you can load TensorFlow from Python first.

**Comment by mwmytu** [comment]
@terrytangyuan  Rstudion desktop is ok, but rstudion sever cannot load tensorflow correctly.

**Comment by hunzikp** [comment]
@mwmytu I had the same issue. Adding the following lines to `$RHOME/etc/ldpaths` solved it for me:
```
export CUDA_HOME=/usr/local/cuda 
export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
```
