### ISSUE TITLE
support of hparams metrics logging for tensorboard 

### ISSUE THREAD

**Issue by philippmuench** [rstudio/tensorflow#385]
I just wonder if there is already an example how to log the parameters used in the training run to tensorboard? In python, the parameters are supplied with a dictionary `hparams[HP_OPTIMIZER]` and then recorded during the run (see https://www.tensorflow.org/tensorboard/hyperparameter_tuning_with_hparams#2_adapt_tensorflow_runs_to_log_hyperparameters_and_metrics). Is the support of *hparams* planned in future? Thanks!

**Comment by dfalbel** [comment]
@philippmuench I have just added a tutorial here: https://tensorflow.rstudio.com/tools/tensorboard/hparams/

**Comment by philippmuench** [comment]
Thanks a lot!
