### ISSUE TITLE
"Error: Feature spec is only available with TensorFlow >= 2.0"

### ISSUE THREAD

**Issue by dennist2** [rstudio/tensorflow#396]
Hi,

This is my first time asking a question on github so if i'm posting in the wrong place or doing some annoying just tell me and I won't do it again.

I'm trying to re-create a tutorial classifying structured data in R using keras/tensorflow. Everything works until I try the code:

---
> spec <- feature_spec(train_ds,target ~ .)
---

To which I get the error:

"Error: Feature spec is only available with TensorFlow >= 2.0

2. | stop("Feature spec is only available with TensorFlow >= 2.0", call. = FALSE)
1. | feature_spec(dataset = train_ds, target ~ .)"

All the packages required for the program and their current versions are:
   tfdatasets   -   2.0.0
   tensorflow  -   2.0.0
   rsample   -   0.0.5
   reticulate 1.13
   keras   -   2.2.5.0
   pins   -   1.0.6
  

I'm just providing what I've generally seen other people include with their issue description, so whatever information someone would need to see just ask away and i'll respond probably within 10-15 minutes if i'm not in class. 

Also, here is a link to the example if it does any good: 
https://tensorflow.rstudio.com/tutorials/advanced/structured/classify/

![Screenshot from 2020-02-05 05-54-52](https://user-images.githubusercontent.com/42229996/73835837-1c378800-47dc-11ea-987e-4ec8dd8d7b46.png)

**Comment by dfalbel** [comment]
In order to be able to use the `feature_spec` interface you need to install the TensorFlow 2.0 python package. You can do this by running:

```
tensorflow::install_tensorflow(version="2.0.0")
```

**Comment by t-kalinowski** [comment]
Looks like this issue is resolved. Please feel free to reopen or file a new issue if you are still encountering problems.
