### ISSUE TITLE
length() for scalar tensors should return 1

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/tensorflow#399]
```
length(tf$constant(1L))
```
currently returns NULL, should probably return 1.

**Comment by t-kalinowski** [comment]
if executing eagerly, it should probably just dispatch to `as.integer(tf$size())` instead of processing the output of `dim()`

**Comment by dfalbel** [comment]
That makes sense to me @t-kalinowski . Do you want to file a PR?

**Comment by t-kalinowski** [comment]
If I find an idle moment this weekend I'll try to pull together a PR...

**Comment by dfalbel** [comment]
Thank you!
