### ISSUE TITLE
CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2

### ISSUE THREAD

**Issue by faltinl** [rstudio/tensorflow#401]
**System information**
- OS Platform : Win10 Pro x64 (1909) 
- Processor: Intel(R) Core(TM) i7-9750H @ 2,6GHz
- TensorFlow version: 2.0.0 installed as tensorflow-gpu 
- Reticulate version: 1.14 installed via tensorflow
- Miniconda: Miniconda3-latest-Windows-x86_64.exe, updated to conda v4.8.2
- Keras version: 2.2.5.0 installed per tensorflow-gpu, via conda with Rstudio 1.2.5033 under R3.6.2

**Problem**
From [#976](https://github.com/rstudio/keras/issues/976) I learned that I need a processor capable to apply the AVX instruction set in order to be able to use TF2.0 under RStudio. Since then I have upgraded my equipment (including a nicely working NVIDIA RTX GeForce 2060 GPU) just to get the paradoxical warning

`CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2`

Q: Is there a tensorflow-build available for installation under RStudio and capable to use AVX2 and if so, where can I find it?

**Comment by skeydan** [comment]
AVX != AVX2 (see https://en.wikipedia.org/wiki/Advanced_Vector_Extensions)

This is a harmless warning. Especially if you have a GPU you shouldn't need to worry about it.
