### ISSUE TITLE
TensorFlow Installation Error In RStudio

### ISSUE THREAD

**Issue by andrew331** [rstudio/tensorflow#406]
Hello! I've been trying to follow the tutorial here:
https://blogs.rstudio.com/tensorflow/posts/2017-12-07-text-classification-with-keras/
and here:
https://tensorflow.rstudio.com/installation/

When it comes to installing and using tensorflow. However I have been getting errors. I have a version of anaconda 3 on my mac.

```
install.packages("keras")
install.packages("tensorflow")
library(keras)
library(tensorflow)
install_tensorflow()
library(tensorflow)
tf$constant("Hello Tensorflow")

```
I get the following error message:

Error: Python module tensorflow was not found.

```
Detected Python configuration:

python:         /usr/bin/python
libpython:      /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
pythonhome:     /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7
version:        2.7.16 (default, Oct 16 2019, 00:34:56)  [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
numpy:          /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy
numpy_version:  1.8.0
tensorflow:     [NOT FOUND] 
```

Any suggestions or workarounds?

**Comment by dfalbel** [comment]
It looks like TensorFlow  is not correctly installed. I recommend updating `reticulate`, `tensorflow` and `keras` to the latest version. Latest reticulate uses miniconda which should be much more robust than using the system python installation.

**Comment by t-kalinowski** [comment]
Looks like this issue is resolved. Please feel free to reopen or file a new issue if you are still encountering problems.
