### ISSUE TITLE
Cannot find tensorflow via reticulate

### ISSUE THREAD

**Issue by ryamy** [rstudio/tensorflow#414]
Hi teams, 

Thanks for you great work!!

I created conda virtual env named r-tensorflow and installed tensorflow-gpu to there. I confirmed python can import tensorflow and access gpu, but R environment can not import tensorflow via reticulate as bellow.

How can I configure this situation? 

Thanks!

**Python environment**
``` 
(r-tensorflow) c:\oracle>
(r-tensorflow) c:\oracle>ipython
ipython
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.9.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tensorflow as tf

In [2]: from tensorflow.python.client import device_lib

In [3]: device_lib.list_local_devices()
2020-04-15 08:40:06.837229: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-04-15 08:40:07.016953: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.53GiB
2020-04-15 08:40:07.017200: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2020-04-15 08:40:08.713936: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-15 08:40:08.714078: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2020-04-15 08:40:08.714156: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2020-04-15 08:40:08.717609: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:0 with 6259 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5)
Out[3]: 
[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 803561976756395359, name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 6563427124
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 1285587801828002551
 physical_device_desc: "device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5"]


```

**R environment**
```
> library(reticulate)
> library(keras)
> library(tensorflow)
> 
> Sys.setenv(RETICULATE_PYTHON="c:/apps/Anaconda3/envs/r-tensorflow/python.exe")
> Sys.setenv(TENSORFLOW_PYTHON="c:/apps/Anaconda3/envs/r-tensorflow/python.exe")
> 
> use_condaenv('r-tensorflow')
> 
> py_config()
python:         c:/apps/Anaconda3/envs/r-tensorflow/python.exe
libpython:      c:/apps/Anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     c:/apps/Anaconda3/envs/r-tensorflow
version:        3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          c:/apps/Anaconda3/envs/r-tensorflow/Lib/site-packages/numpy
numpy_version:  1.16.5
tensorflow:     c:\apps\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\__init__.p

NOTE: Python version was forced by RETICULATE_PYTHON
> 
> np <- import("numpy", convert = FALSE)
> 
> a <- np$array(c(1:4))
> 
> sum <- a$cumsum()
> 
> py_to_r(sum)
[1]  1  3  6 10
> 
> hdevice_lib <- import("tensorflow.python.client.device_lib")
Error in py_module_import(module, convert = convert) : 
  ImportError: Traceback (most recent call last):
  File "c:\apps\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\apps\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\apps\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\apps\Anaconda3\envs\r-tensorflow\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "c:\apps\Anaconda3\envs\r-tensorflow\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 謖 ｮ壹＆繧後◆繝｢繧ｸ繝･繝ｼ繝ｫ縺瑚ｦ九▽縺九ｊ縺ｾ縺帙ｓ縲 


Failed to load 
> 
>
> tf_config()
Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 c:\apps\Anaconda3\envs\r-tensorflow\python.exe

You can install TensorFlow using the install_tensorflow() function.
 
> 
```

**Comment by skeydan** [comment]
Hi, what is your TensorFlow (Python) version?
What is the DLL that cannot be loaded?

> ImportError: DLL load failed: 謖 ｮ壹＆繧後◆繝｢繧ｸ繝･繝ｼ繝ｫ縺瑚ｦ九▽縺九ｊ縺ｾ縺帙ｓ縲 

Perhaps there are differences in the library path (LD_LIBRARY_PATH if this were linux) between the R (is it RStudio?) and Python environments?

**Comment by ryamy** [comment]
Thanks for your advice!

I am using R via Emacs-ESS, so I do not use Rstudio. 

My envirioment is ; GPU: RTX 2080, CUDA10, cuDNN7.1, in windows10.

**tensorflow(python) version**
```
d:\>activate r-tensorflow
activate r-tensorflow
(r-tensorflow) d:\>
(r-tensorflow) d:\>
(r-tensorflow) d:\>conda list | findstr tensorflow
conda list | findstr tensorflow
# packages in environment at C:\apps\Anaconda3\envs\r-tensorflow:
r-tensorflow              1.13.1            r36h6115d3f_0    r
tensorflow-estimator      1.13.0                   pypi_0    pypi
tensorflow-gpu            1.13.1                   pypi_0    pypi
tensorflow-gpu-estimator  2.1.0                    pypi_0    pypi
```

> ImportError: DLL load failed: 謖 ｮ壹＆繧後◆繝｢繧ｸ繝･繝ｼ繝ｫ縺瑚ｦ九▽縺九ｊ縺ｾ縺帙ｓ縲

I could not specify this DLL because of  I'm not familiar with these kind of (character encoding?) issue...

I found that  R can find GPU when **not** specifying specific python environment as bellow.
In that case, reticulate call python in r-miniconda env(r-reticulate) and can find GPU (despite of  tensorflow version is ver 2.0.0).

Anyway, currently I can access GPU (but not env I would like to use...  ). Thanks!

**reticulate default settings can find GPU**
```
> library(reticulate)
> library(keras)
> library(tensorflow)
>
>## setting bellow resulted in Dll error. 
>## Sys.setenv(RETICULATE_PYTHON="c:/apps/Anaconda3/envs/r-tensorflow/python.exe")
>## use_condaenv('r-tensorflow')
> 
> py_config()
python:         C:/Users/xxxx/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/xxxx/AppData/Local/r-miniconda/envs/r-reticulate/python36.dll
pythonhome:     C:/Users/xxxx/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.6.10 |Anaconda, Inc.| (default, Mar 23 2020, 17:58:33) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/xxxx/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.18.1
> 
> 
> device_lib <- import('tensorflow.python.client.device_lib')
> 
> device_lib$list_local_devices()
2020-04-16 01:28:13.786892: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-04-16 01:28:13.790937: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-04-16 01:28:13.873593: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:01:00.0
2020-04-16 01:28:13.873936: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-04-16 01:28:13.883067: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-04-16 01:28:14.496051: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-16 01:28:14.496217: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-04-16 01:28:14.496298: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-04-16 01:28:14.507279: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/device:GPU:0 with 6249 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5)
[[1]]
name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 10502870103655074597


[[2]]
name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 6553465652
locality {
  bus_id: 1
  links {
  }
}
incarnation: 6794371060314739316
physical_device_desc: "device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5"

**r-reticulate(r-miniconda) environment**
```
c:\Users\xxxx\AppData\Local\r-miniconda\Scripts>activate r-reticulate
activate r-reticulate
(r-reticulate) c:\Users\xxxx\AppData\Local\r-miniconda\Scripts>conda list | findstr tensorflow
 | findstr tensorflow
(r-reticulate) c:\Users\xxxx\AppData\Local\r-miniconda\Scripts>conda list | findstr tensorflow
conda list | findstr tensorflow
tensorflow                2.0.0                    pypi_0    pypi
tensorflow-estimator      2.0.1                    pypi_0    pypi
tensorflow-gpu            2.0.0                    pypi_0    pypi
tensorflow-hub            0.8.0                    pypi_0    pypi

```

**Comment by skeydan** [comment]
Hi,

I'm not sure I completely understand :-)

But from what I see, the environment you want to use fails to load in Python as well, right?
In that case, sometimes it makes sense to open an issue directly in the Python (Google) TensorFlow repository.

That said, however, seeing these python packages in that respective env

```
r-tensorflow                      1.13.1            r36h6115d3f_0    r
tensorflow-estimator         1.13.0                   pypi_0    pypi
tensorflow-gpu                  1.13.1                   pypi_0    pypi
tensorflow-gpu-estimator  2.1.0                    pypi_0    pypi
```

I do not think that TensorFlow 1.13 was compatible with CUDA 10 - 1.13 is pretty old by now... 
(Just as an aside, there is a non-matching tensorflow-gpu-estimator  2.1.0 in there... And I wonder what is `r-tensorflow` ?)

What are your requirements? Do you have to use TensorFlow 1.13 for some reason?

**Comment by ryamy** [comment]
What I'd like to do is;

- Deep Learning with GPU in R (thus, I installed reticulate in R)
- From R, use Python libraries already I installed in Anaconda3 virtual env (if possible)

Python pacakges `r-tensorflow` is derived from https://anaconda.org/r/r-tensorflow.
I misunderstood at first that installing `r-tensorflow` would allow my requirements.

> I do not think that TensorFlow 1.13 was compatible with CUDA 10 - 1.13 is pretty old by now...

Thanks, I do not have specific reason to use tensorflow 1.13. 

As you mentioned, currently my environment is dirty and complicated, I think...  So I will reconstruct my virtual env, re-install tensorflow(2.0), and try reticulate again. If that still doesn't solve the problem, I'm going to install python libraries to r-miniconda environment.

Following is current situation (just for my memo).
|Python from    | virtual env      |python ver |tensorflow ver | can find GPU via python | can find GPU via R(reticulate) |
|:---                   | :---                 |:---  |:---  |     :---:                                |         :---:                                  |
|r-miniconda     | r-reticulate    | 3.7.6|2.0.0  |No                                     | Yes                                           |
|Anaconda3      | r-tensorflow   | 3.6.5|1.13.1 | Yes                                    | No                                         |

**Comment by skeydan** [comment]
Sounds good! I would just completely remove everything, then let R use (= create) the default r-reticulate environment, and do `install_tensorflow(version = "2.0")` there.

(I don't think you mentioned your exact CUDA version - depending on that you could also try `install_tensorflow()` which would install 2.1.)
