### ISSUE TITLE
slicing tensors -60:

### ISSUE THREAD

**Issue by philipus** [rstudio/tensorflow#421]
How can I implement the functionality below
```
slice <- function(x, seq_length){
  #x[:,-seq_length:,:]
  x[,`-60:`,]
}
```

**Comment by henry090** [comment]
Hi, please refer to this link: https://www.tensorflow.org/api_docs/python/tf/slice
If something goes wrong, please share a reproducible example.

**Comment by philipus** [comment]
Did not help much

The question is quite r to python specific 

Using dim(x)[2] similar in the example of the above link suggested does not help much 

So maybe it is better for me to to use np in r here and the syntax  ‘-60:’ which works but is not dynamic

**Comment by t-kalinowski** [comment]
You can wrap expressions in the backpacks as well, not just numeric literals.
``` r
library(tensorflow)

slice <- function(x, seq_length){
  x[,`-seq_length:`]
}

x <- as_tensor(rbind(1:12, 1:12, 1:12))
#> Loaded Tensorflow version 2.7.0
 
slice(x, 4)
#> Warning: Negative numbers are interpreted python-style when subsetting tensorflow tensors. (they select items by counting from the back). For more details, see:
#>  https://numpy.org/doc/stable/reference/arrays.indexing.html#basic-slicing-and-indexing
#> To turn off this warning, set 'options(tensorflow.extract.warn_negatives_pythonic = FALSE)'
#> tf.Tensor(
#> [[ 9 10 11 12]
#>  [ 9 10 11 12]
#>  [ 9 10 11 12]], shape=(3, 4), dtype=int32)
```

<sup>Created on 2021-12-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
