### ISSUE TITLE
404 error on the local GPU installation page

### ISSUE THREAD

**Issue by namanpaul** [rstudio/tensorflow#424]
Hi, 
I am looking for detailed instructions for TensorFlow GPU version installation. However, the page link is throwing a 404 error. Any help would be much appreciated. 

Link:
• https://tensorflow.rstudio.com/installation/gpu/local_gpu.html

**Comment by jonthegeek** [comment]
Navigating the menus found this: https://tensorflow.rstudio.com/installation/gpu/local_gpu/

Where was the broken link?

**Comment by namanpaul** [comment]
I was on this particular page: https://tensorflow.rstudio.com/installation/gpu/
The local GPU page is accessible through the list, ✅  
• Overview
• Local

However, if you try to click on the Local GPU icon, that redirects to a 404 error page.

![image](https://user-images.githubusercontent.com/10536682/83578027-8c37ef80-a4ea-11ea-86ed-0eaa22865344.png)

**Comment by dfalbel** [comment]
Fixed with https://github.com/r-tensorflow/r-tensorflow/commit/a7c51ea4374261567c26bd525c85b429f46c3294
