### ISSUE TITLE
Unable to install with Tensorflow installed to Windows 7

### ISSUE THREAD

**Issue by klsh** [rstudio/tensorflow#43]
I have installed Rtools, and the python 3.5 package recommended by Google for tensorflow. I have confirmed that Tensorflow works from the cmd prompt when invoked. I believe the config file for windows needs added to this package.

**Comment by jjallaire** [comment]
That's correct, we don't yet support Windows.

**Comment by caiweining** [comment]
Will support windows in the future？@jjallaire

**Comment by jjallaire** [comment]
Yes, in the future for sure. We'd love to see this as a PR.

**Comment by jjallaire** [comment]
Work on support for Windows is in progress here: https://github.com/rstudio/tensorflow/tree/feature/windows-version

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/tensorflow/tree/feature/windows-version
