### ISSUE TITLE
Installation of TensorFlow not found.

### ISSUE THREAD

**Issue by fleun** [rstudio/tensorflow#437]
Hi,
I have trouble running to_categorical function. I guess it is probably some bug in tensorflow or keras

I follow the instructions from https://github.com/rstudio/keras/issues/639 

```
>devtools::install_github("rstudio/tensorflow")
>devtools::install_github("rstudio/keras")
>tensorflow::install_tensorflow()
```
and I got this error when running this

```
>tensorflow::tf_config()
Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\Users\Dell\AppData\Local\r-miniconda\envs\r-reticulate\python.exe

You can install TensorFlow using the install_tensorflow() function.
```

These are some of my diagnostics:
```
>reticulate::py_discover_config()
python:         C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/python36.dll
pythonhome:     C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.6.12 |Anaconda, Inc.| (default, Sep  9 2020, 00:29:25) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.19.1
```

Nothing happened when I do this :
`> reticulate::use_condaenv("r-tensorflow")`

```
>reticulate::py_config()
python:         C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/python36.dll
pythonhome:     C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.6.12 |Anaconda, Inc.| (default, Sep  9 2020, 00:29:25) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.19.1

```
Thanks for taking the time to fix it. I really need this function.

Felix

**Comment by max-poltora** [comment]
Hi all, 

I have had the same issue. I have found the solution in [this branch](https://github.com/rstudio/tensorflow/issues/311). The method works in my case, but I have to do manipulations with installation every time I start new R session. In summary I do the following steps:

```
library(keras)
use_condaenv("tf")
library(reticulate)
install_keras(method = c("conda"), conda = "auto", version = "default", tensorflow = "gpu")
```
After that I load Anaconda prompt and run:

```
conda activate tf
conda create -y --name tf tensorflow-gpu python=3.6.8
conda activate tf
```
Then, when I get back to my R session I get the following output:
`tensorflow::tf_config()`

> TensorFlow v2.1.0 (C:\Users\user\ANACON~1\envs\tf\lib\site-packages\tensorflow_init_.p)
> Python v3.6 (C:/Users/user/anaconda3/envs/tf/python.exe)
 
`keras:::keras_version()`

> [1] ‘2.2.4’

`reticulate::py_config()`

> python: C:/Users/user/anaconda3/envs/tf/python.exe
> libpython: C:/Users/user/anaconda3/envs/tf/python36.dll
> pythonhome: C:/Users/user/anaconda3/envs/tf
> version: 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]
> Architecture: 64bit
> numpy: C:/Users/user/anaconda3/envs/tf/Lib/site-packages/numpy
> numpy_version: 1.19.2
> tensorflow: C:\Users\user\ANACON~1\envs\tf\lib\site-packages\tensorflow_init_.p
> 
> python versions found:
> C:/Users/user/anaconda3/envs/tf/python.exe
> C:/Users/user/anaconda3/python.exe

Hope this helps.

**Comment by ssh352** [comment]
> Hi,
> I have trouble running to_categorical function. I guess it is probably some bug in tensorflow or keras
> 
> I follow the instructions from [rstudio/keras#639](https://github.com/rstudio/keras/issues/639)
> 
> ```
> >devtools::install_github("rstudio/tensorflow")
> >devtools::install_github("rstudio/keras")
> >tensorflow::install_tensorflow()
> ```
> 
> and I got this error when running this
> 
> ```
> >tensorflow::tf_config()
> Installation of TensorFlow not found.
> 
> Python environments searched for 'tensorflow' package:
>  C:\Users\Dell\AppData\Local\r-miniconda\envs\r-reticulate\python.exe
> 
> You can install TensorFlow using the install_tensorflow() function.
> ```
> 
> These are some of my diagnostics:
> 
> ```
> >reticulate::py_discover_config()
> python:         C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
> libpython:      C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/python36.dll
> pythonhome:     C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate
> version:        3.6.12 |Anaconda, Inc.| (default, Sep  9 2020, 00:29:25) [MSC v.1916 64 bit (AMD64)]
> Architecture:   64bit
> numpy:          C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
> numpy_version:  1.19.1
> ```
> 
> Nothing happened when I do this :
> `> reticulate::use_condaenv("r-tensorflow")`
> 
> ```
> >reticulate::py_config()
> python:         C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
> libpython:      C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/python36.dll
> pythonhome:     C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate
> version:        3.6.12 |Anaconda, Inc.| (default, Sep  9 2020, 00:29:25) [MSC v.1916 64 bit (AMD64)]
> Architecture:   64bit
> numpy:          C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
> numpy_version:  1.19.1
> ```
> 
> Thanks for taking the time to fix it. I really need this function.
> 
> Felix

same issue here:
install_tensorflow() was successful but Tensorflow::tf_config() shows installation Tensorflow not found

**Comment by t-kalinowski** [comment]
Hello,

The code that installs tensorflow and keras has been [refactored](https://github.com/rstudio/tensorflow/pull/476).
Please update to the latest versions of reticulate, tensorflow, and keras:
```R
install.packages("remotes")
remotes::install_github(paste0("rstudio/", c("reticulate", "tensorflow", "keras")))
reticulate::install_miniconda() # skip this if you want to self-install conda or use venv
keras::install_keras()
```

Please let us know if after updating you are still encountering installation issues:
https://github.com/rstudio/tensorflow/issues/new
