### ISSUE TITLE
Tensorflow does not attempt to search the conda environment it created

### ISSUE THREAD

**Issue by msto** [rstudio/tensorflow#438]
Hi,

I'm attempting to install the tensorflow for R package on Linux (Ubuntu 18.04). I followed the [quick start directions](https://tensorflow.rstudio.com/installation/), explicitly requesting conda instead of virtualenv. However, I'm encountering two bugs in the process.

```
> install.packages("tensorflow")
> library(tensorflow)
> install_tensorflow(method="conda", envname="R_tensorflow", conda_python="3.7", version="cpu")
```

## Bug 1 - tensorflow for R does not search the conda environment it created

After successfully creating the new environment and installing tensorflow and its dependencies, the tensorflow for R package does not recognize the installation.

```
> library(tensorflow)
> tf$constant("Hello Tensorflow")
Error: Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /home/mstone/.conda/envs/py37/bin/python3.7
 /usr/bin/python3.6
 /usr/bin/python2.7
```

Specifically, it only searches the conda environment that was active when I started the R session. I did check that the environment created by tensorflow for R exists and has a working tensorflow installation:

```
$ conda info --envs
# conda environments:
#
base                     /app/software/Miniconda3/4.7.10
R_tensorflow             /home/mstone/.conda/envs/R_tensorflow
py37                  *  /home/mstone/.conda/envs/py37
```

```
$ conda deactivate && conda activate R_tensorflow
$ python
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.constant("Hello world")
<tf.Tensor: shape=(), dtype=string, numpy=b'Hello world'>
```

## Bug 2 - permission error when searching the correct environment

I confirmed that tensorflow for R only checks the conda environment that was active when R started (in both my base and the R_tensorflow environments), but I continue to get an error when trying to use tensorflow for R with the environment it created.

```
$ conda deactivate && conda activate R_tensorflow
$ R
> library(tensorflow)
> tf$constant("Hello world")

sh: 1: /home/mstone/.conda/envs/R_tensorflow: Permission denied
Error: Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /home/mstone/.conda/envs/R_tensorflow/bin/python3.7
 /usr/bin/python3.6
 /usr/bin/python2.7
```

Here, the correct environment was searched, but I get a permission error that I didn't get within the other environments. I checked the environment directories and don't see any permission differences between my usual environment (`py37`) and the one created by tensorflow for R (`R_tensorflow`).

```
$ ls -ltrh /home/mstone/.conda/envs/
total 16K
drwxrws--- 22 mstone g_mstone 4.0K Oct  5 19:36 py37
drwxrws--- 11 mstone g_mstone 4.0K Oct  6 12:38 R_tensorflow
```

## Summary

I'm encountering two bugs after using `install_tensorflow()`.  
1. The tensorflow for R package does not search the conda environment it created, but instead the environment that was active when starting R.
2. If I start R after activating the conda environment that tensorflow for R created, I continue to get a "TensorFlow" not found error that appears to be due to a permission issue on the created environment (which I am unable to identify.)

Could you please let me know if I can provide any additional information to help address these? Thanks!

**Comment by msto** [comment]
## sessionInfo

Output from `sessionInfo()` if it's helpful

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS/LAPACK: /app/software/OpenBLAS/0.3.7-GCC-8.3.0/lib/libopenblas_haswellp-r0.3.7.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] tensorflow_2.2.0

loaded via a namespace (and not attached):
 [1] compiler_4.0.2  magrittr_1.5    Matrix_1.2-18   whisker_0.4
 [5] base64enc_0.1-3 rappdirs_0.3.1  Rcpp_1.0.4.6    reticulate_1.16
 [9] grid_4.0.2      jsonlite_1.7.0  tfruns_1.4      lattice_0.20-41
```

**Comment by msto** [comment]
I've found that explicitly setting the active environment with `reticulate` fixes this.

```
> reticulate::use_condaenv("R_tensorflow")
> library(tensorflow)
> tf$constant("Hello world")
tf.Tensor(b'Hello world', shape=(), dtype=string)
```

**Comment by t-kalinowski** [comment]
Conda can encounter errors when using a base installation that is not writable from a session that was not initialized by conda. 

There are potential cumbersome workarounds, but rather then fighting conda, I would suggest letting R/reticulate install and manage it's own installation of miniconda. Try:
```R
reticulate::install_miniconda()
tensorflow::install_tensorflow()
```
