### ISSUE TITLE
Input function doesn't work in R

### ISSUE THREAD

**Issue by ShantanuKumar** [rstudio/tensorflow#44]
https://www.tensorflow.org/versions/r0.11/tutorials/input_fn/index.html
I have been following the tutorial for using input function, but I can't seem to make it work. 
Since we don't have multiple return values in R, I am using list. Has anyone been able to implement the code as mentioned in the tutorial? 

Thank you for your help!

**Comment by terrytangyuan** [comment]
Could you paste your code here?

**Comment by terrytangyuan** [comment]
This should be fixed in master.
