### ISSUE TITLE
use_session_with_seed broken with TensorFlow 2.0

### ISSUE THREAD

**Issue by wangshisheng** [rstudio/tensorflow#446]
Hi all,

There are still some problems about the 'use_session_with_seed' function with TensorFlow 2.0 in RStudio. The error is like:

>tensorflow::use_session_with_seed(123)
Error in py_get_attr_impl(x, name, silent):
  AttributeError: module 'tensorflow_core.keras.backend' has no attribute 'set_session'.

How could I solve this? Thank a lot.

Shisheng

**Comment by anirban-mukherjee** [comment]
Try `tf$random$set_seed(123L)`

**Comment by wangshisheng** [comment]
> Try `tf$random$set_seed(123L)`

Yeah, I will try it, thanks a lot~~
