### ISSUE TITLE
Updates to README.md?

### ISSUE THREAD

**Issue by philshem** [rstudio/tensorflow#449]
Are the details for installation and usage in this repo's README.md outdated?

**README.md**

    devtools::install_github("rstudio/tensorflow")

**https://tensorflow.rstudio.com/installation/**

    install.packages("tensorflow")

<s>And is this sentence also still true? Or is TF for R now native?

> The TensorFlow API is composed of a set of Python modules that enable constructing and executing TensorFlow graphs. </s>

**Comment by anirban-mukherjee** [comment]
The tensorflow for R library is not "native". It uses reticulate to embed a Python session in your R session and imports the TF module in the Python session.

**Comment by eddelbuettel** [comment]
But "native code" commonly means binary. See [_e.g._ this older SO post](https://stackoverflow.com/questions/3434202/what-is-the-difference-between-native-code-machine-code-and-assembly-code).

**Comment by philshem** [comment]
My issue is not so much about TF being native to R, but rather how to install. It seems the README.me installation step still requires `devtools` while the website has a normal `install.packages()`

**Comment by eddelbuettel** [comment]
_Many_ project on GitHub state exactly the same, giving you a choice of installing the release from CRAN or a development version from GitHub.  Two different approaches, two different commands.  Most users appreciate having a choice.

**Comment by anirban-mukherjee** [comment]
@philshem To clarify: devtools gets you the development version from GitHub; install.packages gets you the last release from CRAN.

@eddelbuettel Native code means machine code. Native to a language is an imprecise term to capture features that are a part of the core ("supported"/"official") feature spec of a language vs those that require extensions, other languages, etc. For e.g., see this [SO post](https://softwareengineering.stackexchange.com/questions/147965/what-is-meant-by-native-support-for-a-feature-in-a-programming-language). The distinction is somewhat moot in R where non native libraries are the norm. But even in R, a library that requires an embedded session of another language is atypical and requires a greater degree of dependence on another language (Python) than usual.

I prefer the tensorflow R library approach to the torch R library approach. IMO, reticulate is an excellent library and the performance overhead is minimal. Importantly, the reticulate approach means that one's R and Python code can use the same TF binary. Else, one's hat hangs on the C++ API and the Python API being a 100% in sync, which is not always going to be true in a project as complex and dynamic as TensorFlow/PyTorch. In time, things will stabilise but these are early days.
