### ISSUE TITLE
Change activation of final layer in a model

### ISSUE THREAD

**Issue by willi3by** [rstudio/tensorflow#450]
Hi,

I am not sure whether to post this here or in the reticulate issues, so let me know if this is the wrong place. 

I am trying to implement 3D Grad CAM for my 3D Residual Network. However, when I try to replace the activation function in the last layer of my model I receive an error. 

```
model$layers[[length(model$layers)]]$activation = tf$keras$activations$linear

Error in py_set_attr_impl(x, name, value) : 
  AttributeError: Can't set the attribute "layers", likely because it conflicts with an existing read-only @property of the object. Please choose a different name.

Detailed traceback: 
  File "C:\Users\willi3by\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py", line 340, in __setattr__
    super(Model, self).__setattr__(name, value)
  File "C:\Users\willi3by\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\base_layer.py", line 2767, in __setattr__
    'different name.').format(name))
```

I have tried multiple permutations of this same code to no avail. Here is the relevant environment that I am using:
```
R - 4.0.3
reticulate - 1.18
python - 3.7.9
tensorflow - 2.3
tf-keras-vis - 1.18.5
```

I know I didn't provide much detail about the model itself but I did not think it was relevant to the issue. If it is, let me know and I am happy to provide as much detail as necessary.

Thanks for the help!

**Comment by dfalbel** [comment]
Not super nice, but you can do something like this:

``` r
library(keras)

model <- keras_model_sequential() %>% 
  layer_activation(activation = "linear", input_shape = 1)

reticulate::py_set_attr(model$layers[[1]], "activation", tensorflow::tf$abs)
model$layers[[1]]$activation
#> <function abs at 0x7fe2ccb6c160>

predict(model, c(-1,2,3))
#>      [,1]
#> [1,]    1
#> [2,]    2
#> [3,]    3
```

<sup>Created on 2021-02-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by willi3by** [comment]
Thanks for this! I somehow missing the py_set_attr function in reticulate, that will be very useful for this and other applications.
