### ISSUE TITLE
LD_LIBRARY_PATH works for Python but not R

### ISSUE THREAD

**Issue by chriscardillo** [rstudio/tensorflow#452]
Hello and thanks for making tensorflow and keras available in R.

I've recently update my machine (Ubuntu 20.04) to use CUDA 11.0 and cuDNN 8.1.

My GPU is working as expected in Python (when I run `tf.config.list_physical_devices('GPU')`, I see my GPU), however when I try to test tensorflow in R (`tensorflow::tf_gpu_configured()`), R cannot find my CUDA 11 runtime. Here is the error I am seeing:

```
021-02-04 09:11:46.028506: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib:/usr/lib:/usr/local/cuda-11.0/lib64:/usr/lib/cuda/lib64:/usr/lib/cuda/include
```

Before upgrading CUDA, I had my LD_LIBRARY_PATH in `/etc/R/Renviron.site` and was able to use tensorflow and my GPU from R, but this is no longer working for me after the upgrade.

Is there anything else I should try in order to get my GPU working properly with tensorflow in R again?

**Comment by myoung3** [comment]
This might not be your issue, but it's caused me problems in the past so I'll mention it. If you're using rstudio server environment variables set globally cannot be overridden by individual users. If you try to set LD_LIBRARY_PATH via .Renviron it will be silently ignored by rstudio.

[ref](https://community.rstudio.com/t/rstudio-server-oss-define-custom-libpath-for-all-users/37438)

**Comment by chriscardillo** [comment]
Thanks @myoung3. My issue, though, is currently while using RStudio Desktop.

**Comment by chriscardillo** [comment]
@skeydan - Sorry to randomly @ you but I think you have helped solve issues like this in the past. Do you have any insight on how to amend this? Or do you know anyone who might? Happy to provide more details.

**Comment by myoung3** [comment]
Are you sure the python you're  testing at the shell is the one R is running? Print py_config() in R

**Comment by chriscardillo** [comment]
@myoung3 confirming same installation.

I have fixed this, it seems to have been a path issue. I had two versions of cuda in my `LD_LIBRARY_PATH`, and I think that was confusing to my R tensorflow installation.

I resolved this probably by just having both lib64 and include on my path, e.g. `LD_LIBRARY_PATH="/usr/local/cuda-11.0/lib64:/usr/local/cuda-11.0/include:$LD_LIBRARY_PATH"`.
