### ISSUE TITLE
Tensorflow crash R session [R studio - Ubuntu 18.04]

### ISSUE THREAD

**Issue by duybluemind1988** [rstudio/tensorflow#455]
I tried many ways  to install tensorflow in R (rstudio) but failed. Here are some ways that I tried:

Method 1:

```
install.packages("remotes")
remotes::install_github("rstudio/tensorflow")
library(tensorflow)
install_tensorflow(version = "2.0.0b1")
```

All install successful, but R crash when I run:

```
library(tensorflow)
tf_config() or tf$abs(-1)
```

Method 2:

```
install.packages("devtools")
devtools::install_github("rstudio/tensorflow",dependencies=TRUE)
install_tensorflow()
```

All install successful, but R crash again when I run

```
tf_config() # or
tf$constant("Hellow Tensorflow")
```

Method 3:

```
install.packages("tensorflow")
library(tensorflow)
install_tensorflow()
```

When install completed, R crash again when I run:

```
library(tensorflow)
tf$constant("hello tensorflow")
```

Method 4:

```
library(tensorflow)
install_tensorflow(method = "conda", envname = "py3.6", conda_python_version = "3.6")
```

When install completed, R crash again when I run:

```
library(tensorflow)
tf$constant("hello tensorflow")

```
My environment:

- Ubuntu 18.04
- R studio version 1.4.1103
- R version 4.0.4
- Conda version 4.9.2 (installed anaconda in ubuntu)
- Python version 3.8.5

I see many tensorflow install path in my computer after complete 4 methods above:

- path1: home/user/anaconda3/envs/r-reticulate/lib/python3.7/site-packages/tensorflow
- path2: home/user/anaconda3/envs/r-reticulate/lib/python3.6/site-packages/tensorflow
- path3: home/user/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow
- path4: home/user/anaconda3/envs/py3.8.5/lib/python3.7/site-packages/tensorflow

Could you help please ? Thank!

**Comment by dfalbel** [comment]
It would be great to have a backtrace. Can you try running this in a standalone R console, outside Rstudio?

**Comment by jane2710** [comment]
Hello ! Same problem -
Using RStudio : library(tensorflow), tf$constant("hello tensorflow"), leads R to crash
Using R standalone console , leads to the following error message: R for Windows GUI front end has stopped working-
Environment: Windows7/Pro, R 4.04 , Anaconda 3 2020.11, Python 3.8.5, old IntelCore i3-3220, RAM 8GB, I have updated Anaconda today.  Many thanks for your help !! bests

**Comment by jane2710** [comment]
Here is the trade just before it crashes:
R version 4.0.4 (2021-02-15) -- "Lost Library Book"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R est un logiciel libre livré sans AUCUNE GARANTIE.
Vous pouvez le redistribuer sous certaines conditions.
Tapez 'license()' ou 'licence()' pour plus de détails.

R est un projet collaboratif avec de nombreux contributeurs.
Tapez 'contributors()' pour plus d'information et
'citation()' pour la façon de le citer dans les publications.

Tapez 'demo()' pour des démonstrations, 'help()' pour l'aide
en ligne ou 'help.start()' pour obtenir l'aide au format HTML.
Tapez 'q()' pour quitter R.

> install.packages("tensorflow")
Installing package into ‘C:/Users/David2/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
           binary source needs_compilation
tensorflow  2.2.0  2.4.0             FALSE

installing the source package ‘tensorflow’

essai de l'URL 'https://cran.rstudio.com/src/contrib/tensorflow_2.4.0.tar.gz'
Content type 'application/x-gzip' length 42089 bytes (41 KB)
downloaded 41 KB

* installing *source* package 'tensorflow' ...
** package 'tensorflow' correctement décompressé et sommes MD5 vérifiées
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'tensorflow'
    finding HTML links ... fini
    all_dims                                html  
    evaluate                                html  
    export_savedmodel                       html  
    install_tensorflow                      html  
    install_tensorflow_extras               html  
    parse_arguments                         html  
    finding level-2 HTML links ... done

    parse_flags                             html  
    reexports                               html  
    set_random_seed                         html  
    shape                                   html  
    sub-.tensorflow.tensor                  html  
    tensorboard                             html  
    tensorflow                              html  
    tf                                      html  
    tf_config                               html  
    tf_extract_opts                         html  
    tf_function                             html  
    tf_gpu_configured                       html  
    tf_probability                          html  
    tfe_enable_eager_execution              html  
    train                                   html  
    train_and_evaluate                      html  
    use_compat                              html  
    use_session_with_seed                   html  
    view_savedmodel                         html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (tensorflow)

The downloaded source packages are in
	‘C:\Users\David2\AppData\Local\Temp\Rtmpojbd8k\downloaded_packages’
> library(tensorflow)
> install_tensorflow()
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

Requirement already satisfied: tensorflow==2.4 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (2.4.0)
Requirement already satisfied: astunparse~=1.6.3 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (1.6.3)
Requirement already satisfied: opt-einsum~=3.3.0 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (3.3.0)
Requirement already satisfied: wrapt~=1.12.1 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (1.12.1)
Requirement already satisfied: google-pasta~=0.2 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (0.2.0)
Requirement already satisfied: wheel~=0.35 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (0.36.2)
Requirement already satisfied: six~=1.15.0 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (1.15.0)
Requirement already satisfied: grpcio~=1.32.0 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (1.32.0)
Requirement already satisfied: numpy~=1.19.2 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (1.19.2)
Requirement already satisfied: tensorboard~=2.4 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (2.4.1)
Requirement already satisfied: flatbuffers~=1.12.0 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (1.12)
Requirement already satisfied: h5py~=2.10.0 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (2.10.0)
Requirement already satisfied: tensorflow-estimator<2.5.0,>=2.4.0rc0 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (2.4.0)
Requirement already satisfied: absl-py~=0.10 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (0.12.0)
Requirement already satisfied: termcolor~=1.1.0 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (1.1.0)
Requirement already satisfied: typing-extensions~=3.7.4 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (3.7.4.3)
Requirement already satisfied: gast==0.3.3 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (0.3.3)
Requirement already satisfied: keras-preprocessing~=1.1.2 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (1.1.2)
Requirement already satisfied: protobuf>=3.9.2 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (3.15.6)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorboard~=2.4->tensorflow==2.4) (52.0.0.post20210125)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorboard~=2.4->tensorflow==2.4) (0.4.3)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorboard~=2.4->tensorflow==2.4) (1.0.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorboard~=2.4->tensorflow==2.4) (2.25.1)
Requirement already satisfied: markdown>=2.6.8 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorboard~=2.4->tensorflow==2.4) (3.3.4)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorboard~=2.4->tensorflow==2.4) (1.8.0)
Requirement already satisfied: google-auth<2,>=1.6.3 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from tensorboard~=2.4->tensorflow==2.4) (1.28.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow==2.4) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow==2.4) (4.7.2)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow==2.4) (4.2.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.4->tensorflow==2.4) (1.3.0)
Requirement already satisfied: importlib-metadata in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from markdown>=2.6.8->tensorboard~=2.4->tensorflow==2.4) (3.7.3)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow==2.4) (0.4.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow==2.4) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow==2.4) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow==2.4) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow==2.4) (4.0.0)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.4->tensorflow==2.4) (3.1.0)
Requirement already satisfied: zipp>=0.5 in c:\users\david2\anacon~1\envs\r-reti~1\lib\site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard~=2.4->tensorflow==2.4) (3.4.1)

Installation complete.

> library(tensorflow)

Restarting R session...

**Comment by jane2710** [comment]
Here is the crash:
> tf$constant("Hellow Tensorflow")
2021-03-25 15:30:36.755691: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-03-25 15:30:36.755691: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-03-25 15:30:39.003820: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-25 15:30:39.004820: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021-03-25 15:30:39.020821: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: Could not retrieve CUDA device attribute (81: UNKNOWN ERROR (1)

**Comment by t-kalinowski** [comment]
I'm closing this since the thread has been idle for a while. If you are still experiencing installation issues, please reopen or file a new issue.
