### ISSUE TITLE
Suggest update to README.md to prevent problems on Linux (and maybe MacOS)

### ISSUE THREAD

**Issue by bokov** [rstudio/tensorflow#456]
According to README.md

https://github.com/rstudio/tensorflow/blob/8f9ddd92d497dcd673ab7d2b9ae4a2acb930ef27/README.md#L17

Not all Linux environments will virtualenv already installed, and the errors one gets when attempting to install tensorflow is obvious in retrospect...

    Error: could not find a Python environment for /usr/bin/python3

I suggest explicitly stating in that part of the READEME.md :

> If you are on a Debian/Ubuntu system, before proceeding please make sure that you have the `python-virtualenv` package installed.

Also if, like me, your first installation attempt did not succeed, you might have a broken virtual environment that is preventing new install attempts from working. It might help to make up a name for a new TF virtual environment and pass that to the `envname` argument, e.g.  `install_tensorflow(envname='MyNewTFEnv')`. This way a fresh environment by that name is created and used.

**Comment by t-kalinowski** [comment]
Hi, as far as I know, the `python3-venv` .deb package is not needed for the installation to succeed, since `install_tensorflow()` defaults to downloading miniconda, which brings along it's own environment management tooling. 

Can you please provide the full output from running `install_tensorflow()`?

**Comment by eddelbuettel** [comment]
FWIW, seconded. Under current Ubuntu, I don't have the virtualenv package installed, prefer my system Python (which I know and trust, no need for miniconda for me) but these days I have to set `RETICULATE_PYTHON=/usr/bin/python3` in my `~/.Renviron`.
