### ISSUE TITLE
How can I allocate GPU memory?

### ISSUE THREAD

**Issue by HONG-genetics** [rstudio/tensorflow#459]
I have tesorflow v2. 

This code is for allocating GPU memory in v1.

`gpu_options <- tf$GPUOptions(per_process_gpu_memory_fraction = 0.3)`
`# gpu_options <- tf$GPUOptions(allow_growth = TRUE)  # <- one or the other`
`config <- tf$ConfigProto(gpu_options = gpu_options)`
`k_set_session(tf$Session(config = config))`

How can I allocate GPU memory in tesorflow v2?

**Comment by dfalbel** [comment]
You can do something like this:

```
library(tensorflow)
gpus <- tf$config$experimental$list_logical_devices("GPU")
lapply(gpus, function(gpu) tf$config$experimental$set_memory_growth(gpu, "GPU"))
```

**Comment by JoonKiH** [comment]
Thanks.
I want to set the limit rate of gpu ram.
such as 'per_process_gpu_memory_fraction = 0.3'.

**Comment by t-kalinowski** [comment]
Hi, the `GPUOptions` callable in your first example is still present in tensorflow 2.0. It just moved to `tf$compat$v1$GPUOptions`, e.g., `tf$compat$v1$GPUOptions(per_process_gpu_memory_fraction = .3)`
