### ISSUE TITLE
Is there some way to install DirectML sollution in R?

### ISSUE THREAD

**Issue by R470R** [rstudio/tensorflow#467]
Hello, thanks a lot for this incredible package, I was enthusiastic about directml solution that was made by microsoft.

I tried to install it with Alternate Versions present in https://tensorflow.rstudio.com/installation/, but the answer was not positive.

Did I commited a mistake or the world is not ready yet ?

Best Regards

Health & Safety

**Comment by t-kalinowski** [comment]
Hi, thanks for filing. Can you please provide the output from running `tensorflow::install_tensorflow()` in R?

**Comment by R470R** [comment]
Hello Mr. @t-kalinowski !

> tensorflow::install_tensorflow()
Collecting package metadata (current_repodata.json): ...working... done

Solving environment: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 4.10.1

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.

Collecting tensorflow==2.4
  Downloading tensorflow-2.4.0-cp37-cp37m-win_amd64.whl (370.7 MB)
Requirement already satisfied: gast==0.3.3 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (0.3.3)
Collecting grpcio~=1.32.0
  Using cached grpcio-1.32.0-cp37-cp37m-win_amd64.whl (2.5 MB)
Collecting tensorboard~=2.4
  Downloading tensorboard-2.5.0-py3-none-any.whl (6.0 MB)
Requirement already satisfied: protobuf>=3.9.2 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (3.15.6)
Requirement already satisfied: keras-preprocessing~=1.1.2 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (1.1.2)
Requirement already satisfied: typing-extensions~=3.7.4 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (3.7.4.3)
Requirement already satisfied: opt-einsum~=3.3.0 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (3.3.0)
Requirement already satisfied: numpy~=1.19.2 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (1.19.2)
Requirement already satisfied: termcolor~=1.1.0 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (1.1.0)
Requirement already satisfied: wheel~=0.35 in c:\users\cunha\appdata\roaming\python\python37\site-packages (from tensorflow==2.4) (0.36.2)
Requirement already satisfied: wrapt~=1.12.1 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (1.12.1)
Requirement already satisfied: h5py~=2.10.0 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (2.10.0)
Requirement already satisfied: google-pasta~=0.2 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (0.2.0)
Requirement already satisfied: absl-py~=0.10 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (0.10.0)
Collecting tensorflow-estimator<2.5.0,>=2.4.0rc0
  Using cached tensorflow_estimator-2.4.0-py2.py3-none-any.whl (462 kB)
Requirement already satisfied: six~=1.15.0 in c:\users\cunha\appdata\roaming\python\python37\site-packages (from tensorflow==2.4) (1.15.0)
Requirement already satisfied: astunparse~=1.6.3 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from tensorflow==2.4) (1.6.3)
Collecting flatbuffers~=1.12.0
  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from tensorboard~=2.4->tensorflow==2.4) (0.4.3)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Downloading tensorboard_data_server-0.6.1-py3-none-any.whl (2.4 kB)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from tensorboard~=2.4->tensorflow==2.4) (1.8.0)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from tensorboard~=2.4->tensorflow==2.4) (52.0.0.post20210125)
Requirement already satisfied: google-auth<2,>=1.6.3 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from tensorboard~=2.4->tensorflow==2.4) (1.28.0)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from tensorboard~=2.4->tensorflow==2.4) (2.25.1)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from tensorboard~=2.4->tensorflow==2.4) (1.0.1)
Requirement already satisfied: markdown>=2.6.8 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from tensorboard~=2.4->tensorflow==2.4) (3.3.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow==2.4) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow==2.4) (4.2.1)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow==2.4) (4.7.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.4->tensorflow==2.4) (1.3.0)
Requirement already satisfied: importlib-metadata in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from markdown>=2.6.8->tensorboard~=2.4->tensorflow==2.4) (3.7.3)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow==2.4) (0.4.8)
Requirement already satisfied: idna<3,>=2.5 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow==2.4) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow==2.4) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow==2.4) (2021.5.30)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow==2.4) (1.26.4)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.4->tensorflow==2.4) (3.1.0)
Requirement already satisfied: zipp>=0.5 in c:\users\cunha\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard~=2.4->tensorflow==2.4) (3.4.1)
Installing collected packages: tensorboard-data-server, grpcio, tensorflow-estimator, tensorboard, flatbuffers, tensorflow
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.36.1
    Uninstalling grpcio-1.36.1:
      Successfully uninstalled grpcio-1.36.1
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.2.0
    Uninstalling tensorflow-estimator-2.2.0:
      Successfully uninstalled tensorflow-estimator-2.2.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.2.2
    Uninstalling tensorboard-2.2.2:
      Successfully uninstalled tensorboard-2.2.2
  WARNING: The script tensorboard.exe is installed in 'C:\Users\cunha\AppData\Local\R-MINI~1\envs\R-RETI~1\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.2.0
    Uninstalling tensorflow-2.2.0:
      Successfully uninstalled tensorflow-2.2.0
  WARNING: The scripts estimator_ckpt_converter.exe, import_pb_to_tensorboard.exe, saved_model_cli.exe, tensorboard.exe, tf_upgrade_v2.exe, tflite_convert.exe, toco.exe and toco_from_protos.exe are installed in 'C:\Users\cunha\AppData\Local\R-MINI~1\envs\R-RETI~1\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed flatbuffers-1.12 grpcio-1.32.0 tensorboard-2.5.0 tensorboard-data-server-0.6.1 tensorflow-2.4.0 tensorflow-estimator-2.4.0
WARNING: You are using pip version 21.0.1; however, version 21.1.2 is available.
You should consider upgrading via the 'C:\Users\cunha\AppData\Local\R-MINI~1\envs\R-RETI~1\python.exe -m pip install --upgrade pip' command.

Installation complete.

Best Regards

**Comment by t-kalinowski** [comment]
@R470R It looks like installation succeeded. What happens when you run:
```R
library(tensorflow)
tf_config()
tf$abs(1)
```

**Comment by R470R** [comment]
Hello Mr @t-kalinowski , very honored with your care. 

The reason why I was focused on directml version was because with it I could run with an AMD gpu 6000 series.

Thank you very much 

Best Regards

**Comment by t-kalinowski** [comment]
Using AMD GPUs with Tensorflow is not officially supported by the Tensorflow maintainers (Google) or us (RStudio). I know there is some ongoing work in this space, you may want to look here: https://rocmdocs.amd.com/en/latest/. Unfortunately, we're unable to provide support for this at this time.

That said, if you can manually configure a python tensorflow installation that uses ROCm, you should be able to point reticulate at it and it should work from R. I've not done this so I'm unsure how difficult it will be.

It sounds like you're able to successfully install and use tensorflow using the CPU from R, so I'm going to close the issue. Please reopen the issue if that's not the case.
