### ISSUE TITLE
R crashes with 'illegal operation' (but not R-Studio) and CPU does support AVX

### ISSUE THREAD

**Issue by Millani** [rstudio/tensorflow#475]
I installed the `tensorflow` package from within R-Studio following these instructions: https://stackoverflow.com/questions/63220597/python-in-r-error-could-not-find-a-python-environment-for-usr-bin-python.

Then if I try any tensorflow command from R but outside R-Studio, nothing happens - whatever tensorflow command I execute keeps hanging (it does not freeze R, it just hangs until I interrupt it with Ctrl+C). But on the contrary, any tensorflow command I try within R-Studio seems to work normally. That patterns applies to **anything**, including something as simple as:

```
library(tensorflow)
tf_version()
```

Now, if I try setting up the Conda environment explicitly first, like in:

```
library(reticulate)
use_condaenv('r-reticulate')
library(tensorflow)
tf_version()
```
Then in R and outside R-Studio I get **exactly** the same crash described 3 years ago in https://github.com/rstudio/tensorflow/issues/228. However, weirdly, everything works perfectly inside R-Studio.

Critical info: my CPU does support AVX. A `lscpu | grep avx` command issued in the UBuntu terminal returns:

> Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d

What is going on and how to solve this? The entire output of the crash goes below:

```
> library(tensorflow)
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tensorflow_2.4.0

loaded via a namespace (and not attached):
 [1] compiler_3.6.3  magrittr_2.0.1  Matrix_1.2-17   whisker_0.4    
 [5] base64enc_0.1-3 rappdirs_0.3.3  Rcpp_1.0.6      reticulate_1.19
 [9] grid_3.6.3      jsonlite_1.7.1  tfruns_1.5.0    lattice_0.20-41
> library(reticulate)
> use_condaenv('r-reticulate')
> library(tensorflow)
> tf_version()

 *** caught illegal operation ***
address 0x7f796676cc48, cause 'illegal operand'

Traceback:
 1: py_module_import(module, convert = convert)
 2: import(module)
 3: doTryCatch(return(expr), name, parentenv, handler)
 4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5: tryCatchList(expr, classes, parentenv, handlers)
 6: tryCatch({    import(module)    TRUE}, error = clear_error_handler(FALSE))
 7: py_module_available("tensorflow")
 8: tf_config()
 9: tf_version()

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 
```

**Comment by t-kalinowski** [comment]
There must be something different between the environment Rstudio runs in and your bash terminal.

Inspect the output of `Sys.getenv()` both in and out of Rstudio and look for differences, paying close attention to 
environment variables PATH, LD_LIBRARY_PATH, and any env variables that start with RETICULATE_ 

My best guess is that outside Rstudio, R is finding a different python installation, or maybe, a different *.so.

**Comment by Millani** [comment]
Thank @t-kalinowski for your reply. I think you were right. There was no variable whose name starts with RETICULATE and LD_LIBRARY_PATH is identical, but indeed PATH had a relevant difference within terminal R and within R-Studio.

Namely, the PATH variable from within terminal R had the following extra paths:

`home/millani/.pyenv/shims:/home/millani/.pyenv/bin:/home/millani/.pyenv/shims:/home/millani/.pyenv/bin`

Which were being inserted in the `~/.bashrc` file (hence why R-Studio's PATH variable did not get those extra paths).

Once those were removed from the `~/.bashrc` file, the lines:

```
library(tensorflow)
tf_version()
```

Do not crash R anymore. However, now `install_tensorflow()` leads to an error:

> Error: could not find a Python environment for /usr/bin/python3

If run after first calling (following [these steps](https://stackoverflow.com/a/63440092/6389471), of course):

```
library(reticulate)
use_condaenv('r-reticulate')
```

Then the error becomes:

> Error in python_config(python_version, required_module, python_versions) : 
>   Error 139 occurred running /opt/anaconda3/envs/r-reticulate/bin/python

**Comment by t-kalinowski** [comment]
Glad you were able to narrow it down!

Did you manually create the 'r-reticulate' conda environment? It looks like you have a self-installed conda installation in a non-default location (and also a by default, not user-writable location), maybe there is something funky going with where conda is trying to create environments (maybe something in ~/.condarc or something similar?). Also, there are some issues with the current version of conda failing if you're running it as a user that doesn't have write permissions to the base conda installation. 

You'll have the most reliable experience if you let reticulate manage it's own python conda installation: 
```r
reticulate::install_miniconda()
keras::install_keras()
```
The reticulate installed miniconda would be isolated from all the other python installations on your system, and should "just work".

**Comment by Millani** [comment]
Excellent, I removed the manually created environment (and all its contents), then followed your suggestion, @t-kalinowski. It worked for successfully installing both `tensorflow` and `keras`. The one thing still not working is that when I try `mnist <- dataset_mnist()` to test whether `keras` functionality is as expected, both R and R-Studio display "Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz" but then hang, never finish the download.

**Comment by t-kalinowski** [comment]
That sounds more like a network connection issue. 
When you go outside R / R studio, what happens when you try to load the dataset from python:
e.g:
```
~/.local/share/r-miniconda/envs/r-reticulate/bin/python -c 'import tensorflow as tf; print(tf.keras.datasets.mnist.load_data())'
```

**Comment by Millani** [comment]
It could have been. I just re-installed everything from scratch and worked. Meaning, the saga is over! Many thanks, @t-kalinowski for your invaluable help here.
