### ISSUE TITLE
Import/Installation Error

### ISSUE THREAD

**Issue by alawami** [rstudio/tensorflow#48]
I installed the package at first with no issues, but when I tried loading it I get the following error:

`ImportError: No module named tensorflow
If you have not yet installed TensorFlow, see https://www.tensorflow.org/get_started/
Configuration:
 python:    /usr/bin/python
 libpython: /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so
 numpy:     /usr/lib/python2.7/dist-packages/numpy/core/include`

I am using python version 3.4, I don't need to change the python path, but I do need to change the paths to libpython and numpy. So I tried to reinstall using both:

`Sys.setenv(TENSORFLOW_PYTHON="/usr/local/bin/python")
devtools::install_github("rstudio/tensorflow")`

and 

`Sys.setenv(TENSORFLOW_PYTHON=3)
devtools::install_github("rstudio/tensorflow")`

but I get the following error:

`Downloading GitHub repo rstudio/tensorflow@master
from URL https://api.github.com/repos/rstudio/tensorflow/zipball/master
Installing tensorflow
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpPMSwtK/devtools28f3420d7dd8/rstudio-tensorflow-4c806d0' --library='/home/ahmedose/R/x86_64-pc-linux-gnu-library/3.3' --install-tests `

`installing *source* package ‘tensorflow’ ...
Using python binary at 3.4
Using python version 3
Could not locate 
ERROR: configuration failed for package ‘tensorflow’`

`removing ‘/home/ahmedose/R/x86_64-pc-linux-gnu-library/3.3/tensorflow’`

`restoring previous ‘/home/ahmedose/R/x86_64-pc-linux-gnu-library/3.3/tensorflow’
Error: Command failed (1)`

**Comment by jjallaire** [comment]
We've made some recent changes to our installation and bindings to python/tensorflow which should have resolved this issue.
