### ISSUE TITLE
Tensorflow now requires R >= 3.5 due to `tfautograph`

### ISSUE THREAD

**Issue by colearendt** [rstudio/tensorflow#484]
https://github.com/t-kalinowski/tfautograph/blob/47d1d8155e2128192e5adbba67588bd6d5e72195/DESCRIPTION#L9

**Comment by t-kalinowski** [comment]
Thank you for reporting, this is be fixed now.
Actions taken: 
To make `R CMD install tensorflow` succeed: New release of tfautograph (0.3.2)
To make `R CMD check` succeed: New release of keras (2.6.1)
Also, expanded github actions workflows in keras and tensorflow repos to also test on R 3.4, 3.5. 
Please note, the keras minimum R version was bumped to R 3.4. The minimum R version for tensorflow will be bumped to 3.4 soon as well.

**Comment by t-kalinowski** [comment]
@colearendt I can restore R-3.3 compat to Keras if that is useful, please let me know: https://github.com/rstudio/keras/actions/runs/1304567227
