### ISSUE TITLE
package installs default tensorflow into conda env with existing tensorflow

### ISSUE THREAD

**Issue by bryorsnef** [rstudio/tensorflow#488]
I'm having an installation issue where whenever I set up a conda environment with tensorflow-gpu==2.5, force R to use that environment with use_condaenv("myenv", required = T), and then run a tensorflow function, instead of using tensorflow-gpu the default 2.6 tensorflow gets installed. I don't see any way to disable that behaviour. I've also tried installing with install_tensorflow and specifying version == "gpu" but I get the default 2.6 version.

**Comment by bryorsnef** [comment]
Not in Rstudio, working from command line on a cluster.

**Comment by t-kalinowski** [comment]
Can you please post the full console output from the installation commands? Nothing that you posted above seems out of place.
For debugging purposes, can you please reinstall the latest release version of the tensorflow R package or the dev version?
Also, can you please repeat the above, but this time launch R without first activating the conda env?
