### ISSUE TITLE
Tensorflow not installing properly on Windows

### ISSUE THREAD

**Issue by gdrod12** [rstudio/tensorflow#497]
I have been trying to install tensorflow in rstudio and it has not been cooperating. Keep in mind I have very little experience in this specific area so I might be making a really simple mistake. Here is my code:
install.packages("keras", type="source")
library(reticulate)
keras::install_keras()

and here is the output:
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/tensorflow/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/tensorflow/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/tensorflow/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/tensorflow/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/tensorflow/
Could not fetch URL https://pypi.org/simple/tensorflow/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/tensorflow/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement tensorflow==2.7.* (from versions: none)
ERROR: No matching distribution found for tensorflow==2.7.*
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
Error: Error installing package(s): "\"tensorflow==2.7.*\"", "\"tensorflow-hub\"", "\"scipy\"", "\"requests\"", "\"Pillow\"", "\"h5py\"", "\"pandas\""
In addition: Warning message:
In read_python_versions_from_registry("HCU", key = "PythonCore") :
  Unexpected format for PythonCore version: 3.10

Any help would be very much appreciated.

**Comment by t-kalinowski** [comment]
Hi, this issue was fixed in the dev version of reticulate, should be on CRAN soon. In the interim you can try:
```R
# install dev version of reticulate + keras
remotes::install_github("rstudio/reticulate")
remotes::install_github("rstudio/tensorflow")
remotes::install_github("rstudio/keras")

# if you want a fresh python installation:
reticulate::miniconda_uninstall() 
reticulate::install_miniconda()

keras::install_keras()

**Comment by gdrod12** [comment]
This worked perfectly. Thanks.
