### ISSUE TITLE
Binary installation is only available for 64-bit platforms.

### ISSUE THREAD

**Issue by avrenli2** [rstudio/tensorflow#507]
Hello,
I have the 64-bit version of R installed and my operating system is 64-bit, too.
When I try to run  install_tensorflow()  , I still get the following error message:

**Binary installation is only available for 64-bit platforms.**

I was able to run cmd and pip install tensorflow, but that is all I could do.  I do not know how to call it from R.
Is there a way to create an environment and call it from R instead of running install_tensorflow() ? I am not familiar with Python and I would be grateful for any help.

**Comment by avrenli2** [comment]
Thank you so much for the quick response.
**.Machine$sizeof.pointer == 8.**  returns **TRUE** , so my R is indeed 64 bit.
I installed **tensorflow** with **pip install tensorflow**  using window's cmd.
Could you help me figure out the exact path to **tensorflow** so that I can call it on RStudio and then run **keras_model_sequential()** on RStudio?
Thank you so much for being kind and helpful,

**Comment by t-kalinowski** [comment]
On Windows, you can go to that same cmd prompt and type `where python` to get the file path to Python. 
This assumes that the `pip` found on your PATH path corresponds to the `python` that's on your PATH. If not, then you might need to investigate manually, starting at `where pip`
