### ISSUE TITLE
Error installing tensorflow on a Mac (macOS 10.15)

### ISSUE THREAD

**Issue by avrenli2** [rstudio/tensorflow#509]
Hello,
I am trying to run install_tensorflow() on a Mac computer.  Its operating system is macOS 10.15
I tried several clean installations but keep getting the following error message.  I would be grateful for any help.   Thank you,

![Screen Shot 2022-02-09 at 12 37 53 PM](https://user-images.githubusercontent.com/62804852/153735633-229532ca-268e-4ee9-a080-4c94c6fc7fd5.png)

**Comment by avrenli2** [comment]
Mr. Kalinoswki, this worked on my student's MacBook.
We are extremely grateful to you for your kindness.
I would like to send you a little gift to thank you.  Could you email your shipping information?

**Comment by t-kalinowski** [comment]
Thank you! That's very generous, but no gifts are necessary. I am happy to help. 😄

**Comment by avrenli2** [comment]
Hello Thomas
I would still like to send you a humble gift.
I am teaching tensorflow and I had multiple students who had issues
installing it.
I could not have resolved it without your prompt and generous help.
Let me know your shipping address and thank you so much again for being so
kind and generous,
