### ISSUE TITLE
loading error in Mac OS

### ISSUE THREAD

**Issue by wenbostar** [rstudio/tensorflow#51]
Hi, 
I used pip to install tensorflow and the R package was also installed as following:
`devtools::install_github("rstudio/tensorflow")
`

When I ran the following lines of code:
`library(tensorflow);
sess = tf$Session()
`
An error message was occurred:
错误: 不适用于非函数

What's the problem?
Best regards!
Bo

**Comment by jjallaire** [comment]
We've made some recent changes to installation and how we bind to tensorflow which should have resolved this issue.
