### ISSUE TITLE
Installation problems 

### ISSUE THREAD

**Issue by Allisterh** [rstudio/tensorflow#510]
I hope this an issue that easily resolved. I have been trying to get TensorFlow and keras to work on my machine for weeks now (windows 11).  I can install both packages easily (btw I have anaconda 4.10.3 and R version 4.1.2 installed). However, whenever I close R and reopen it load the packages and try to use them I get this message:

Error: Valid installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\Users\Alister\anaconda3\python.exe

Python exception encountered:
 ModuleNotFoundError: No module named 'tensorflow'

Detailed traceback:
  File "C:\Users\Alister\Dropbox\PC (2)\Documents\R\win-library\4.1\reticulate\python\rpytools\loader.py", line 39, in _import_hook
    module = _import(

You can install TensorFlow using the install_tensorflow() function.

Please can someone tell me what is happening here is this a reticulate problem or tensorflow problem. Like I said I successfully installed TensorFlow and created a an environment in Anaconda but for the life of me it just wont work.

**Comment by t-kalinowski** [comment]
Have you run `tensorflow::install_tensorflow()` ?

**Comment by Allisterh** [comment]
This is my exact install tensorflow installation command. 

install_tensorflow(method = "conda", 
  version  = "default", envname  = "py_tf", 
  conda_python_version = "3.9", 
  extra_packages = c("matplotlib", "numpy"))

**Comment by t-kalinowski** [comment]
Many installation issues are resolved by running the following in a **fresh R session** (you can restart R in Rstudio with Ctrl+Shift+F10) :
```R
# install the development version of packages, in case the
# issue is already fixed but not on CRAN yet.
install.packages("remotes")
remotes::install_github(sprintf("rstudio/%s", c("reticulate", "tensorflow", "keras")))
reticulate::miniconda_uninstall() # start with a blank slate
reticulate::install_miniconda()
keras::install_keras()
```

Test to see if installation was successful.
```R
tensorflow::as_tensor("Hello World")
```

If the above snippet succeeded and you saw something like `tf.Tensor(b'Hello World', shape=(), dtype=string)`, then :tada:, you've successfully installed Tensorflow.

If the above installation failed, please gather some diagnostic info:
```R
reticulate::py_config()
tensorflow::tf_config()
reticulate::import("tensorflow")
reticulate::py_last_error()
sessionInfo()
```

Please copy and paste the FULL OUTPUT of running all three snippets, and be sure to enclose the output lines with three backticks (```) for monospace formatting.

**Comment by Allisterh** [comment]
Thanks so much [it worked like a charm. However, I am still puzzled why the conda version of install kept failing. Nonetheless thanks o much for your kind assistance, really appreciated.

**Comment by shenoyvarun86** [comment]
Hi , I tried the steps you mentioned but it didn't work. 

 ``` > # install the development version of packages, in case the
> # issue is already fixed but not on CRAN yet.
> install.packages("remotes")
Error in install.packages : Updating loaded packages

Restarting R session...

sh: line 1: 14581 Abort trap: 6           '/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5' -E -c 'import platform; print(platform.python_version())' 2>&1
sh: line 1: 14587 Abort trap: 6           '/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5' -E -c 'import sys; print(sys.version)' 2>&1
> install.packages("remotes")
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/remotes_2.4.2.1.tgz'
Content type 'application/x-gzip' length 397070 bytes (387 KB)
==================================================
downloaded 387 KB


The downloaded binary packages are in
	/var/folders/xh/mgv0yc2x2zsbd3pg32bg3q4r0000gn/T//Rtmp1yuin0/downloaded_packages
> remotes::install_github(sprintf("rstudio/%s", c("reticulate", "tensorflow", "keras")))
Skipping install of 'reticulate' from a github remote, the SHA1 (5d0a9a52) has not changed since last install.
  Use `force = TRUE` to force installation
Skipping install of 'tensorflow' from a github remote, the SHA1 (eeb1e66b) has not changed since last install.
  Use `force = TRUE` to force installation
Skipping install of 'keras' from a github remote, the SHA1 (51e7d770) has not changed since last install.
  Use `force = TRUE` to force installation
> 
> reticulate::miniconda_uninstall() # start with a blank slate
> 
> reticulate::install_miniconda()
* Installing Miniconda -- please wait a moment ...
* Downloading 'https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh' ...
trying URL 'https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh'
Content type 'application/x-sh' length 89407592 bytes (85.3 MB)
==================================================
downloaded 85.3 MB

PREFIX=/Users/varun/Library/r-miniconda
Unpacking payload ...
                                                                                                                 
Installing base environment...


Downloading and Extracting Packages


Downloading and Extracting Packages

Preparing transaction: ...working... done
Executing transaction: ...working... 
done
installation finished.
+ /Users/varun/Library/r-miniconda/bin/conda update --yes --name base conda
Channels:
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/varun/Library/r-miniconda

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2023.11.17         |  py311hecd8cb5_0         160 KB
    ------------------------------------------------------------
                                           Total:         160 KB

The following packages will be UPDATED:

  certifi                         2023.7.22-py311hecd8cb5_0 --> 2023.11.17-py311hecd8cb5_0 



Downloading and Extracting Packages: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+ /Users/varun/Library/r-miniconda/bin/conda 'create' '--yes' '--name' 'r-reticulate' 'python=3.9' 'numpy' '--quiet' '-c' 'conda-forge'
Channels:
 - conda-forge
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/varun/Library/r-miniconda/envs/r-reticulate

  added / updated specs:
    - numpy
    - python=3.9


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bzip2-1.0.8                |       h10d778d_5         125 KB  conda-forge
    ca-certificates-2023.11.17 |       h8857fd0_0         151 KB  conda-forge
    libblas-3.9.0              |20_osx64_openblas          14 KB  conda-forge
    libcblas-3.9.0             |20_osx64_openblas          14 KB  conda-forge
    libcxx-16.0.6              |       hd57cbcb_0         1.1 MB  conda-forge
    libffi-3.4.2               |       h0d85af4_5          50 KB  conda-forge
    libgfortran-5.0.0          |13_2_0_h97931a8_1         107 KB  conda-forge
    libgfortran5-13.2.0        |       h2873a65_1         1.5 MB  conda-forge
    liblapack-3.9.0            |20_osx64_openblas          14 KB  conda-forge
    libopenblas-0.3.25         |openmp_hfef2a42_0         5.7 MB  conda-forge
    libsqlite-3.44.2           |       h92b6c6a_0         870 KB  conda-forge
    libzlib-1.2.13             |       h8a1eda9_5          58 KB  conda-forge
    llvm-openmp-17.0.5         |       hb6ac08f_0         293 KB  conda-forge
    ncurses-6.4                |       h93d8f39_2         803 KB  conda-forge
    numpy-1.26.2               |   py39h14c6d2e_0         6.0 MB  conda-forge
    openssl-3.2.0              |       hd75f5a5_0         2.4 MB  conda-forge
    pip-23.3.1                 |     pyhd8ed1ab_0         1.3 MB  conda-forge
    python-3.9.18              |h07e1443_0_cpython        10.8 MB  conda-forge
    python_abi-3.9             |           4_cp39           6 KB  conda-forge
    readline-8.2               |       h9e318b2_1         250 KB  conda-forge
    setuptools-68.2.2          |     pyhd8ed1ab_0         454 KB  conda-forge
    tk-8.6.13                  |       h1abcd95_1         3.1 MB  conda-forge
    tzdata-2023c               |       h71feb2d_0         115 KB  conda-forge
    wheel-0.41.3               |     pyhd8ed1ab_0          57 KB  conda-forge
    xz-5.2.6                   |       h775f41a_0         233 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        35.6 MB

The following NEW packages will be INSTALLED:

  bzip2              conda-forge/osx-64::bzip2-1.0.8-h10d778d_5 
  ca-certificates    conda-forge/osx-64::ca-certificates-2023.11.17-h8857fd0_0 
  libblas            conda-forge/osx-64::libblas-3.9.0-20_osx64_openblas 
  libcblas           conda-forge/osx-64::libcblas-3.9.0-20_osx64_openblas 
  libcxx             conda-forge/osx-64::libcxx-16.0.6-hd57cbcb_0 
  libffi             conda-forge/osx-64::libffi-3.4.2-h0d85af4_5 
  libgfortran        conda-forge/osx-64::libgfortran-5.0.0-13_2_0_h97931a8_1 
  libgfortran5       conda-forge/osx-64::libgfortran5-13.2.0-h2873a65_1 
  liblapack          conda-forge/osx-64::liblapack-3.9.0-20_osx64_openblas 
  libopenblas        conda-forge/osx-64::libopenblas-0.3.25-openmp_hfef2a42_0 
  libsqlite          conda-forge/osx-64::libsqlite-3.44.2-h92b6c6a_0 
  libzlib            conda-forge/osx-64::libzlib-1.2.13-h8a1eda9_5 
  llvm-openmp        conda-forge/osx-64::llvm-openmp-17.0.5-hb6ac08f_0 
  ncurses            conda-forge/osx-64::ncurses-6.4-h93d8f39_2 
  numpy              conda-forge/osx-64::numpy-1.26.2-py39h14c6d2e_0 
  openssl            conda-forge/osx-64::openssl-3.2.0-hd75f5a5_0 
  pip                conda-forge/noarch::pip-23.3.1-pyhd8ed1ab_0 
  python             conda-forge/osx-64::python-3.9.18-h07e1443_0_cpython 
  python_abi         conda-forge/osx-64::python_abi-3.9-4_cp39 
  readline           conda-forge/osx-64::readline-8.2-h9e318b2_1 
  setuptools         conda-forge/noarch::setuptools-68.2.2-pyhd8ed1ab_0 
  tk                 conda-forge/osx-64::tk-8.6.13-h1abcd95_1 
  tzdata             conda-forge/noarch::tzdata-2023c-h71feb2d_0 
  wheel              conda-forge/noarch::wheel-0.41.3-pyhd8ed1ab_0 
  xz                 conda-forge/osx-64::xz-5.2.6-h775f41a_0 


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
* Miniconda has been successfully installed at "~/Library/r-miniconda".
[1] "/Users/varun/Library/r-miniconda"
> keras::install_keras()
sh: line 1: 14853 Abort trap: 6           '/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5' -EV 2>&1
sh: line 1: 14855 Abort trap: 6           '/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5' -EV 2>&1
+ /Users/varun/Library/r-miniconda/bin/conda 'remove' '--yes' '--name' 'r-tensorflow' '--all'
+ . /Users/varun/Library/r-miniconda/bin/activate
+ conda activate 'r-tensorflow'

EnvironmentNameNotFound: Could not find conda environment: r-tensorflow
You can list all discoverable environments with `conda info --envs`.


+ '/Users/varun/opt/anaconda3/envs/r-tensorflow/bin/python' -m pip install --upgrade --no-user 'tensorflow==2.13.*' tensorflow-hub tensorflow-datasets scipy requests Pillow h5py pandas pydot
ERROR: Could not find a version that satisfies the requirement tensorflow==2.13.* (from versions: none)
ERROR: No matching distribution found for tensorflow==2.13.*
Error: Error installing package(s): "'tensorflow==2.13.*'", "tensorflow-hub", "tensorflow-datasets", "scipy", "requests", "Pillow", "h5py", "pandas", "pydot"
> tensorflow::as_tensor("Hello World")
Error: Valid installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /Users/varun/opt/anaconda3/envs/r-tensorflow/bin/python3.12

Python exception encountered:
 Traceback (most recent call last):
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'tensorflow'


You can install TensorFlow using the install_tensorflow() function. 


> tensorflow::as_tensor("Hello World")
Error: Valid installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /Users/varun/opt/anaconda3/envs/r-tensorflow/bin/python3.12

Python exception encountered:
 Traceback (most recent call last):
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'tensorflow'


You can install TensorFlow using the install_tensorflow() function.

The diagnostic is as follows:

```
 reticulate::import("tensorflow")
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'tensorflow'
Run `reticulate::py_last_error()` for details.
> reticulate::py_config()
python:         /Users/varun/opt/anaconda3/envs/r-tensorflow/bin/python
libpython:      /Users/varun/opt/anaconda3/envs/r-tensorflow/lib/libpython3.12.dylib
pythonhome:     /Users/varun/opt/anaconda3/envs/r-tensorflow:/Users/varun/opt/anaconda3/envs/r-tensorflow
version:        3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:38) [Clang 15.0.7 ]
numpy:           [NOT FOUND]
tensorflow:     [NOT FOUND]

tensorflow::tf_config()
Valid installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /Users/varun/opt/anaconda3/envs/r-tensorflow/bin/python3.12

Python exception encountered:
 Traceback (most recent call last):
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'tensorflow'


You can install TensorFlow using the install_tensorflow() function.
 
 reticulate::import("tensorflow")
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'tensorflow'
Run `reticulate::py_last_error()` for details.

 reticulate::py_last_error()

── Python Exception Message ──────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'tensorflow'

── R Traceback ───────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─reticulate::import("tensorflow")
 2.   └─reticulate:::py_module_import(module, convert = convert)

sessionInfo()
R version 4.3.2 (2023-10-31)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.1.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Los_Angeles
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] crayon_1.5.2           cli_3.6.1              rlang_1.1.2           
 [4] zeallot_0.1.0          processx_3.8.2         png_0.1-8             
 [7] generics_0.1.3         jsonlite_1.8.7         prettyunits_1.2.0     
[10] keras_2.13.0.9000      rprojroot_2.0.4        pkgbuild_1.4.2        
[13] ps_1.7.5               rappdirs_0.3.3         grid_4.3.2            
[16] tfruns_1.5.1           base64enc_0.1-3        lifecycle_1.0.4       
[19] whisker_0.4.1          compiler_4.3.2         Rcpp_1.0.11           
[22] here_1.0.1             rstudioapi_0.15.0      lattice_0.21-9        
[25] R6_2.5.1               reticulate_1.34.0.9000 curl_5.1.0            
[28] callr_3.7.3            tensorflow_2.14.0.9000 magrittr_2.0.3        
[31] Matrix_1.6-1.1         withr_2.5.2            tools_4.3.2           
[34] desc_1.4.2             remotes_2.4.2.1       
>

**Comment by vmandela99** [comment]
@t-kalinowski hope you are doing great.

Thanks for this solution. I got stuck in the last step.

this error:

`> tensorflow::install_tensorflow()
+ "C:/Users/moubi/AppData/Local/r-miniconda/condabin/conda.bat" "remove" "--yes" "--name" "r-tensorflow" "--all"

Remove all packages in environment C:\Users\moubi\AppData\Local\R-MINI~1\envs\r-tensorflow:


## Package Plan ##

  environment location: C:\Users\moubi\AppData\Local\R-MINI~1\envs\r-tensorflow


The following packages will be REMOVED:

  bzip2-1.0.8-hcfcfb64_5
  ca-certificates-2023.11.17-h56e8100_0
  libexpat-2.5.0-h63175ca_1
  libffi-3.4.2-h8ffe710_5
  libsqlite-3.44.2-hcfcfb64_0
  libzlib-1.2.13-hcfcfb64_5
  openssl-3.2.0-hcfcfb64_1
  pip-23.3.2-pyhd8ed1ab_0
  python-3.12.1-h2628c8c_1_cpython
  setuptools-69.0.3-pyhd8ed1ab_0
  tk-8.6.13-h5226925_1
  tzdata-2023d-h0c530f3_0
  ucrt-10.0.22621.0-h57928b3_0
  vc-14.3-hcf57466_18
  vc14_runtime-14.38.33130-h82b7239_18
  vs2015_runtime-14.38.33130-hcb4865c_18
  wheel-0.42.0-pyhd8ed1ab_0
  xz-5.2.6-h8d14728_0


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+ "C:/Users/moubi/AppData/Local/r-miniconda/condabin/conda.bat" "create" "--yes" "--name" "r-tensorflow" "python" "--quiet" "-c" "conda-forge"
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\moubi\AppData\Local\R-MINI~1\envs\r-tensorflow

  added / updated specs:
    - python


The following NEW packages will be INSTALLED:

  bzip2              conda-forge/win-64::bzip2-1.0.8-hcfcfb64_5 
  ca-certificates    conda-forge/win-64::ca-certificates-2023.11.17-h56e8100_0 
  libexpat           conda-forge/win-64::libexpat-2.5.0-h63175ca_1 
  libffi             conda-forge/win-64::libffi-3.4.2-h8ffe710_5 
  libsqlite          conda-forge/win-64::libsqlite-3.44.2-hcfcfb64_0 
  libzlib            conda-forge/win-64::libzlib-1.2.13-hcfcfb64_5 
  openssl            conda-forge/win-64::openssl-3.2.0-hcfcfb64_1 
  pip                conda-forge/noarch::pip-23.3.2-pyhd8ed1ab_0 
  python             conda-forge/win-64::python-3.12.1-h2628c8c_1_cpython 
  setuptools         conda-forge/noarch::setuptools-69.0.3-pyhd8ed1ab_0 
  tk                 conda-forge/win-64::tk-8.6.13-h5226925_1 
  tzdata             conda-forge/noarch::tzdata-2023d-h0c530f3_0 
  ucrt               conda-forge/win-64::ucrt-10.0.22621.0-h57928b3_0 
  vc                 conda-forge/win-64::vc-14.3-hcf57466_18 
  vc14_runtime       conda-forge/win-64::vc14_runtime-14.38.33130-h82b7239_18 
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.38.33130-hcb4865c_18 
  wheel              conda-forge/noarch::wheel-0.42.0-pyhd8ed1ab_0 
  xz                 conda-forge/win-64::xz-5.2.6-h8d14728_0 


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

C:\Users\moubi\Documents\s.sudan_conflict_vs_soghum_yield\new_project>CALL "C:\Users\moubi\AppData\Local\r-miniconda\condabin\activate.bat" "r-tensorflow" 

C:\Users\moubi\Documents\s.sudan_conflict_vs_soghum_yield\new_project>conda.bat activate "r-tensorflow" 

(r-tensorflow) C:\Users\moubi\Documents\s.sudan_conflict_vs_soghum_yield\new_project>"C:\Users\moubi\AppData\Local\r-miniconda\envs\r-tensorflow/python.exe" -m pip install --upgrade --no-user "tensorflow==2.14.*" 
ERROR: Could not find a version that satisfies the requirement tensorflow==2.14.* (from versions: none)
ERROR: No matching distribution found for tensorflow==2.14.*
Error: Error installing package(s): "\"tensorflow==2.14.*\""
In addition: Warning message:
In shell(fi, intern = intern) :
  'C:\Users\moubi\AppData\Local\Temp\Rtmp0mton7\file23e8fc23aca.bat' execution failed with error code 1`

**Comment by t-kalinowski** [comment]
Hi @Allisterh We no longer recommend using miniconda as the default installation path for TensorFlow.

We recommend installing Python normally, either from www.python.org, or by running `reticulate::install_python()`, and then running `install_tensorflow()`.

E.g., this should work:

```r
reticulate::install_python()
keras::install_keras()
```

**Comment by Allisterh** [comment]
> Hi @Allisterh We no longer recommend using miniconda as the default installation path for TensorFlow.
> 
> We recommend installing Python normally, either from [www.python.org](http://www.python.org), or by running `reticulate::install_python()`, and then running `install_tensorflow()`.
> 
> E.g., this should work:
> 
> ```r
> reticulate::install_python()
> keras::install_keras()
> ```

Does it matter which version of Python you install?

**Comment by t-kalinowski** [comment]
Being on the latest version is generally not advisable, ~2 minor versions behind the current Python minor release version is generally the sweet spot for deep learning packages. (3.9.* or 3.10.* today). The default argument to `install_python()` is `"3.9:latest"` today, and is generally incremented in new releases when appropriate.
