### ISSUE TITLE
python3 error in  ‘Py_InitModule’ 

### ISSUE THREAD

**Issue by ivokwee** [rstudio/tensorflow#52]
I tried to install  your tensorflow package with python 3 (Ubuntu xenial, R 3.2.3) and got some compile error in Py_InitModule. It seems this function is deprecated in Python 3.

> Sys.setenv(TENSORFLOW_PYTHON_VERSION = 3)
> devtools::install_github("rstudio/tensorflow")

`g++ -std=c++11 -I/usr/share/R/include -DNDEBUG -I/usr/include/python3.5m -I/usr/include/python3.5m -I/usr/local/lib/python3.5/dist-packages/numpy/core/include -D PYTHONLIBFILE=libpython3.5.so  -I"/home/kwee/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c python.cpp -o python.o
python.cpp: In function ‘void py_initialize(const string&)’:
python.cpp:896:40: error: ‘Py_InitModule’ was not declared in this scope
   Py_InitModule("tfcall", TFCallMethods);`

**Comment by jjallaire** [comment]
Thanks for reporting! Fixed here: https://github.com/rstudio/tensorflow/commit/f3f649623cef7666d9d9b7dc3854a61bef681c50
