### ISSUE TITLE
some generics functions not exported

### ISSUE THREAD

**Issue by mohamed-180** [rstudio/tensorflow#520]
for e.g:
t , mean , range not exported .
to reproduce the issue
```
library(tensorflow)
x <- tf$constant(matrix(1:6, nrow = 2), dtype = tf$float32)
t(x)
```
getting :
`Error in t.default(x) : argument is not a matrix`

**Comment by t-kalinowski** [comment]
I just tried with the development version of tensorflow and this worked. Are you sure your installation was successful?
```
remotes::install_github("rstudio/tensorflow", force=TRUE)
```

**Comment by mohamed-180** [comment]
Thanks,
just updated and every thing fine.
