### ISSUE TITLE
Unable to execute Tutorials - Advanced Quickstart

### ISSUE THREAD

**Issue by jonathannathanaus** [rstudio/tensorflow#526]
Hi All, 

I am currently going through the [Advanced quick start tutorial ](https://tensorflow.rstudio.com/tutorials/advanced/). 

However, I cannot train the model due to numerous issues surrounding `tf_function`.  
 
```
# training loop function
training_loop <- tf_function(autograph( function(train_ds, test_ds) {

  for (b1 in train_ds) {
    train_step(b1$x, b1$y)
  }

  for (b2 in test_ds) {
    test_step(b2$x, b2$y)
  }

  tf$print("Acc", train_accuracy$result(), "Test Acc", test_accuracy$result())

  train_loss$reset_states()
  train_accuracy$reset_states()
  test_loss$reset_states()
  test_accuracy$reset_states()

}))
```

The first issue I get when running the code as is from the tutorial is:

```
Error in tf_function(autograph(function(train_ds, test_ds) { : 
  could not find function "tf_function"
```

I am able to solve this by either adding `library(tensorflow)` or `tensorflow::tf_function`. However, this leads me to my next issue. By adding the library, I now get a  fatal error for R.   see below. 

![image](https://user-images.githubusercontent.com/56504347/162608192-5462d2b7-9622-4df4-a96d-6f401958d080.png)

As a reference, my version of tf and python are: 

```
>     tf_config()
TensorFlow v2.9.0-dev20220312 (C:\Users\JONO-D~1\CONDA~1\envs\R-RETI~1\lib\site-packages\tensorflow)
Python v3.10 (C:/Users/Jono - Desktop/.conda/envs/r-reticulate/python.exe)
```

**Comment by t-kalinowski** [comment]
Hi, Thanks for filing. It looks like you're running a nightly build of Tensorflow, which is intended only for testing purposes. Can you please install the latest release version?

You can install the latest TF release version by running this at the R console of a fresh R session:

```r
install.packages("remotes")
remotes::install_github(sprintf("rstudio/%s", c("reticulate", "tensorflow", "keras")))
reticulate::miniconda_uninstall() # start with a blank slate
reticulate::install_miniconda()
keras::install_keras()
```

**Comment by jonathannathanaus** [comment]
Hi @t-kalinowski , 

No, thankyou for spotting that. 

```
> library(tensorflow)
> tf_config()
TensorFlow v2.8.0 (C:\PROGRA~3\ANACON~1\envs\R-RETI~1\lib\site-packages\tensorflow)
Python v3.10 (C:/ProgramData/Anaconda3/envs/r-reticulate/python.exe)
```

However, after fixing the nightly issue, I am still unable to run the code.  

Running the code as is, I am still getting the same errors as before. 

Could this be related to GPU memory limitations?

```
2022-04-11 19:41:09.463351: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-11 19:41:09.834355: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2824 MB memory:  -> device: 0, name: Quadro K2200, pci bus id: 0000:2b:00.0, compute capability: 5.0

```

As a point of comparison, I can run [Loading image file](https://tensorflow.rstudio.com/tutorials/beginners/load/load_image/) with no problem :(

**Comment by jonathannathanaus** [comment]
Another weak point could be the mineconda installation. 

I had to install it separately due spaces in file path names.

**Comment by jonathannathanaus** [comment]
Hey @t-kalinowski , 

Yes, I encountered exactly the same errors as in my original post sadly. 

```
Error in tf_function(autograph(function(train_ds, test_ds) { : 
  could not find function "tf_function"
> 
> 
> #un our training loop for 5 epochs
> for (epoch in 1:5) {
+   cat("Epoch: ", epoch, " -----------\n")
+   training_loop(train_ds, test_ds)  
+ }
Epoch:  1  -----------
Error in training_loop(train_ds, test_ds) : 
  could not find function "training_loop"

```

Then by adding `library(tensorflow)` , the code runs a bit further and then p;roduces a fatal error. The last bit of output before the crash is: 
```
**Epoch:  1  -----------
2022-04-12 20:08:05.953590: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8302
```
![image](https://user-images.githubusercontent.com/56504347/162936891-287fd761-03f4-4b8a-a9b1-7bf9144d3a44.png)


Are you able to run the tutorial?

**Comment by jonathannathanaus** [comment]
Hi @t-kalinowski , 

I just found the issue. My GPU doesn't look like it was up to spec when trying to run the model. 

I used the suggestion from @Fubukimaru over at [rstudio/keras](https://github.com/rstudio/keras/issues/406) to disable my GPU. 

The model is now running!

`2022-04-13 23:09:35.183338: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected`

`....`

```
Epoch:  1  -----------
Acc 0.9315 Test Acc 0.951
Epoch:  2  -----------
Acc 0.98055 Test Acc 0.9625
Epoch:  3  -----------
Acc 0.9916 Test Acc 0.965
Epoch:  4  -----------
Acc 0.9957 Test Acc 0.965
Epoch:  5  -----------
Acc 0.9974 Test Acc 0.9695
> 
```

Thanks for the help!
