### ISSUE TITLE
ERROR: compilation failed for package 'tensorflow'

### ISSUE THREAD

**Issue by denotepython** [rstudio/tensorflow#53]
c:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-33~1.2/include" -DNDEBUG    -I"C:/Users/rocket/Documents/R/win-library/3.3/Rcpp/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:0:
tensorflow_types.hpp:1:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
make: *** [RcppExports.o] Error 1
Warning: 运行命令'make -f "C:/PROGRA~1/R/R-33~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="tensorflow.dll" OBJECTS="RcppExports.o python.o"'的状态是2

**Comment by jjallaire** [comment]
The package doesn't currently support Windows (tensorflow itself just added
Windows support a week or two ago).

**Comment by denotepython** [comment]
Thank you, waiting for your update! by the way, the newest Rstudio is so wonderful that I want to use R instead of Python!

**Comment by ameshkoff** [comment]
+1 Waiting for Windows support.

**Comment by Streaky75** [comment]
Any update on this?

**Comment by eddelbuettel** [comment]
Sorry to be bearer of bad news here but so far we only stated that 

> The package doesn't currently support Windows

which is not the same as saying "we will add Windows support".  Contributions are welcome, but many of us are wary as Python installations on Windows get complex quickly, and mixing Python and R on Windows is really tricky too.  See how I have not yet even mentioned Tensorflow?

**Comment by jjallaire** [comment]
Yes, we'd very much like to see Windows support as a pull request so that
someone with more experience and expertise with Python on Windows can
oversee the work and inevitable follow up to ensure things work correctly
with the various permutations of Python on Windows.



On Fri, Dec 23, 2016 at 8:23 AM, Dirk Eddelbuettel <notifications@github.com

**Comment by dfalbel** [comment]
Maybe the supported OS's should be stated in the README file :)

**Comment by jjallaire** [comment]
Sorry, when we started there was no such thing as TensorFlow for Windows (this only came to be in the past few weeks). Will update this soon.

**Comment by jjallaire** [comment]
Docs updated

**Comment by jjallaire** [comment]
Work on support for Windows is in progress here: https://github.com/rstudio/tensorflow/tree/feature/windows-version
