### ISSUE TITLE
Save and restore model

### ISSUE THREAD

**Issue by henry-p** [rstudio/tensorflow#54]
Does saving and restoring a model work with R?

I have a model
```
# Parameters
...

# Model
layer1 = tf$add(tf$matmul(x, weight_variable(shape(n_input, n_hidden_1))),
                bias_variable(shape(n_hidden_1)))
layer1 = tf$nn$relu(layer1)

layer2 = tf$add(tf$matmul(layer1, weight_variable(shape(n_hidden_1, n_hidden_2))),
                bias_variable(shape(n_hidden_2)))
layer2 = tf$nn$relu(layer2)

out_layer = tf$matmul(layer2, weight_variable(shape(n_hidden_2, n_classes))) +
            bias_variable(shape(n_classes))

# Initialize graph
sess <- tf$Session()
sess$run(tf$initialize_all_variables())

# Train
...
```

I use `out_layer` to make a prediction like this:
```
pred = sess$run(out_layer, feed_dict = dict(x = test.x))
```

later I save the model like this:

```
saver <- tf$train$Saver()
data_file <- saver$save(sess, paste0(data.dir, "my_model.ckpt"))
```

Then I restart R (to test if restoring works). This leads to the situation that now all tensorflow objects are \<Object with null pointer>.
Now I **try** to restore the model like this:

```
sess = tf$Session()
restorer = tf$train$import_meta_graph(paste0(data.dir, "my_model.ckpt.meta"))
restorer$restore(sess, tf$train$latest_checkpoint(data.dir))
```
...this gives me no errors.
However, `out_layer` (and the other tensorflow-objects) is still an \<Object with null pointer>! Does this mean, restoring the model has not really worked, or do I just have to make an effort to assign `out_layer` the correct pointer again?

**Comment by jjallaire** [comment]
When you restart R all of the tensorflow objects become invalid. This means that you need to re-run whatever parts of your script are required to restore those objects.

**Comment by henry-p** [comment]
@jjallaire Does that mean I cannot restore a neural net that I trained for several hours? I'm asking, because I don't want to retrain the net every time I am restart my computer.

**Comment by jjallaire** [comment]
No, you just need to re-initialize your tensorflow session and objects to
the point where you can call restore on the saved net.

**Comment by henry-p** [comment]
Hm, I just tried it as you suggested (with a smaller network). The variables do indeed get initialized correctly. However, after having restored the network and making a prediction, the prediction values are really bad, as if they were just in the initial random state and *not* in the restored state. Any idea what could've gone wrong?

**Comment by jjallaire** [comment]
This gets into the mechanics of using tensorflow itself which I'm less personally familiar with. @terrytangyuan any ideas?

**Comment by terrytangyuan** [comment]
Sorry for my late reply as I am travelling right now with limited access. Please post usage questions in StackOverflow instead and tag tensorflow. It would be much easier if you use TF.Learn which already provides functionalities to persist model result. Some basic examples can be found here: https://github.com/rstudio/tensorflow/tree/master/inst/examples/tflearn

**Comment by henry-p** [comment]
@terrytangyuan Thank you for your answer.
I don't understand why I should post this on StackOverflow, since this is an R related problem, or am I mistaken?

Unfortunately I cannot really use TF.Learn for the problem I am working on currently.
However, I tried to persist a model with TF.Learn, just out of curiousity.
From the linked examples only the iris_dnn.R file runs through without errors (with warnings though). In addition I tried to make use of the API docs (https://www.tensorflow.org/api_docs/python/contrib.learn/), but couldn't figure out how to do it.

To sum up my understanding of the problem:

After starting a new R session, all pointers to the Tensorflow objects are \<null>. Reconstructing the graph (by just running the code that defines the graph) re-establishes these pointers again. At this point all weights in the network are just set to a random number. One would assume that restoring the model from the files like so:
```
restorer = tf$train$import_meta_graph(paste0(data.dir, "my_model.ckpt.meta"))
restorer$restore(sess, tf$train$latest_checkpoint(data.dir))
```
...would then also re-establish the correct weights that resulted from training the model.
However, this is NOT the case, the weights are still random.
In other words, the restoring of the model has no effect.

**Comment by dfalbel** [comment]
Are you sure you are not running `sess$run(tf$initialize_all_variables())` after restoring the session?

The following works fine for me:

```
library(tensorflow)
w <- tf$Variable(tf$random_normal(shape = shape(10L, 1L)))
init <- tf$global_variables_initializer()
saver <- tf$train$Saver()
sess <- tf$Session()
sess$run(init)
w_r <- sess$run(w)
w_r
save_path <- saver$save(sess, "/tmp/model.ckpt")
```
Then Clean R + Restart R and run:

```
library(tensorflow)
w <- tf$Variable(tf$random_normal(shape = shape(10L, 1L)))
saver <- tf$train$Saver()

sess <- tf$Session()
saver$restore(sess, "/tmp/model.ckpt")
w_r2 <- sess$run(w)
```

With this, I get w_r identical to w_r.

**Comment by henry-p** [comment]
I think you are just using the existing variable `w` and use it to initialize `w_r2` here. So your save&restore code has no effect here? Like the following code would have the same effect (as compared to the second code chunk you posted):
```
library(tensorflow)
w <- tf$Variable(tf$random_normal(shape = shape(10L, 1L)))
w_r2 <- sess$run(w)
```

**Comment by dfalbel** [comment]
`w <- tf$Variable(tf$random_normal(shape = shape(10L, 1L)))` generates 10 random numbers... They would never be equal if it wasn't restored.
