### ISSUE TITLE
Installation issue: an error related to tensorflow version (v1.14.0) 

### ISSUE THREAD

**Issue by HaipengU** [rstudio/tensorflow#545]
Hello,

I got an error message of "save_model_tf only works with TF >= 2.0.0" when calling the function `save_model_tf()`. I checked the tensorflow version using `tf_config()`,  and it returns v.1.14.0. I tried to re-install tensorflow by specifying the version (e.g., 2.8 and 2.9) in the function `install_tensorflow (version = "2.9")`, but it still shows v.1.14.0. It seems like I can not change the version of tensorflow. Any suggestions? Thanks. 

I am using an Apple M1 Pro. 
OUTPUT from `tf_config()`
TensorFlow v1.14.0 ()
Python v3.7 (~/anaconda3/bin/python)

**Comment by t-kalinowski** [comment]
What does `R.version$arch` give you? 
The `macOS` section on this page might be helpful: [tensorflow.rstudio.com/install/local_gpu](https://tensorflow.rstudio.com/install/local_gpu)

**Comment by HaipengU** [comment]
> R.version$arch

Thanks for your reply. The command `R.version$arch` returned "x86_64". Following the link you shared, I installed the Arm build of R and `R.version$arch` returned "aarch64". I then re-install tnsorflow and keras using the following codes, but got an PackagesNotFoundError. I have pasted the codes for installation and the error message below. Any suggestions? 

```
install.packages("tensorflow")
reticulate::virtualenv_create("tensorflowforR", 
                              python = "/Users/myname/anaconda3/bin/python3")

library(tensorflow)
install_tensorflow(envname = "tensorflowforR")
```
Then it returned the following error message: 

```
PackagesNotFoundError: The following packages are not available from current channels:

  - tensorflow-deps

Current channels:

  - https://conda.anaconda.org/apple/osx-64
  - https://conda.anaconda.org/apple/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


Error: one or more Python packages failed to install [error code 1]
```

**Comment by t-kalinowski** [comment]
R (reticulate) is still finding the `x86` build of conda you had installed previously. You can uninstall the x86 conda installation and install an arm build like this:
```r
unlink("~/anaconda3", recursive = TRUE)
reticulate::install_miniconda()
```

(You may need to remove some conda initialization code that anaconda added to your `.zshrc` file as well.)

**Comment by HaipengU** [comment]
> R (reticulate) is still finding the `x86` build of conda you had installed previously. You can uninstall the x86 conda installation and install an arm build like this:
> 
> ```r
> unlink("~/anaconda3", recursive = TRUE)
> reticulate::install_miniconda()
> ```
> 
> (You may need to remove some conda initialization code that anaconda added to your `.zshrc` file as well.)

Hi, after remoted the anaconda3 and install miniconda using these codes, I solved all of my issues. I noticed when I called `conda` in my terminal, it returned command not find (same for `python`). I guess this because `unlink` function removed anaocoda3 from my laptop. Just want to check if it will cause some issues if I re-install anacoda3.

**Comment by t-kalinowski** [comment]
> (You may need to remove some conda initialization code that anaconda added to your .zshrc file as well.)

open up ~.zshrc, (or maybe .zprofile) and look for something that looks like a conda initialization hook, and delete it :)

**Comment by HaipengU** [comment]
> > (You may need to remove some conda initialization code that anaconda added to your .zshrc file as well.)
> 
> open up ~.zshrc, (or maybe .zprofile) and look for something that looks like a conda initialization hook, and delete it :)

Yes, I already did this. Thanks for the prompt reply and help!
