### ISSUE TITLE
Is the Anaconda issue still relevant?

### ISSUE THREAD

**Issue by charlesg** [rstudio/tensorflow#55]
I noticed the configure.ac reject any Anaconda python. The issue linked is from 2015 and I wanted to make sure this was still relevant and that building a new python from scratch was the only solution.

We run on Linux (RHEL 7.2 in this case).

We have been using Anaconda python on all our nodes for years and would like to keep this standard. It greatly facilitates managing a larger scale python deployment.

**Comment by eddelbuettel** [comment]
It is more efficient to continue a discussion within a given (focussed) issue ticket -- in this case a very simple search will tell that that #8, #17 and #28 all aimed at Anaconda.

And to the best of my knowledge the technical issue of its libraries being compiled in a way that makes it hard or difficult for tensorflow to use them has not changed.  So "yes, still relevant".

**Comment by jjallaire** [comment]
Yes, the issue is that Anaconda doesn't want to be dynamically loaded.
Rather, it wants everything to have been built using the Anaconda build
tools rather than the standard R build tools (including those used by CRAN).

On Mon, Dec 19, 2016 at 8:58 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by charlesg** [comment]
Thanks for confirming. Sorry to open a new issue, wasn't sure how to proceed. Will close now.

**Comment by vonjd** [comment]
This is no longer an issue, the documentation was updated too.

See here:
https://github.com/rstudio/tensorflow/commit/4e1e11d6ba2fe7efe1a03356f96172dbf8db365e
