### ISSUE TITLE
could not find function "tf_read_image"

### ISSUE THREAD

**Issue by rainoffallingstar** [rstudio/tensorflow#554]
Hello,I am working with TensorFlow  for R 2.9 and TensorFlow 2.10 in python, I was working to write a grad-cam process and dealing with the following codes:
 `img_path <- get_file(
  fname = "elephant.jpg",
  origin = "https://img-datasets.s3.amazonaws.com/elephant.jpg")
img_tensor <- tf_read_image(img_path, resize = c(299, 299))`
then, the error came as following:
```
Error in tf_read_image(img_path, resize = c(299, 299)) : 
  could not find function "tf_read_image"
```
Is there a solution or It is a bug?

**Comment by t-kalinowski** [comment]
`tf_read_function()` is a local helper function defined in the book: https://github.com/t-kalinowski/deep-learning-with-R-2nd-edition-code/blob/865615f0a979dc7e3f763a38b367768a8421500e/ch09.R#L73

**Comment by rainoffallingstar** [comment]
I see, Thank you very much.
