### ISSUE TITLE
Error: attempt to apply non-function

### ISSUE THREAD

**Issue by doudouricklin** [rstudio/tensorflow#56]
Hi all,
**Installation procedure, as follows:**
python:    /usr/local/python2.7/bin/python2.7
libpython: libpython2.7.so
numpy:     /usr/local/python2.7/lib/python2.7/site-packages/numpy/core/include

**sessionInfo() information, as follows:**
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.3 (Final)
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base
other attached packages:
[1] testthat_1.0.2   **tensorflow_0.3.0**
loaded via a namespace (and not attached):
 [1] httr_1.2.1      magrittr_1.5    R6_2.2.0        tools_3.2.2
 [5] withr_1.0.2     curl_2.3        crayon_1.3.2    memoise_1.0.0
 [9] Rcpp_0.12.8     knitr_1.15.1    git2r_0.16.0    digest_0.6.10
[13] devtools_1.12.0

**My code was:**
library(tensorflow)
sess = tf$Session()

**Then, i got the  error message, as:**
Error: attempt to apply non-function

Cloud you help me to deal with this problem?

And, i am not sure if the version of tensorflow can be updated to 0.12?

Thanks
Doudouricklin

**Comment by doudouricklin** [comment]
Hi all,
After I updated the glibc >2.17,  gcc > 4.8.5(GLIBCXX>3.4.19), and python --configure change to ucs 4
I could use the TensorFlow 0.11 with R and python on Centos 6.3.
I hope this message can help anyone.
Thanks
12/26
Doudouricklin

**Comment by psdhillon** [comment]
Hey @doudouricklin, Have you been able to solve the problem, I am also struggling with the same problem. if i check the function help ?tf, it is giving me results, but when trying to run function tf, it shows Error: attempt to apply non-function. Please assist. Thanks in advance

**Comment by doudouricklin** [comment]
Yes, we run this on Centos 6.3 with updating gcc=4.8.5 and  glibc=2.17
After updating these package, we also reinstall the python 2.7
You can try again
Thanks
