### ISSUE TITLE
Could anyone please solve this for me? 

### ISSUE THREAD

**Issue by Pocket-Tanks** [rstudio/tensorflow#560]
W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
AND
 W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)

**Comment by t-kalinowski** [comment]
How did you install tensorfow?

Can you please fill out the installation issue template: 
https://github.com/rstudio/tensorflow/blob/main/.github/ISSUE_TEMPLATE/installation-issue.md
