### ISSUE TITLE
please include decode_tiff to r-tensorflow ?

### ISSUE THREAD

**Issue by ricds** [rstudio/tensorflow#565]
It would be great to have that feature and allowing multiple channels to be inputted, instead of only 3 or 4 channels. Right now, I have a workaround to decode_raw then extracting the number of bytes of the image, but when I get images of different filesizes that does not work. Thanks

**Comment by t-kalinowski** [comment]
I think you can already via:
```r
tf$io$decode_image(channels = )
```
or perhaps:
```r
# py_install("tfio")
tfio <- reticulate::import("tfio")
tfio$experimental$image$decode_tiff()
```
https://www.tensorflow.org/api_docs/python/tf/io/decode_image
https://www.tensorflow.org/io/api_docs/python/tfio/experimental/image/decode_tiff
