### ISSUE TITLE
On windows platform, tensorflow-gpu verion should not higher than 2.10

### ISSUE THREAD

**Issue by evanliu3594** [rstudio/tensorflow#574]
I followed the installation guide at https://tensorflow.rstudio.com/installation/,  and #524  but unable to start tensorflow-gpu configuration.

After a whole-day trouble-shooting, I found a note at https://tensorflow.google.cn/install/source_windows#gpu
![image](https://github.com/rstudio/tensorflow/assets/55047262/ffb45c1f-3c6a-4e7c-9a8e-39417b6fe6ad)

So if anyone meets the same problem, you should install the tensorflow package with `keras::install_keras(version = "2.10")`.

Maybe this should be noticed in the installation guide.

**Comment by t-kalinowski** [comment]
Thanks for reporting, this is now mentioned on the webpage https://tensorflow.rstudio.com/install/local_gpu

**Comment by t-kalinowski** [comment]
Attempting to install a "gpu" version on Windows shows a warning now, which will typically be displayed right after an error. I.e., this is what you now see if calling `install_tensorflow(version = 'gpu')` on Windows.

![image](https://github.com/rstudio/tensorflow/assets/8462255/57e3c162-d222-45f1-a9d4-afe08fc6c53b)
