### ISSUE TITLE
 {{function_node __wrapped__DecodeWav_device_/job:localhost/replica:0/task:0/device:CPU:0}} Bad format chunk size for WAV: Expected 16 or 18, but got40 [Op:DecodeWav] name: 

### ISSUE THREAD

**Issue by RonKat2008** [rstudio/tensorflow#590]
I am currently trying to compile this code: 
file_contents = tf.io.read_file(Not_Parkinson_File)
wav, sample_rate = tf.audio.decode_wav(file_contents, desired_channels=1)
wav = tf.squeeze(wav, axis=-1)
sample_rate = tf.cast(sample_rate, dtype=tf.int64)
wav = tfio.audio.resample(wav, rate_in=sample_rate, rate_out=16000)
And I am getting this error : {{function_node __wrapped__DecodeWav_device_/job:localhost/replica:0/task:0/device:CPU:0}} Bad format chunk size for WAV: Expected 16 or 18, but got40 [Op:DecodeWav] name: 
Does anyone know how to fix this?

**Comment by t-kalinowski** [comment]
Are you using the R interface to TensorFlow? The above looks like python-only code. This repo is specific to the R interface to TensorFlow.
