### ISSUE TITLE
Tensor flow Installation Issue: the condition has length > 1

### ISSUE THREAD

**Issue by hnguyen20** [rstudio/tensorflow#598]
Hello,

Can someone please help me with the following issue. I have tried every installation methods I could find online but I keep getting the following error when trying to install tensorflow. For example, when I run:
install.packages("keras")
reticulate::install_miniconda()
keras::install_keras()
I got the following error message:

Virtual environment 'r-tensorflow' removed.
Using Python: /home/user/.pyenv/versions/3.10.14/bin/python3.10
Creating virtual environment 'r-tensorflow' ... 
+ /home/user/.pyenv/versions/3.10.14/bin/python3.10 -m venv /home/user/.virtualenvs/r-tensorflow
Done!
Installing packages: pip, wheel, setuptools
+ /home/user/.virtualenvs/r-tensorflow/bin/python -m pip install --upgrade pip wheel setuptools
Requirement already satisfied: pip in /home/user/.virtualenvs/r-tensorflow/lib/python3.10/site-packages (23.0.1)
Collecting pip
  Using cached pip-24.0-py3-none-any.whl (2.1 MB)
Collecting wheel
  Using cached wheel-0.43.0-py3-none-any.whl (65 kB)
Requirement already satisfied: setuptools in /apps/z_install_tree/linux-rocky8-ivybridge/gcc-12.2.0/py-setuptools-59.4.0-frhcj5yjr5ed2whf5v7fdxayyjrhalab/lib/python3.10/site-packages (59.4.0)
Collecting setuptools
  Using cached setuptools-69.5.1-py3-none-any.whl (894 kB)
Installing collected packages: wheel, setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.4.0
    Not uninstalling setuptools at /apps/z_install_tree/linux-rocky8-ivybridge/gcc-12.2.0/py-setuptools-59.4.0-frhcj5yjr5ed2whf5v7fdxayyjrhalab/lib/python3.10/site-packages, outside environment /home/user/.virtualenvs/r-tensorflow
    Can't uninstall 'setuptools'. No files were found to uninstall.
  Attempting uninstall: pip
    Found existing installation: pip 23.0.1
    Uninstalling pip-23.0.1:
      Successfully uninstalled pip-23.0.1
Successfully installed pip-24.0 setuptools-69.5.1 wheel-0.43.0
Virtual environment 'r-tensorflow' successfully created.
Using virtual environment 'r-tensorflow' ...
Error in if (idx != -1) version <- substring(version, 1, idx - 1) : 
  the condition has length > 1
In addition: Warning message:
In system2(python, c("-c", shQuote(command)), stdout = TRUE, stderr = TRUE) :
  running command ''/home/user/.virtualenvs/r-tensorflow/bin/python' -c 'import sys; import pip; sys.stdout.write(pip.__version__)' 2>&1' had status 1

**Comment by t-kalinowski** [comment]
Can you please fill out the installation issue template: https://github.com/rstudio/tensorflow/blob/main/.github/ISSUE_TEMPLATE/installation-issue.md
