### ISSUE TITLE
Vague Error Output

### ISSUE THREAD

**Issue by pourzanj** [rstudio/tensorflow#60]
I know there was an update to fix the issue of vague error outputs, but I'm still only getting the following whenever there is an error:

`Error in py_call(attrib, args, keywords) : basic_string::resize`

I'm running the newest Tensorflow on Ubuntu 14 and the newest version of the R tensorflow library.

**Comment by jjallaire** [comment]
This should be resolved by Rcpp 0.12.9 which is now on CRAN.
