### ISSUE TITLE
Erroneous use of `getNamespaceVersion()` in a comparison

### ISSUE THREAD

**Issue by TimTaylor** [rstudio/tensorflow#607]
As pointed out in this [thread](https://stat.ethz.ch/pipermail/r-devel/2024-October/083675.html) on R-devel, the following line could break at a future (sufficiently high) release of reticulate:

https://github.com/rstudio/tensorflow/blob/2ed2029989ff08c8a714faa82e60f64d84a82e5d/R/package.R#L63

``` r
getNamespaceVersion("reticulate")
#>  version 
#> "1.39.0"
getNamespaceVersion("reticulate") >= "1.99.0"
#> version 
#>   FALSE
getNamespaceVersion("reticulate") >= "1.100.0"
#> version 
#>    TRUE
```

This can be solved with either the suggested `compareVersion()` or via wrapping with `as.package_version()`:

``` r
compareVersion(getNamespaceVersion("reticulate"), "1.38.0") >= 0
#> [1] TRUE
compareVersion(getNamespaceVersion("reticulate"), "1.100.0") >= 0
#> [1] FALSE

as.package_version(getNamespaceVersion("reticulate")) >= "1.38.0"
#> [1] TRUE
as.package_version(getNamespaceVersion("reticulate")) >= "1.100.0"
#> [1] FALSE
```

**Comment by eddelbuettel** [comment]
FWIW that is due to a recent-ish change in R itself.  The change, IIRC, occurred on the 'other side' i.e. we now need to promote the comparison string:

```sh
edd@rob:~$ docker run --rm -ti r-base:4.3.3 Rscript -e 'getNamespaceVersion("base") > as.package_version("4.3.0")'
[1] TRUE
edd@rob:~$ docker run --rm -ti r-base:4.3.3 Rscript -e 'getNamespaceVersion("base") > as.package_version("4.4.0")'
[1] FALSE
edd@rob:~$ 
```

Ditto for 4.4.1 directly:

```sh
edd@rob:~$ Rscript -e 'getNamespaceVersion("base") > as.package_version("4.3.0")'
[1] TRUE
edd@rob:~$ Rscript -e 'getNamespaceVersion("base") < as.package_version("4.5.0")'
[1] TRUE
edd@rob:~$ 
```

**Comment by t-kalinowski** [comment]
Thank you both! This is very helpful and much appreciated. The fix will be on main shortly.
