### ISSUE TITLE
Error in py_call(attrib, args, keywords) : basic_string::_M_replace_aux

### ISSUE THREAD

**Issue by jayendrashinde91** [rstudio/tensorflow#66]
Hi,
I am new to TensorFlow and trying out the MNIST example (Multilayer ConvNet) from your github page.

How do I debug this error:
Error in py_call(attrib, args, keywords) : basic_string::_M_replace_aux

**Comment by pourzanj** [comment]
What version of Rcpp do you have?

**Comment by jayendrashinde91** [comment]
Rcpp version: ‘0.12.8’

**Comment by eddelbuettel** [comment]
We are _very_ close to release 0.12.9, and there was issue in 0.12.8 that can affect `stop()`.  If you can, try upgrade to the (very well tested, stable) GitHub master.
