### ISSUE TITLE
Eliminate deprecation warnings in tf.learn examples

### ISSUE THREAD

**Issue by jjallaire** [rstudio/tensorflow#68]
There are currently lots of deprecation warnings in the tflearn examples. Let's modify this code to use whatever the most up to date idioms are. Note that I've made the minimum required version of TF 0.12 via https://github.com/rstudio/tensorflow/commit/5274628fc603e8eed00d1860fd010190cf0907d3 if that helps.

Note also that I removed all the other warnings (mostly due to the tf$summary migration) here: https://github.com/rstudio/tensorflow/commit/993974e23632e3a617b68b2a16ce5991c9e7fc84

@terrytangyuan

**Comment by terrytangyuan** [comment]
I'll look into it.
