### ISSUE TITLE
Another installation issue

### ISSUE THREAD

**Issue by axelurbiz** [rstudio/tensorflow#72]
The problem is very similar to Issues #24 and #28 (but with a different error message). I've spent the last 4 hrs trying to debug with no luck. 

Sys.setenv(TENSORFLOW_PYTHON="/usr/local/bin/python")
devtools::install_github("rstudio/tensorflow", force = TRUE)
library(tensorflow)
Reloading installed tensorflow
The tensorflow package requires version 0.12 or later of TensorFlow
If you have not yet installed TensorFlow, see https://www.tensorflow.org/get_started/
Configuration:
 python:    /usr/local/bin/python
 libpython: /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
 numpy:     /usr/local/lib/python2.7/site-packages/numpy/core/include

I have checked TensorFlow installation is ok:
>>> import tensorflow as tf
>>> tf.__version__
'0.12.1'

Axel.

**Comment by terrytangyuan** [comment]
Could you check where you tensorflow is installed? (`pip show tensorflow`)

**Comment by axelurbiz** [comment]
Thanks Terry. This is what I get:

$ pip show tensorflow
Name: tensorflow
Version: 0.12.1
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /Users/myname/anaconda/lib/python2.7/site-packages
Requires: mock, six, numpy, protobuf, wheel

**Comment by jjallaire** [comment]
The problem is that tensorflow is installed within Anaconda (which is not
supported by the tensorflow package due to the way it's built) but within
the R session you are using homebrew python. Try pip installing tensorflow
within your homebrew installation (/usr/local/bin/python).

**Comment by axelurbiz** [comment]
Thanks JJ! That worked! Closing issue.
