### ISSUE TITLE
Deep MNIST for Experts: Error

### ISSUE THREAD

**Issue by axelurbiz** [rstudio/tensorflow#73]
When running this example from the RStudio site, I was getting an error message:

Error in py_call(attrib, args, keywords) : 
  ValueError: Cannot execute operation using `run()`: No default session is registered. Use `with sess.as_default():` or pass an explicit session to `run(session=sess)`

The fix is to change the following lines:

train_accuracy <- accuracy$eval(feed_dict = dict(
  x = batch[[1]], y_ = batch[[2]], keep_prob = 1.0))
train_step$run(feed_dict = dict(
  x = batch[[1]], y_ = batch[[2]], keep_prob = 0.5))
train_accuracy <- accuracy$eval(feed_dict = dict(
  x = mnist$test$images, y_ = mnist$test$labels, keep_prob = 1.0))

for these ones:

train_accuracy <- accuracy$eval(session=sess, feed_dict = dict(
  x = batch[[1]], y_ = batch[[2]], keep_prob = 1.0))
train_step$run(session=sess, feed_dict = dict(
  x = batch[[1]], y_ = batch[[2]], keep_prob = 0.5))
train_accuracy <- accuracy$eval(session=sess, feed_dict = dict(
  x = mnist$test$images, y_ = mnist$test$labels, keep_prob = 1.0))

Best,
Axel.

**Comment by jjallaire** [comment]
This example code is intended as a snippet only (i.e. it's not standalone but rather presumed to be within a larger block of code that provides the default session).
