### ISSUE TITLE
ERROR: dependency 'Rcpp' is not available for package 'tensorflow'

### ISSUE THREAD

**Issue by waholulu** [rstudio/tensorflow#77]
Report Rcpp not available while I already installed it.
> library(Rcpp)
> devtools::install_github("rstudio/tensorflow")
Downloading GitHub repo rstudio/tensorflow@master
from URL https://api.github.com/repos/rstudio/tensorflow/zipball/master
Installing tensorflow
"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/wahol/AppData/Local/Temp/Rtmpiwg3qe/devtools53c453d76ce/rstudio-tensorflow-e91f28f"  \
  --library="C:/Users/wahol/OneDrive/文档/R/win-library/3.3" --install-tests 

ERROR: dependency 'Rcpp' is not available for package 'tensorflow'
* removing 'C:/Users/wahol/OneDrive/文档/R/win-library/3.3/tensorflow'
Error: Command failed (1)

**Comment by jjallaire** [comment]
This is an error message from R indicating that Rcpp isn't available.
Unless there is a bug in R it must somehow not be installed or available.
Could you try re-installing Rcpp prior to installing tensorflow?
