### ISSUE TITLE
Cannot install: package fails to load

### ISSUE THREAD

**Issue by NullInfinity** [rstudio/tensorflow#78]
When installing via `devtools::install_github('rstudio/tensorflow'), the compilation proceeds correctly, but then I receive the following error:

```sh
> devtools::install_github('rstudio/tensorflow')
Downloading GitHub repo rstudio/tensorflow@master

<snip>

installing to /home/alex/.local/opt/R/x86_64-pc-linux-gnu-library/3.3/tensorflow/libs
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error : .onLoad failed in loadNamespace() for 'tensorflow', details:
  call: system(paste(shQuote(python), shQuote(system.file("config/config.py", 
  error: error in running command
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/alex/.local/opt/R/x86_64-pc-linux-gnu-library/3.3/tensorflow’
Error: Command failed (1)
```

As can be seen above, I am using R 3.3, and have TensorFlow 0.12 installed with my system python version (3.5).

**Comment by jjallaire** [comment]
There is a python script that is being executed which is yielding an error. Let's try just executing this script standalone to see what the problem might be. The script is here: https://github.com/rstudio/tensorflow/blob/master/inst/config/config.py

Try executing that with the version of python where tensorflow is installed and let me know what errors are produced.

**Comment by NullInfinity** [comment]
Running from my home directory:
```sh
alex@cizin ~ $ python ~/Development/Public/r-tensorflow/inst/config/config.py
Version: 3.5.2 (default, Oct  2 2016, 22:41:13)  [GCC 5.4.0]
VersionNumber: 3.5
LIBPL: /usr/lib64/python3.5/config-3.5m
LIBDIR: /usr/lib64
PREFIX: /usr
EXEC_PREFIX: /usr
Architecture: 64bit
NumpyPath: /home/alex/.local/lib64/python3.5/site-packages/numpy
NumpyVersion: 1.11.3I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcurand.so.8.0 locally

TensorflowPath: /home/alex/.local/lib64/python3.5/site-packages/tensorflow
TensorflowVersion: 0.12.head
```

**Comment by jjallaire** [comment]
Hmm...what is the result of Sys.which("python") in your R session?

If we get the python script to run I see one other problem that may occur -- the CUDA library outputs statements co-minded with the other output. I should be able to get past that by separating stdout and stderr (assuming the CUDA statements are being printed to stderr).

I just made a change to use `system2` rather than `system` for running the script and to try to capture and print more error diagnostics. Could you re-try and let me know how you far?

**Comment by NullInfinity** [comment]
```R
> Sys.which("python")
           python 
"/usr/bin/python"
```

Retried, but unfortunately get the same error (just with `system2` instead of `system` now):
```sh
Error : .onLoad failed in loadNamespace() for 'tensorflow', details:
  call: system2(command = python, args = system.file("config/config.py", 
  error: error in running command
```

**Comment by jjallaire** [comment]
Interestingly this implies that it couldn't run the command (i.e. perhaps
couldn't find the python script?) rather that that it encountered an error
while running the command. So for some reason we can't execute that script
within the R package installation. Let me add some diagnostics then we can
re-try again.

**Comment by jjallaire** [comment]
Okay, I've added a diagnostic to actually print the full command line before executing it, e.g. here's what I see on my system:

```
* installing to library ‘/home/jjallaire/R/x86_64-pc-linux-gnu-library/3.3’
* installing *source* package ‘tensorflow’ ...
make: Nothing to be done for 'all'.
** libs
installing to /home/jjallaire/R/x86_64-pc-linux-gnu-library/3.3/tensorflow/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
/usr/bin/python2.7 '/home/jjallaire/R/x86_64-pc-linux-gnu-library/3.3/tensorflow/config/config.py'
* DONE (tensorflow)
```

Could you re-try and let me know what that command line is for you? (and whether it implies anything about what the problem may be).

**Comment by NullInfinity** [comment]
The command I get is
```sh
/usr/bin/python-exec2c '/home/alex/.local/opt/R/x86_64-pc-linux-gnu-library/3.3/tensorflow/config/config.py'
```

So, unlike in your case, it is running the script with `python-exec` instead of just `python`. I already showed above what I get when I run `config.py` with `/usr/bin/python`. However, I just tried running it with `/usr/bin/python-exec2c` instead and in that case there is no output.

I'm not really sure why R is using `python-exec` instead of `python`, or why `python-exec` doesn't produce any output. But I suppose the lack of output is why the build is failing.

**Comment by NullInfinity** [comment]
Oh, it looks like `python-exec` is actually Gentoo specific: (https://wiki.gentoo.org/wiki/Project:Python/python-exec)

**Comment by NullInfinity** [comment]
It's a wrapper for running a preferred Python implementation, but I don't know much more than that. How does R decide which Python to run `config.py` with? Perhaps there's a way I can force R to run the script with `/usr/bin/python` instead.

**Comment by jjallaire** [comment]
I suggest we debug outside of the context of package loading. This source file is completely standalone and we can use it to figure out what's going on:

https://github.com/rstudio/tensorflow/blob/master/R/tf_config.R

If you source that file and then run:

```
tf_discover_config()
```

That will basically reproduce what's failing during package installation.

One guess is that when we call `normalizePath` on `/usr/bin/python` it's getting resolved to that python-exec script:

https://github.com/rstudio/tensorflow/blob/master/R/tf_config.R#L42

**Comment by NullInfinity** [comment]
It turns out that on Gentoo, `/usr/bin/python` is a symlink to `/usr/bin/python-exec2c` (sorry, turns out I don't know the workings of my OS very well...) As a result,
```R
normalizePath('/usr/bin/path') == /usr/bin/python-exec2c
```

I have now successfully installed the package by setting
```sh
TENSORFLOW_PYTHON = /usr/bin/python3.5 # not a symlink
```
in my environment.

That said, it would still be nice to understand why the script is failing. The following works:
```R
> system2(command='/usr/bin/python', 'config/config.py', stdout=T)
```
The following gives no output (and no error) (*):
```R
> system2(command='/usr/bin/python-exec2c', 'config/config.py')
```
Finally, this command gives the expected error (**):
```R
> system2(command='/usr/bin/python-exec2c', '../inst/config/config.py', stdout=T)
Error in system2(command = "/usr/bin/python-exec2c", "../inst/config/config.py",  : 
  error in running command
```

So:
1) is it necessary to call `normalisePath` on the Python path. If this does not happen, the symlink `/usr/bin/python` is passed directly to `system2` and the system handles the symlink. Are there some other reasons for normalising the path?

2) Hopefully you know R better than me and have some insight into why (*) above gives no error but (**) gives the error.

**Comment by jjallaire** [comment]
I'm sure why /usr/bin/python-exec2c doesn't yield any output or error.

I got rid of the call to `normalizePath` (that was just there for de-duping paths but I think that has proven over-agressive). Could you try again after calling `Sys.unsetenv("TENSORFLOW_PYTHON")` just to confirm that the fix works in your setup?

**Comment by NullInfinity** [comment]
Yes, it now works. Thanks for the quick fix.
