### ISSUE TITLE
Package fails to find PyMalloc libpython

### ISSUE THREAD

**Issue by NullInfinity** [rstudio/tensorflow#80]
Gentoo builds Python to use pymalloc, and as per [PEP 3149](https://www.python.org/dev/peps/pep-3149/), the Python 3 libpython shared libraries, are suffixed with `m`, e.g. `/usr/lib/libpython-3.5m.so`. However, it seems the package only looks for `libpython3.5.so` without any possible suffix.

Indeed,
```R
library(tensorflow)

Python shared library '/usr/lib64/libpython3.5.so' not found, Python bindings not loaded.

<snip>

Detected Python configuration:

python:         /usr/bin/python-exec2c
libpython:      /usr/lib64/libpython3.5.so[NOT FOUND]
version:        3.5.2 (default, Oct  2 2016, 22:41:13)  [GCC 5.4.0]
numpy:          /home/alex/.local/lib64/python3.5/site-packages/numpy
numpy_version:  1.11.3
tf:             /home/alex/.local/lib64/python3.5/site-packages/tensorflow
```

**Comment by NullInfinity** [comment]
My PR #81 seems to correctly set `libpython` to `/usr/lib64/libpython3.5m.so.1.0`. However, loading the package now causes a segfault:
```R
> devtools::install_github('NullInfinity/tensorflow')
<snip>
** testing if installed package can be loaded
sh: line 1: 14816 Segmentation fault      '/usr/lib64/R/bin/R' --no-save --slave 2>&1 < '/tmp/Rtmpx9oqSP/file39ba5e4a1ebd'

 *** caught segfault ***
address 0x50, cause 'memory not mapped'

Traceback:
 1: .Call("tensorflow_py_initialize", PACKAGE = "tensorflow", python,     libpython, pythonhome, python3)
 2: py_initialize(config$python, config$libpython, config$pythonhome,     config$version >= "3.0")
 3: fun(libname, pkgname)
 4: doTryCatch(return(expr), name, parentenv, handler)
 5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 6: tryCatchList(expr, classes, parentenv, handlers)
 7: tryCatch(fun(libname, pkgname), error = identity)
 8: runHook(".onLoad", env, package.lib, package)
 9: loadNamespace(package, lib.loc)
10: doTryCatch(return(expr), name, parentenv, handler)
11: tryCatchOne(expr, names, parentenv, handlers[[1L]])
12: tryCatchList(expr, classes, parentenv, handlers)
13: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
14: try({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps)})
15: library(pkg_name, lib.loc = lib, character.only = TRUE, logical.return = TRUE)
16: withCallingHandlers(expr, packageStartupMessage = function(c) invokeRestart("muffleMessage"))
17: suppressPackageStartupMessages(library(pkg_name, lib.loc = lib,     character.only = TRUE, logical.return = TRUE))
18: doTryCatch(return(expr), name, parentenv, handler)
19: tryCatchOne(expr, names, parentenv, handlers[[1L]])
20: tryCatchList(expr, classes, parentenv, handlers)
21: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
22: try(suppressPackageStartupMessages(library(pkg_name, lib.loc = lib,     character.only = TRUE, logical.return = TRUE)))
23: tools:::.test_load_package("tensorflow", "/home/alex/.local/opt/R/x86_64-pc-linux-gnu-library/3.3")
An irrecoverable exception occurred. R is aborting now ...
ERROR: loading failed
* removing ‘/home/alex/.local/opt/R/x86_64-pc-linux-gnu-library/3.3/tensorflow’
* restoring previous ‘/home/alex/.local/opt/R/x86_64-pc-linux-gnu-library/3.3/tensorflow’
Error: Command failed (1)
```

My guess is this is due to ABI incompatibility: the whole purpose of the `m` suffix is to separable the ABI incompatible PyMalloc Python build from the standard one. This seemed odd, since I assumed the package was built against my (PyMalloc enabled) system libpython during the compilation phase.

However, looking more closely I see the package itself builds a library `libpython.o`. Is this a wrapper for `/usr/lib/libpython.so`? I expect this is where the trouble is coming, but I am not sure (yet?) how to fix it.

**Comment by jjallaire** [comment]
We actually don't build against any version python, rather all symbols are imported dynamically via `dlopen/dlsym`. This is so that we can distribute a single binary on CRAN that works with all versions of Python (including v2 and v3) and so that we don't force recompilation of the package every time someone changes the version of python they are linking to.

So something is going wrong with the lookup of dynamic symbols. I can't debug this firsthand since I don't have your configuration. It might be useful to printf debug starting here:

https://github.com/rstudio/tensorflow/blob/master/src/python.cpp#L902

To see how far we get / where the crash is occurring.

**Comment by jjallaire** [comment]
Another strong possibility is that the layout of the `PyObject` struct is different in the pymalloc version of python. As you can see we declare our own version of the header of PyObject here:

https://github.com/rstudio/tensorflow/blob/master/src/libpython.h#L34-L54

If the memory / field layout is different in pymalloc then things would indeed break! 

Possible remediations include dynamically adapting for pymalloc or figuring out a way to not declare that header (although I think we need it for a bunch of macros that reach into various fields of PyObject).

**Comment by jjallaire** [comment]
Happily the issue seems to have nothing to do with an alternate layout of PyObject (since it looks like it doesn't change for PyMalloc builds).

I recalled that Anaconda also built with PyMalloc and I had trouble binding to it as well. I went back and debugged this and discovered that PyMalloc was exposing an incorrectly formed Unicode string buffer here:

https://github.com/rstudio/tensorflow/commit/3858327d4978a1cd37c101a3de1850e51051b0db

I made that change as well as a change to detect the 'm' suffix. Could you try again on your system to see if the issue is resolved?

**Comment by NullInfinity** [comment]
Yes, it appears to be working now. Thanks.
