### ISSUE TITLE
Error: attempt to apply non-function reported.

### ISSUE THREAD

**Issue by chriswweibo** [rstudio/tensorflow#85]
After updated to v0.5.0, I received this message from my script.
And I went back to the tutorial to double check this. Still this issue. Just two lines:

```{r}
> library(tensorflow)
> sess = tf$Session()
Error: attempt to apply non-function 
```

How can I fix it?

**Comment by jjallaire** [comment]
Can you execute the following to see what your detected configuration looks like:

```r
library(tensorflow)
py_config()
```

**Comment by chriswweibo** [comment]
Results are:

```{r}
> library(tensorflow)
> py_config()
python:         /usr/bin/python
libpython:      /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
pythonhome:     /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7
version:        2.7.10 (default, Jul 30 2016, 19:40:32)  [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
numpy:          /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy
numpy_version:  1.8.1
tensorflow:     [NOT FOUND]
available:      TRUE

python versions found: 
 /usr/bin/python
 /Users/chris/anaconda/bin/python
```

**Comment by jjallaire** [comment]
The problem is that it can't find tensorflow. Where did you install tensorflow?

**Comment by chriswweibo** [comment]
It is a little weird. Actually, my script went through without errors reported before updating.
Do you mean python can not find tensorflow?

**Comment by jjallaire** [comment]
It means that the tensorflow Python package is not located in either /usr/bin/python or
 /Users/chris/anaconda/bin/python. Where did you install it?

**Comment by jjallaire** [comment]
Yes, I mean that python can't find tensorflow.

**Comment by chriswweibo** [comment]
I have re-installed the tensorflow in Rstudio. 
No errors.
