### ISSUE TITLE
Error in Image PreProcessing

### ISSUE THREAD

**Issue by axelurbiz** [rstudio/tensorflow#89]
This is clearly not an error in the package, but due to my lack of fully understanding its functionality. I'm getting an error when attempting to flip an image after cropping. I've tried to put together a reproducible example of my underlying image data.

```r
set.seed(1)
N_IMAGES = 100
images <- array(runif(32*32*3 * N_IMAGES) * 250, dim = c(N_IMAGES, 32, 32, 3))
images.lab <- sample(1L:10L, N_IMAGES, replace = TRUE)
labels <- matrix(0L, nrow = N_IMAGES, ncol = 10)
for (i in 1:N_IMAGES) {
 labels[i, ][images.lab[[i]]] <- 1
}
rm(images.lab)

### Helper functions
library(tensorflow)
sess <- tf$InteractiveSession()

weight_variable <- function(name, shape, stddev, wd = NULL) {
  var <- tf$truncated_normal(shape = shape, stddev = stddev)
  if (!is.null(wd)) {
    weight_decay <- tf$multiply(tf$nn$l2_loss(var), wd, name='weight_loss')
  }
  tf$Variable(var)
}

bias_variable <- function(shape) {
  initial <- tf$constant(0.1, shape = shape)
  tf$Variable(initial)
}

conv2d <- function(x, W) {
  tf$nn$conv2d(x, W, strides = c(1L, 1L, 1L, 1L), padding = 'SAME') 
}

# Placeholders for images
x <- tf$placeholder(tf$float32, shape(NULL, 32L, 32L, 3L))
y_ <- tf$placeholder(tf$float32, shape(NULL, 10L))
x_image <- tf$reshape(x, shape(-1L, 32L, 32L, 3L))

# Randomly crop a [height, width] section of the image.
distorted_image <- tf$random_crop(x_image,  size = shape(-1L, 24L, 24L, 3L))

# Randomly flip the image horizontally.
distorted_image <- tf$image$random_flip_left_right(distorted_image)
```

>>Error in py_call(attrib, args, keywords) : 
>>  ValueError: 'image' must be three-dimensional.

```r
### Additional operations below after fixing error above ###

# Because these operations are not commutative, consider randomizing the order their operation.
distorted_image <- tf$image$random_brightness(distorted_image, max_delta=63)
distorted_image <- tf$image$random_contrast(distorted_image, lower=0.2, upper=1.8)

# Subtract off the mean and divide by the variance of the pixels.
distorted_image <- tf$image$per_image_standardization(distorted_image)

# conv1
W_conv1 <- weight_variable('weights', shape(5L, 5L, 3L, 64L), stddev=5e-2, wd=NULL)
b_conv1 <- bias_variable(shape(64L))
h_conv1 <- tf$nn$relu(conv2d(distorted_image, W_conv1) + b_conv1)
```

Thank you,
Axel.

**Comment by jjallaire** [comment]
I fixed up the formatting of your issue so the R code is displayed syntax highlighted.

I'm afraid that I'm not expert enough on the mechanics of TF to speculate on what might be wrong here. Perhaps another user will have an idea.

**Comment by dfalbel** [comment]
The answer for this is here: http://stackoverflow.com/a/39852683/3297472
`tf$image$random_flip_left_right` expects an image, not a batch of images. If ypu want to apply it for the batch, you will have to use `tf$map_fn`. In R you can do this:

`distorted_image <- tf$map_fn(tf$image$random_flip_left_right, distorted_image)`

**Comment by jjallaire** [comment]
Thanks @dfalbel !

**Comment by axelurbiz** [comment]
Thanks @dfalbel and @jjallaire .  One more question. How about passing additional function arguments to tf$map_fn? For example, I'm trying to apply "tf$image$resize_image_with_crop_or_pad" to the "x_image" tensor from the code above with additional arguments. This is my attempt, but it fails:

distorted_image <- tf$map_fn(tf$image$resize_image_with_crop_or_pad, 
                                                   x_image, target_height = 24, target_width = 24)
Error in py_call(attrib, args, keywords) : 
  TypeError: map_fn() got an unexpected keyword argument 'target_width'

This is the function doc related to the TensorFlow version I'm using:
https://www.tensorflow.org/versions/r0.12/api_docs/python/image/cropping

Thanks,
Axel.

**Comment by jjallaire** [comment]
If you could provide the smallest possible standalone code snippet that illustrates the problem we can reproduce locally and figure out what's going on.

**Comment by axelurbiz** [comment]
@jjallaire opened issue #94 with code snippet. 
btw - I really appreciate your efforts in bringing DL to the R community. You are great!
