### ISSUE TITLE
Should 'parse_flags()' return a dictionary / list of flags?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/tensorflow#90]
E.g. the example I'm porting looks like this:

```python
< ... >
args = parser.parse_args()
arguments = args.__dict__
learn_runner.run(generate_experiment_fn(**arguments), job_dir)
```

We could mimic this with R code like:

```R
< ... >
parse_flags()
arguments = tf$flags$FLAGS$`__dict__`$`__flags`
experiment_fn <- do.call(generate_experiment_fn, arguments)
learn_runner$run(experiment_fn, job_dir)
```

But unpacking the flags in that way is pretty ugly. I would propose that our `parse_flags()` function return the dictionary / list of arguments directly, e.g.

```R
arguments <- parse_flags()
experiment_fn <- do.call(generate_experiment_fn, arguments)
learn_runner$run(experiment_fn, job_dir)
```

**Comment by jjallaire** [comment]
The way FLAGS works in TensorFlow is by side-effects populating a known global variable. This allows other tools to inspect and record the FLAGS (whereas if we just returned a dict they'd be lost in the either). Does that make sense?

**Comment by kevinushey** [comment]
Right, but digging out the actual dictionary of flags after calling `parse_flags()` is a somewhat ugly (as per the above code).

**Comment by jjallaire** [comment]
Check the fully_connected_feed example. You don't need to dig them out,
they are already available in the aliased flags object. Hacky but it's the
most common pattern used right now

**Comment by jjallaire** [comment]
I'll close this for now -- we should develop our own flags functions which can (eventually) wrap whatever eventual standard TF settles on for global flags.
