### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by lawwu** [rstudio/tensorflow#91]
I'm running into an issue when trying to validate tensorflow's installation:

`> sess = tf$Session()
dyld: Library not loaded: @loader_path/../lib/libpython3.5m.dylib
  Referenced from: /Users/lwu/tensorflow/bin/python
  Reason: image not found
dyld: Library not loaded: @loader_path/../lib/libpython3.5m.dylib
  Referenced from: /Users/lwu/tensorflow/bin/python
  Reason: image not found
Error in mapply(function(from, to) paste(lines[from:to], collapse = "\n"),  : 
  zero-length inputs cannot be mixed with those of non-zero length`

When I try to run `py_cong()`, I get a similar error:
`dyld: Library not loaded: @loader_path/../lib/libpython3.5m.dylib
  Referenced from: /Users/lwu/tensorflow/bin/python
  Reason: image not found
Error in mapply(function(from, to) paste(lines[from:to], collapse = "\n"),  : 
  zero-length inputs cannot be mixed with those of non-zero length`

I believe it has to do with how I've installed python on my Mac but having a hard time troubleshooting it.

**Comment by billni** [comment]
You need to yum install libpython

**Comment by lawwu** [comment]
I went back and followed the instructions to install tensorflow with virtualenv: https://www.tensorflow.org/install/install_mac and ran `reticulate::use_virtualenv("~/tensorflow")` and it worked!

```
> library(tensorflow)
> py_config()
python:         /Users/lwu/tensorflow/bin/python
libpython:      /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
pythonhome:     /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7
virtualenv:     /Users/lwu/tensorflow/bin/activate_this.py
version:        2.7.10 (default, Jul 30 2016, 19:40:32)  [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
numpy:          /Users/lwu/tensorflow/lib/python2.7/site-packages/numpy
numpy_version:  1.12.0
tensorflow:     /Users/lwu/tensorflow/lib/python2.7/site-packages/tensorflow

python versions found: 
 /Users/lwu/tensorflow/bin/python
 /usr/bin/python
 /usr/local/bin/python3
 /Users/lwu/anaconda/bin/python

> sess = tf$Session()
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
> hello <- tf$constant('Hello, TensorFlow!')
> sess$run(hello)
[1] "Hello, TensorFlow!"
```

**Comment by jjallaire** [comment]
Great!
