### ISSUE TITLE
I get a noice to advice me compiling the package using sse4. How to do it?

### ISSUE THREAD

**Issue by billni** [rstudio/tensorflow#93]
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.

**Comment by jjallaire** [comment]
That refer to core tensorflow not being compiled with SSE3 rather than the R tensorflow package. e.g. see http://stackoverflow.com/questions/42270739/how-do-i-resolve-these-tensorflow-warnings
