### ISSUE TITLE
Not using the correct Python

### ISSUE THREAD

**Issue by yasirs** [rstudio/tensorflow#95]
I have tensor flow correctly installed for a Python 3.5 installation on Windows 10. The path to this Python binary is "c:\Program Files (x86)\python3\python.exe"

I open up Rstudio, and give the following commands:

```r
Sys.setenv(TENSORFLOW_PYTHON="c:/Program Files (x86)/python3/python.exe")
devtools::install_github("rstudio/tensorflow")
library(tensorflow)
sess = tf$Session()
```
This gives the error:

```
Error: Python module tensorflow was not found.

Detected Python configuration:

python:         C:\Users\un\ANACON~1\python.exe
libpython:      C:/Users/un/ANACON~1/python27.dll
pythonhome:     C:\Users\un\ANACON~1
version:        2.7.11 |Anaconda 2.4.1 (64-bit)| (default, Dec  7 2015, 14:10:42) [MSC v.1500 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\un\ANACON~1\lib\site-packages\numpy
numpy_version:  1.10.1
tensorflow:     [NOT FOUND]

python versions found: 
 c:/Program Files (x86)/python3/python.exe
 C:\Users\un\ANACON~1\python.exe
 C:\PROGRA~2\python3\python.exe
```

Why is it detecting a different installation when I've already supplied the correct path to the environment variable `TENSORFLOW_PYTHON`?

**Comment by jjallaire** [comment]
I'm not sure why, but it's definitely not finding tensorflow in any of the enumerated Python versions. My best guess is that you may be running a 32-bit version of R and all of the installed Python versions are 64-bit. Is that possible?

**Comment by yasirs** [comment]
Thanks @jjallaire I had 64-bit Python, but I 2.7 was in the path. I uninstalled the old Python and changed the Paths to the new one and it now works.

**Comment by jjallaire** [comment]
Great!
