### ISSUE TITLE
yann lecun website is down how to load MNIST?

### ISSUE THREAD

**Issue by McCompexpert** [rstudio/tensorflow#96]
mnist <- datasets$mnist$read_data_sets("MNIST-data", one_hot = TRUE) is resulting in an error

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  URLError: <urlopen error [Errno 110] Connection timed out>
```
It seems that the yann lecun website is down.
Asking google brings this archive page:

https://web.archive.org/web/20150906081542/http://yann.lecun.com/exdb/mnist/index.html

How to adjust the code and load the dataset from an alternative url?

**Comment by jjallaire** [comment]
Looks like the site is back online as of this morning.

**Comment by McCompexpert** [comment]
yep, that's the best solution - it is simply back
